### ISSUE TITLE
Can't Save Shortcuts

### ISSUE THREAD

**Issue by jeickemeyer** [bibletime/bibletime#10]
BibleTime 2.10.1 @ OSX

My attempts to define a second shortcut (or to redefine the first shortcut) for Next verse (for example) do not persist.  All seems well within preferences, but after exiting preferences the new shortcuts don't work, and the changed shortcuts aren't there when reopening preferences.  

I am a new BibleTime user.  Is it just me, or is this a bug?  Or are shortcuts such as "j" or right arrow not valid for Next verse?

Just for fun, I tried changing the relevant shortcut lines in the bibletimerc file after exiting, but no joy.

**Comment by gholmlund** [comment]
Fixed the bug. Closing.
