### ISSUE TITLE
Segmentation fault with core dumped

### ISSUE THREAD

**Issue by CrudeRags** [bibletime/bibletime#103]
Bibletime crashes randomly a few minutes after starting. There is no specific action that triggers it. Sometime it occurs while searching, other times when changing settings or trying to modify the view, etc... 

The message in coredumps are not the same everytime:
> craterib% bibletime
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch9: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch9: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000002 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch9: buf 00000000 00000003 00000004 00000004 00000000
nouveau: ch9: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000003 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000003 00000004 00000004 00000000
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Uncaught TypeError: channel.execCallbacks[message.id] is not a function"
zsh: segmentation fault (core dumped)  bibletime

>craterib% bibletime
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000004 00000004 00000004 00000000
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Uncaught TypeError: channel.execCallbacks[message.id] is not a function"
bibletime: pushbuf.c:727: nouveau_pushbuf_data: Assertion `kref' failed.
zsh: abort (core dumped)  bibletime

>craterib% bibletime
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Uncaught TypeError: btHtmlJsObject.mouseMoveEvent is not a function"
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000003 00000004 00000004 00000000
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch9: buf 00000000 00000004 00000004 00000004 00000000
nouveau: ch9: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch9: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch9: buf 00000000 00000004 00000004 00000004 00000000
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Uncaught TypeError: channel.execCallbacks[message.id] is not a function"
(BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: javascript console : "Uncaught TypeError: channel.execCallbacks[message.id] is not a function"
bibletime: pushbuf.c:727: nouveau_pushbuf_data: Assertion `kref' failed.
zsh: abort (core dumped)  bibletime

OS: Archlinux
Linux version: 4.11.2-1-ARCH
BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7

What is the problem? How to solve it?

**Comment by jaakristioja** [comment]
This is not a bug in BibleTime but in some library it uses either directly or indirectly. Most likely related to the drivers for some nVidia graphics card. See [this Qt forum post](https://forum.qt.io/topic/65491/help-in-locating-source-of-qt-5-6-0-assertion-crash/2) and [this Qt bug report](https://bugreports.qt.io/browse/QTBUG-41242) for details. For a workaround the latter also advises to use `LIBGL_ALWAYS_SOFTWARE=1` in the process environment.
