### ISSUE TITLE
Invalid node channel message / segfault with 2.11.0

### ISSUE THREAD

**Issue by bryce-lynch** [bibletime/bibletime#108]
Since upgrading to 2.11.0-2 Bibletime crashes on start (this is on arch linux - I also saw a qt5-webkit-5.212 update so perhaps other qt5 libs were updated as well):

[5727:5727:0100/000000.811245:ERROR:broker_posix.cc(41)] Invalid node channel message
Segmentation fault (core dumped)
[5725:5725:0100/000000.811258:ERROR:broker_posix.cc(41)] Invalid node channel message

**Comment by jaakristioja** [comment]
This is possibly a duplicate of issue #107. Can you please try the workaround proposed for #107?

**Comment by bryce-lynch** [comment]
I'm now seeing this (already tried reinstalling bibletime):
bibletime: error while loading shared libraries: libsword.so.1.7.4: cannot open shared object file: No such file or directory

**Comment by bryce-lynch** [comment]
Sorry, it seems i forgot to try the 2nd workaround from #107. I'm now happily using bibletime-git without errors. Thanks!
