### ISSUE TITLE
"Invalid node channel message" then segfault

### ISSUE THREAD

**Issue by Geremia** [bibletime/bibletime#109]
Whenever I try opening a bible translation, I get this:
```
(BibleTime 2.11.0_rc2) WARNING: Not a BibleTime Bookmark XML file
[1:1:0100/000000.722656:ERROR:broker_posix.cc(41)] Invalid node channel message
Segmentation fault
```
I'm on Linux 4.9.34.

**Comment by jaakristioja** [comment]
```
(BibleTime 2.11.0_rc2) WARNING: Not a BibleTime Bookmark XML file
```

This is most likely not related to the crash which follows.

```
[1:1:0100/000000.722656:ERROR:broker_posix.cc(41)] Invalid node channel message
```

This is an error message from the Qt web engine, and most likely not a bug in BibleTime.

```
Segmentation fault
```

We're unable to say much more about this crash unless you provide us a backtrace for it. For example, run bibletime in gdb (e.g. using `gdb bibletime`) and once it crashes, use the `thread apply all bt` and `thread apply all bt full` to get a backtrace and a detailed backtrace respectively.

**Comment by Geremia** [comment]
@jaakristioja [Here's the dump](https://gist.github.com/Geremia/4e71c70b19e37e69942ce09cc4e46585) of what occurs when I double-click on a bible to view.

**Comment by Geremia** [comment]
@jaakristioja By the way, I still get this issue, even after upgrading to Qt version 5.9.1.

**Comment by jaakristioja** [comment]
Ok, it appears that this is caused by upstream [Qt issue 61213](https://bugreports.qt.io/browse/QTBUG-61213), which the Qt guys have not yet resolved. In commit d941081e0252b0d9b0cd8d398885b1a8752a59b5 we have already a workaround for this issue, but this is not yet part of any official BibleTime release.
