### ISSUE TITLE
Czech translation of the Mag viewer area label

### ISSUE THREAD

**Issue by Cigydd** [bibletime/bibletime#111]
Dear developers,

I have a question if the Czech translation of the Mag viewer area is correct. It’s translated as „Časopis“, which means „Magazine“ in English. Shouldn’t it be „Lupa“, meaning „Magnifier“?☺

With kind regards,
Cigydd

**Comment by LAfricain** [comment]
You right! It's not well translated. You can correct it directly on [transifex](https://www.transifex.com/bibletime/bibletime/language/cs/)

**Comment by Cigydd** [comment]
Thank you, LAfricain, I sent a team join request.

Dne 03. 10. 19 v 17:28 LAfricain napsal(a):

**Comment by LAfricain** [comment]
You welcome! Welcome on board :)

**Comment by Cigydd** [comment]
Thank you☺

**Comment by gholmlund** [comment]
I verified that the translation was updated to Lupa. Closing.
