### ISSUE TITLE
Verse numbers don’t display

### ISSUE THREAD

**Issue by Cigydd** [bibletime/bibletime#112]
Dear developers,

I’ve compiled BibleTime for myself to prove it and it shows that the verse numbers don’t display even if selected so in the settings.

I think it’s a bug. I’d like to help, though I’m a beginner in C++. Coming from Pascal and Python. 

Bible Time 2.11.0, Linux Mint 18.2 Sonya

Regards,

Cigydd

**Comment by LAfricain** [comment]
>  I’d like to help, though I’m a beginner in C++

Do you know about related projects that are also looking for volunteers? http://crosswire.org/volunteers/ and the [bug tracker](https://tracker.crosswire.org/projects/API/issues/API-217?filter=allopenissues).

**Comment by Cigydd** [comment]
Thank you for directing me to the right place. Hopefully I shall find a task that suits my abilities. Especially the _tesseract_ OCR training seems interesting.

**Comment by LAfricain** [comment]
> Especially the tesseract OCR training seems interesting.

I don't know what you are talking about? Did you find some issue about this on the crosswire bug tracker?

**Comment by Cigydd** [comment]
I found it of the volunteers page (https://crosswire.org/volunteers/), in the _Tesseract work_ section (on the bottom of the page). University of Münster, Germany is looking for collaboration on the digitialization of some Kurt Aland’s work.

**Comment by LAfricain** [comment]
Ah ok cool! 
[lios](https://gitlab.com/Nalin-x-Linux/lios-3)...

**Comment by Cigydd** [comment]
Wow, cool! This tool could help me in other projects too ;-)

**Comment by jaakristioja** [comment]
@Cigydd does the issue still occur? Note that there is a "Show verse numbers" setting under Settings -> Configure BibleTime -> Desk -> Text filters, but that does not affect subwindows which are already open, but is a default setting for new subwindows. Each subwindow has its own "Show verse numbers" setting, which can be accessed from the "Tool" toolbar of each window. Just click on the "Display Settings" icon (the one with a computer screen and a wrench) and select "Show verse numbers".

**Comment by Cigydd** [comment]
Thank you for your response, @jaakristioja. Already noticed that. Closing this issue.
