### ISSUE TITLE
How to display the mag correcty?

### ISSUE THREAD

**Issue by injesus-k** [bibletime/bibletime#115]
Hi
As in the pic it shows up in a strange way. This happened after some time. At the beginning it worked well. I deinstalled BibleTime and also the data and installed BibleTime again. But still the problem is the same. Also the data is still here (bibles, order, settings).
![bibletime show mag does not work](https://user-images.githubusercontent.com/27821498/30358366-5ed7829a-9844-11e7-8ae6-01f095dd72cb.png)
Greetings
Klaus

**Comment by jaakristioja** [comment]
@injesus-k What pic?

**Comment by injesus-k** [comment]
I had to reinstall Linux. The problem is gone.
