### ISSUE TITLE
Release 2.11.1

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#118]
It's long been time.

* Release guide: https://github.com/bibletime/bibletime/wiki/Releasing-BibleTime

**Comment by jaakristioja** [comment]
@mgruner @gholmlund Please upload OS X and Windows binaries.

**Comment by mgruner** [comment]
@jaakristioja @gholmlund thanks! Which version of QT may I use to build? I still have 5.5.1 installed as there had been issues with more recent versions. Is that still the case, or can I go with 5.9.1?

**Comment by gholmlund** [comment]
Martin,

Either version should work. I used 5.9.1 on Windows.

Gary

**Comment by jaakristioja** [comment]
@mgruner I believe the release is done once we have the OS X version uploaded. Please close this once done.

And thank you all for the great work! =)

**Comment by greg-hellings** [comment]
Fedora builds are in flight through the Bodhi testing framework.

**Comment by mgruner** [comment]
@jaakristioja DMG added. Thank you for making this possible!

@gholmlund thanks for the recommendation, I used 5.9.1 now and it seems to improve the UI. 

@greg-hellings would you be so kind to try this locally?

**Comment by greg-hellings** [comment]
@mgruner Trying what? My Mac runs Fedora (DVR with MythTV), although in a pinch I can reboot it to OS X and give it a basic spin if you need it.

**Comment by mgruner** [comment]
Yes, just to verify that the DMG is fine. If that doesn’t cause too much trouble for you.
