### ISSUE TITLE
“bibletime” terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by vapeurs** [bibletime/bibletime#120]
I have just installed Bibletime on Arch. 

**“bibletime” terminated by signal SIGSEGV (Address boundary error)**

When I close the inner window, Bibletime crashes..

**Comment by jaakristioja** [comment]
What version of BibleTime and Qt? Can you please post a backtrace (e.g. using `thread apply all bt` in GDB) of this crash?

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.
