### ISSUE TITLE
Bibletime 2.11.1 on Mac doesn't open previous books

### ISSUE THREAD

**Issue by davidekelly** [bibletime/bibletime#121]
Hi, I had Bibletime 2.11.0 installed on my MacBook Pro (15", 2014, running Sierra/10.12.6) and I had the ESV2001 Bible open along with commentaries from Clarke, Gill, and Burkitt.I just downloaded and install Bibletime 2.11.1. I just dragged the app from the .DMG image into my "Applications" folder and replaced Bibletime 2.11.0. I then ran the app. It starts OK and displays the four book titles across the window frame, but it doesn't display any of the book contents. I checked the ~/Library/Application Support/Sword folder and the books are all still there. I also re-indexed the books OK, but Bibletime doesn't display their contents. Can someone please advise me what's wrong? Thank you.

**Comment by mgruner** [comment]
Hello @davidekelly. Thank you for your report, I can confirm this. As a workaround, I pulled the 2.11.1 build altogether. An update of the QT library seems to fix this locally, but unfortunately, my build toolchain does not work anymore. I will open a new issue for this. Please use 2.11.0 for the time being.
