### ISSUE TITLE
Personal commentary is not writable on Debian

### ISSUE THREAD

**Issue by teusbenschop** [bibletime/bibletime#122]
There is an old bug report on Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=619118

I have compiled BibleTime 2.11.1 from source on Debian.

The issue mentioned in the bug report is still available in version 2.11.1: 

"The personal commentary is installed in
~/.sword/modules/comments/rawfiles/personal using the bookshelf
manager.  There is no button for (it used to be a pencil) or other
documented method for entering a write mode for making notes."

![screen shot 2017-11-02 at 14 34 38](https://user-images.githubusercontent.com/1310167/32328685-07707c28-bfdb-11e7-8bfe-4114939e2b87.png)

**Comment by gholmlund** [comment]
It is available as a context menu under the Personal Commentary. It works for me.
![pedit2](https://user-images.githubusercontent.com/3507381/34657790-b8163f7c-f3de-11e7-9e06-87ecc6979849.png)

**Comment by teusbenschop** [comment]
Thank you for providing the solution to the bug report in Debian. I'll pass your feedback on to the submitter of the bug in Debian. Blessings!
