### ISSUE TITLE
Bibletime and freeBSD 11.1

### ISSUE THREAD

**Issue by Elimelech** [bibletime/bibletime#126]
I see that the bibletime was removed from
http://pkg.freebsd.org/FreeBSD:11:i386/

Will the continuation of the development of Bibletime under freeBSD?
Now I have freeBSD 11.1 and wrote the error:

root @ A9t: / home / luba # bibletime
Shared object "libicui18n.so.58" not found, required by "libsword-1.7.4.so"

Thanks for answers!

**Comment by tabthorpe** [comment]
I have been *very* delinquent in maintaining my ports in FreeBSD for a
little the last little while. This might just be the nudge I need to resume
my work, please stay tuned.

**Comment by tabthorpe** [comment]
I committed a workaround today, please update your ports tree and try rebuild sword from source.

**Comment by Elimelech** [comment]
I'm interested in bibletime (Open source Bible study tool)  This
program is already running on freeBSD11?

2018-01-17 19:09 GMT+02:00, tabthorpe <notifications@github.com>:
> I committed a workaround today, please update your ports tree and try
> rebuild sword from source.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bibletime/bibletime/issues/126#issuecomment-358373620


-- 
Желаю вам поддержки Свыше и успеха!

С уважением,
Ваш  Владимир Тимофиев <http://copi.ru/94717/>

**Comment by Elimelech** [comment]
I install programs in freeBSD like this: pkg install bibletime

When will there be sword and bibletime in the packages on this site? -
http://pkg.freebsd.org/FreeBSD:11:i386/



2018-01-17 19:09 GMT+02:00, tabthorpe <notifications@github.com>:
> I committed a workaround today, please update your ports tree and try
> rebuild sword from source.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bibletime/bibletime/issues/126#issuecomment-358373620


-- 
Желаю вам поддержки Свыше и успеха!

С уважением,
Ваш  Владимир Тимофиев <http://copi.ru/94717/>

**Comment by tabthorpe** [comment]
On Wed, Jan 17, 2018 at 05:59:32PM +0000, Elimelech wrote:
> I install programs in freeBSD like this: pkg install bibletime
> 
> When will there be sword and bibletime in the packages on this site? -
> http://pkg.freebsd.org/FreeBSD:11:i386/
> 

Yes of course, my apologies! As a porter, I do everything from source.

If I recall correctly, and things may have changed, but I think they do
builds weekly, so what I did today *should* be available in about 7
days.

I also received an update today for sword 1.8.0, so I will do a full
test on that and ensure it all works hopefully very soon.


Thomas

-- 
Thomas Abthorpe
thomas@goodking.ca

**Comment by Elimelech** [comment]
Thanks, but bibletime-2.10.1 will be updated?

2018-01-17 22:49 GMT+02:00, tabthorpe <notifications@github.com>:
> On Wed, Jan 17, 2018 at 05:59:32PM +0000, Elimelech wrote:
>> I install programs in freeBSD like this: pkg install bibletime
>>
>> When will there be sword and bibletime in the packages on this site? -
>> http://pkg.freebsd.org/FreeBSD:11:i386/
>>
>
> Yes of course, my apologies! As a porter, I do everything from source.
>
> If I recall correctly, and things may have changed, but I think they do
> builds weekly, so what I did today *should* be available in about 7
> days.
>
> I also received an update today for sword 1.8.0, so I will do a full
> test on that and ensure it all works hopefully very soon.
>
>
> Thomas
>
> --
> Thomas Abthorpe
> thomas@goodking.ca
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bibletime/bibletime/issues/126#issuecomment-358440499


-- 
Желаю вам поддержки Свыше и успеха!

С уважением,
Ваш  Владимир Тимофиев <http://copi.ru/94717/>

**Comment by tabthorpe** [comment]
On Wed, Jan 17, 2018 at 09:14:18PM +0000, Elimelech wrote:
> Thanks, but bibletime-2.10.1 will be updated?
> 

Unfortunately, I do not have a timetable at the moment, I will play with
it in the weeks to follow.


Thomas

-- 
Thomas Abthorpe
thomas@goodking.ca

**Comment by tabthorpe** [comment]
It is with a heavy heart that I have requested my FreeBSD commit bit be turned in for safe keeping. I have not been able to keep up my responsibilities to any the open source projects that I have supported for so long.

I will close this, but sadly there will be not be an update from me. It is my sincerest hope that somebody will adopt my ports, and do a better job than I have these last years.
