### ISSUE TITLE
General Books not recognizing paragraphs.

### ISSUE THREAD

**Issue by TomSullivanInUSA** [bibletime/bibletime#127]
On Debian 9 (Stretch), using XFCE 4.12, a General Book published via OSIS fails to recognize paragraphs. There is not even a space between the contents of two paragraphs. This may be seen using the Westminster module, looking at the Confession. It does not show up so much in the catechisms because titles are used. I have the same problem with a tract I made into a module. This does not seem to be a problem for either Bibles or Commentaries. This may not be limited to OSIS - I do not know how Westminster General Book was created.

**Comment by gholmlund** [comment]
I tested this on Debian 9 with BibleTime 2.10.1 and sword 1.7.3 and I saw the problem. I then built BibleTime 2-11.1 with sword 1.7.3 and the problem was gone. I am closing this as fixed.
