### ISSUE TITLE
Generic book footnotes do not appear.

### ISSUE THREAD

**Issue by BeForgiven-Info** [bibletime/bibletime#128]
Using Bibletime 2.10.1 on Debian 9, XFCE 4.12. In a General Book, footnotes created by (note type="x-footnote" n="2") ... (/note) - substituting parens for angle brackets to avoid problems with triggering HTML - appear in blue, e.g., (2). On mouseover, the a large question mark/arrow is displayed. However, the content of the note does not appear anywhere.

**Comment by gholmlund** [comment]
Can you give us a specific book and location in the book that has this problem? This will help us reproduce it.

**Comment by BeForgiven-Info** [comment]
I have attached a test module with a lot of stuff in it. But you will 
find plenty of footnotes in the sections headed "the westmins" and 
"Questions 11." This is not for publication - it is just a test and 
tutorial module chosen for small size.

Tom Sullivan
info@BeForgiven.INFO
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

**Comment by gholmlund** [comment]
I cannot find any attachment. Please try attaching it again.

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.
