### ISSUE TITLE
Request for installation help.

### ISSUE THREAD

**Issue by BeForgiven-Info** [bibletime/bibletime#129]
Hello:

I tried installing 2.11.1, and downloaded the tarball and tried to run the script. I saw from errors that I needed to install cmake and qt4-default. But I cannot find the package such as Qt5LinguistTools.

What prerequisite packages do I need? I already have the 2.10.1 BibleTime package installed, so obviously what is needed is not there. For that matter, a general list of dependencies would be helpful.

Running Debian 9 (Stretch), XFCE (a Gnome fork).

Help would be much appreciated.

Error text:
$ ./build-release.sh
-- Setting up build environment for BibleTime version 2.11.1
CMake Error at CMakeLists.txt:121 (FIND_PACKAGE):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

**Comment by gholmlund** [comment]
It is important to understand that when you compile a program you need more packages and when you just run it. You need the "dev" packages corresponding to various libraries. They provide the include files.
Also, Qt5 has numerous libraries and tool packages. They easiest thing to do is install the qtcreator package. It is all of the development software for Qt5.
Also, install libsword-dev and libclucene-dev.
