### ISSUE TITLE
BibleTime should remember the search scope

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#13]
Moved from old bugtracker. Comments:
# Martin Gruner devs 2013-02-01 22:58:30 EET

Does not need to be permanent, but at least during one run the search scope should not be reset. It is not helpful when you want to study a topic or book.

**Comment by gholmlund** [comment]
Current scope saved to config and restored.

**Comment by jaakristioja** [comment]
It works! Thanks!
