### ISSUE TITLE
Mag not always working with Hebrew / Strong

### ISSUE THREAD

**Issue by jcornuz** [bibletime/bibletime#132]
Hello,

This is with the Open Scripture Hebrew Bible and the Strong real Hebrew modules. 

Some words work as expected (hovering over with the mouse displays the strong entry in the mag) while others don't (the mag is stuck with the previous entry). In Jonah 1,1 for exemple, the first and last words don't work; in 1.2 it is some words in the middle of the verse that fail.

I have checked with xiphos (which displays the strong numbers embedded in the text) and there are definitely numbers associated with each of the words.
Toggling cantillation, voyel points, changing display style, switching to "standard strong"... none of these make a difference.
This is on Fedora 27, if that makes any difference.

I hope this helps. Many thanks for BibleTime, it is good to see such a project carry on through the years (I remember using BT in my Bible classes in.... 1999!)

Joel

**Comment by gholmlund** [comment]
The following is extracted from Jonah 1:1. There are "?" where the Hebrew chars are. The first and last words have different html formatting that the others. The others have the Strongs reference in the span surrounding the word. The first and last have child spans for the words, so the Strongs reference is in the parent node of the word.  

<span lemma=\"H01961\" morph=\"oshm:HC/Vqw3ms\">
    <span>???</span>
    <span>??????</span>
</span> 

<span lemma=\"H01697\" morph=\"oshm:HNcmsc\">??????</span>
<span>?</span>
<span lemma=\"H03068\" morph=\"oshm:HNp\">???????</span> 
<span lemma=\"H0413\" morph=\"oshm:HR\">???</span>
<span>?</span>
<span lemma=\"H03124\" morph=\"oshm:HNp\">???????</span> 
<span lemma=\"H01121\" morph=\"oshm:HNcmsc\">???</span>
<span>?</span>
<span lemma=\"H0573\" morph=\"oshm:HNp\">?????????</span> 

<span lemma=\"H0559\" morph=\"oshm:HR/Vqc\">
    <span>??</span>
    <span>?????</span></span>
<span>?</span>"

**Comment by gholmlund** [comment]
I modified the javascript code that gets the lemma, etc. from the mouse movements. If the current node does not have any attributes, check the parent node for attributes and use them.

Change made for master and stable-2.11

**Comment by jcornuz** [comment]
Works as excpected with a build from master.
This is amazing! Thanks for the great work!
