### ISSUE TITLE
Questions about translation (French)

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#133]
Hello,
I translated the gui to French, but I'm having some problems. In French we use the non-break space before (or after) some punctuation (?:!;«»), but it seems to be not recognize by QT? I saw this [bug](https://github.com/monero-project/monero-gui/issues/452) for an other software. If I use the shortcut for the non-break space (ALtGr+V) It seems to read it as a normal space, if I use the html code (&nbsp;), it refuse ton convert to qm.
The problem if I use "normal" space, the » can be orphan at the beginning to the sentence...
Any solution?
I noticed also on Transifex, the word Yoryba, but I think this is a mistake no? I should be Yoruba?

Thanks for help.

PS: You should too update the po files, because this to string src/frontend/tips/bttipdialog.cpp:153: 
src/frontend/tips/bttipdialog.cpp:114: are different on transifex.

**Comment by LAfricain** [comment]
On mobile version (thanks for the new version!) Commentaries, book, and daily devotionnal is not internationalized.

**Comment by LAfricain** [comment]
Is no break space a  problem of uft8? As report to #25?
The fr.ts is utf8.
I don't know if it is right but I add tr() to the `bibletime/src/mobile/qml/WindowManager.qml` file for the strings not internationalized as mentioned before.
see the attach file: 
[WindowManager.qml.zip](https://github.com/bibletime/bibletime/files/1800760/WindowManager.qml.zip)

**Comment by gholmlund** [comment]
Adding the tr() to WindowManager.qml is not the right fix for BibleTime Mobile. The category/language names come from sword and are used to create models (Model/View) in Qt which are then viewed by the user. I will have to look at the c++ code to fix this. BibleTime Desktop does it correctly.

**Comment by gholmlund** [comment]
Regarding the non-breaking space. I have not looked at this yet. If anyone else with more translation experience has any ideas, they would be welcome.

**Comment by LAfricain** [comment]
Le 12/03/2018 à 03:04, gholmlund a écrit :
>
> Adding the tr() to WindowManager.qml is not the right fix for
> BibleTime Mobile. The category/language names come from sword and are
> used to create models (Model/View) in Qt which are then viewed by the
> user. I will have to look at the c++ code to fix this. BibleTime
> Desktop does it correctly.
>

OK!

**Comment by LAfricain** [comment]
Le 12/03/2018 à 03:05, gholmlund a écrit :
>
> Regarding the non-breaking space. I have not looked at this yet. If
> anyone else with more translation experience has any ideas, they would
> be welcome.
>

I had never encountered this problem with the po files, I discovered it
with the ts.

**Comment by LAfricain** [comment]
Yes, this [one](https://www.fileformat.info/info/unicode/char/00a0/index.htm) is use by instance by Libreoffice by default. But  this [one](http://www.fileformat.info/info/unicode/char/202f/index.htm) is better, it is the one use by the keybord shortcut altgr + V. I think French translator will use more the second, because we use text editor, or po/ts file managers. But if you have a solution with the first no problem I'll adapt myself.

**Comment by gholmlund** [comment]
I just tried this one and it works.
&#xa0;

**Comment by LAfricain** [comment]
Ok well, I'll do the same!
