### ISSUE TITLE
Bookshelf Manager: 1) "Search Indexes" Feature Missing 2) Library Function Not Working

### ISSUE THREAD

**Issue by SeanMMadden** [bibletime/bibletime#137]
Hello, folks.

THANK YOU for all your work in developing BibleTime. It's exactly what I am looking for in an open-source, locally based Bible app for Linux.

1. Unfortunately, I had to jump through hurdles to add texts (e.g., KJV, Strongs) to my install, as the Bookshelf Manager failed to connect / download the list from the default SWORD repository (tried FTP, SFTP, HTTPS options). Further, once the library seemed (?) to be downloaded and I was able to tick the corresponding box and clicked Next, I was brought to another screen which asked me to choose a language, and yet no options actually populated the screen, meaning I was unable to progress further.

As a workaround, I manually downloaded the ZIP files from the SWORD Project website, and extracted them within my .sword directory. This worked like a charm, though, ideally, it would be good to actually have use of the Bookshelf Manager, for ease of downloading / updating texts.

2. Also, once I had my texts downloaded, installed and viewable within BibleTime, I remain unable to use the crucially important Search function within my KJV text — although it's working beautifully for a couple of the other texts I've installed. I suspect the KJV index file is corrupted and needed reindexing. But when I referred to the BibleTime Handbook, the relevant "Search Indexes" feature discussed within the Bookshelf Manager section is not actually an option/feature in my install (downloaded / installed / removed / reinstalled three times) yesterday. I likewise removed and re-downloaded / installed the relevant KJV text in hope that a newly reinstalled BibleTime app with a likewise newly installed KJV text would force a reindexing of the text. Repeated this process three times, but to no avail.

I'd hugely appreciate any and all help which folk might be able to provide regarding the above two issues. As apart from these two issues, I'm massively impressed by BibleTime, and would love to make it my primary offline Bible resource. But search functionality is, of course, crucial.

Perhaps it is relevant to mention, too, that my Bookshelf Manager (within BibleTime v2.11.1) looks very different from that which appears in the screenshots on http://bibletime.info/. Perhaps the latter are from an earlier, out-of-date version?

Thank you, folks!

Sean

**Comment by SeanMMadden** [comment]
To be clear, while I've successfully worked around both of the issues raised in this report, the underlying bugs remain.

**Comment by gholmlund** [comment]
I have some time now and could work on this. 

Install/Refresh sources issue: Instead of refreshing after 7 days occurs, it would have to refresh the sources the firs time the book shelf wizard is used after BibleTime is started.

Index issue: I would have to add back the functionality for deleting/creating indexes. Since this would involve translation strings, it probably would go on the master branch only.

**Comment by gholmlund** [comment]
![image](https://user-images.githubusercontent.com/3507381/43564169-671d8d3e-95da-11e8-8f06-653fbc56af9d.png)
To be able to delete and create search indexes, I have borrowed the interface for it from BibleTime 2.10, except that it is a dialog opened from the search dialog. Any comments?

**Comment by adamoell** [comment]
That's great gholmlund... people use the Search dialogue often enough that they/we will easily discover it. It'll be good to have this back.

**Comment by gholmlund** [comment]
Updating sources the first time the bookshelf wizard is used per session was added to stable-2.11 and master.
UI for deleting and creating search indexes was added to the master.
