### ISSUE TITLE
The "Free (full syntax)" search with quotes (strict word order) is not working

### ISSUE THREAD

**Issue by SeanMMadden** [bibletime/bibletime#138]
Hello, again, folks.

In follow-up to my previous open Issue, I have found that the "Free (full syntax)" search with quotes (strict word order) is not working. For example if you place "new Jerusalem" (in quotes, that is) into the "Search for" field, the search indicates that there are no results. When in actual fact, this should result in two verses: Revelation 3:12 and Revelation 21:2.

Thank you, again, for any and all help with this matter as well as those noted within my previous post, as it's, of course, important that we be able to have confidence that the search results are accurate.

God bless.

Sean

**Comment by gholmlund** [comment]
I see that it works with some modules (ASV for example) and not with other (ESV2011, KJV). I found that during indexing we have Strongs numbers turned on so they will show up when searching. During indexing of the ESV2011 "new Jerusalem" actually is "<G3588> new <G2537> Jerusalem" and therefore the words are not together. If you search for "new <G2537> Jerusalem" in BibleTime you will get the two verses mentioned above. 
It sees to me that we can either support quote phrases or Strongs, but not both. Comments please.

**Comment by SeanMMadden** [comment]
I'm only interested in using one Bible version: the King James Bible. And, specifically, my concern is that the much-needed "Free (full syntax)" search is not working, as noted in my original issue query, above.

With regard to choosing which of the two — Strongs numbers or quote phrases — there's no question, at least in my mind, that the latter (quote phrases) are infinitely more important. If, that is, it comes down to having to choose between the two; if that's, indeed, the underlying problem here.

> If you search for "new Jerusalem" in BibleTime you will get the two verses mentioned above.

If you mean searching using the "All words" option, you actually end up with four responses. But that's problematic, as it's listing two erroneous verses (1 Kings 11:29, 2 Chronicles 20:5), neither of which contain the text string "new Jerusalem".

Thus the need for the "Free (full syntax)" search with quotes (strict word order) to produce accurate results. Right now, it's not working at all; that is, when using quotes to force a strict word order search.

Thank you, again, for your continued help with this. Apart from this crucial functionality, all's working well.

**Comment by SeanMMadden** [comment]
By the way, this Bible search website is the very best I've found, after using a great many over time:

http://thekingsbible.com/BibleAdvancedSearch.aspx

I've shared it with you as a potentially helpful testing tool, in cross-referencing results between it and BibleTime. For example, type in **new Jerusalem** into the **this exact word or phrase** search field, and you'll see it accurately provides the two valid results: Revelation 3:12 and 21:2, and no others.

Hope this helps. And thanks again for working on this bug. It's the only thing keeping me tied to the above online search option, as otherwise I have everything I need within BibleTime and its modules.

**Comment by gholmlund** [comment]
@jaakristioja I can fix this issue by indexing both with and without text with strongs, etc. On my computer indexing the KJVA was 23 seconds and it went to 40 seconds. Since indexing is infrequent, perhaps this is an acceptable result. ?
