### ISSUE TITLE
Unknow purpose of a window on bt-mobile

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#139]
What the purpose of this window on bt-mobile:
![screenshot_2018-03-23-17-22-11](https://user-images.githubusercontent.com/19690477/37842158-a6dc4e72-2ec1-11e8-9fe5-55c56046da61.png)

**Comment by gholmlund** [comment]
It is the search results window. If you do a search it would be filled with the results. Then it is easy to swipe sideways to get back and forth between this and the main window. Perhaps I should have a "Search Results" title at the top.

**Comment by LAfricain** [comment]
Ok! I will test...

>Perhaps I should have a "Search Results" title at the top.

Yes.
