### ISSUE TITLE
No text in window after upgrade to Qt 5.11

### ISSUE THREAD

**Issue by vmsiam** [bibletime/bibletime#140]
I just upgraded to Bibletime 2.11.1 on Yosemite.
However after the upgrade I find no text in the windows. See image. Thanks for your help.
![bibtime](https://user-images.githubusercontent.com/2777035/39736843-5bae4f18-52ac-11e8-8aaa-5c30a03cd793.jpg)

**Comment by fullrich** [comment]
This exact thing (2.11.1) is happening for me as well on Arch Linux . Upon trying to uninstall and reinstall I received error about could not satisfy dependencies ... it was looking for ``sword 1.8`` and all Arch has is sword 1.7.4.12

**Comment by gholmlund** [comment]
I have confirmed that ubuntu 18.04 and qt 5.11.0 show blank windows. This appears to be a Qt 5.11.0 issue.  I will investigate further.

**Comment by big-corey** [comment]
In Manjaro 17.10 KDE with the latest 4.17.0-1 testing kernel and sword 1.7.4.12, I have the same problem. This aligns with @fullrich 's problem.
