### ISSUE TITLE
distributed version requires libkhtml

### ISSUE THREAD

**Issue by rcabane** [bibletime/bibletime#141]
I'm using OpenSUSE 42.3, and tried to install bibletime from the distribution's repository (version 2.10). It installs fine but fails with the message 
_bibletime: error while loading shared libraries: libkhtml.so.4: cannot open shared object file: No such file or directory_
Indeed, I can only find libkhtml.so.5 in the /usr/lib64 dir. That library comes from the package libkde4 (version 4.14). The library libkhtml.so.4 seems to be very old and I can't find it anyway in rpmfind.

**Comment by gholmlund** [comment]
I have installed OpenSUSE 42.3 kde version and then installed BibleTime from the repository. It runs correctly for me. 
Secondly, BibleTime does not use libkhtml or any other kde library. It only uses Qt and Sword libraries. 
It seems to me that the issue is specific to your computer. Perhaps removing BibleTime and re-installing would help.

**Comment by rcabane** [comment]
Hello
>
> I have installed OpenSUSE 42.3 kde version and then installed 
> BibleTime from the repository. It runs correctly for me.
> Secondly, BibleTime does not use libkhtml or any other kde library. It 
> only uses Qt and Sword libraries.
> It seems to me that the issue is specific to your computer. Perhaps 
> removing BibleTime and re-installing would help.
>
Thank you for your kind answer. Installing bibletime is really easy, and 
succeeds :
===========================================================
/rob@BobLip:~> sudo zypper in bibletime//
//Récupération des métadonnées du dépôt 'openSUSE-Leap-42.3-Update' 
............................................................................................[fait]//
//Construction du cache du dépôt 'openSUSE-Leap-42.3-Update' 
...................................................................................................[fait]//
//Chargement des données du dépôt...//
//Lecture des paquets installés...//
//Résolution des dépendances des paquets...//
//Les 2 NOUVEAUX paquets suivants vont être installés ://
//  bibletime libsword-1_7_5//
//2 nouveaux paquets à installer.//
//Taille de téléchargement totale : 2,1 MiB. Déjà en cache : 0 B. Après 
l'opération, 9,5 MiB d'espace disque supplémentaire sera utilisé.//
//Continuer ? [o/n/...? affiche toutes les options] (o): o//
//Récupération de paquet libsword-1_7_5-1.7.5~a1-29.1.x86_64 (1/2), 
415,1 KiB (  1,6 MiB décompressé)//
//Récupération : libsword-1_7_5-1.7.5~a1-29.1.x86_64.rpm 
.........................................................................................[fait 
(548,3 KiB/s)]//
//Récupération de paquet bibletime-2.11.1-26.3.x86_64 (2/2),   1,7 MiB 
(  8,0 MiB décompressé)//
//Récupération : bibletime-2.11.1-26.3.x86_64.rpm 
..................................................................................................[fait 
(1,1 MiB/s)]//
//Recherche de conflits de fichiers : 
..........................................................................................................................[fait]//
//(1/2) Installation de : libsword-1_7_5-1.7.5~a1-29.1.x86_64 
..................................................................................................[fait]//
//(2/2) Installation de : bibletime-2.11.1-26.3.x86_64 
.........................................................................................................[fait]/
==============================================
Now, I try to execute bibletime :
==============================================
/rob@BobLip:~> bibletime --help//
//bibletime: error while loading shared libraries: libkhtml.so.4: cannot 
open shared object file: No such file or directory/
==============================================
So I'm baffled ..
Best regards
Robert

**Comment by gholmlund** [comment]
Something is not consistent. You originally said you were using BibleTime 2.10, but your logs above show version 2.11.1 and sword 1.7.5. 
With my openSUSE 42.3 it installs  BibleTime 2.10 and sword 1.7.4. Have you enabled some different repositories?

**Comment by greg-hellings** [comment]
It's especially relevant to note that there was never any Sword 1.7.5 ever made. So wherever you're pulling packages from is a little bit out of touch with reality.

**Comment by rcabane** [comment]
Hello
I tried again with Bibletime, removing the version I previously 
downloaded from the Education repository and reinstalling the standard 
version from the 42.3 repo.
The installation is easy et succeeds; the command rpm -q bibletime gives :
bibletime-2.10.1-6.4.x86_64
Lauching bibletime --help gives, however, the error message :
bibletime: error while loading shared libraries: libkhtml.so.4: cannot 
open shared object file: No such file or directory
I tried also
rpm -q --requires bibletime
giving :
libQtCore.so.4()(64bit)
libQtDBus.so.4()(64bit)
libQtGui.so.4()(64bit)
libQtWebKit.so.4()(64bit)
libQtXml.so.4()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libclucene-core.so.1()(64bit)
libclucene-shared.so.1()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
libsword-1.7.4.so()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsLzma) <= 4.4.6-1

So ... I don't know what to do.
Sincereley
Robert

**Comment by rcabane** [comment]
Le 25/05/2018 à 02:23, gholmlund a écrit :
> ldd /usr/bin/bibletime

Hopefully ! Here it is :

         linux-vdso.so.1 (0x00007fff30b55000)
         libQtWebKit.so.4 => /usr/lib64/libQtWebKit.so.4 
(0x00007fe559f6c000)
         libQtGui.so.4 => /usr/lib64/libQtGui.so.4 (0x00007fe5592ac000)
         libQtDBus.so.4 => /usr/lib64/libQtDBus.so.4 (0x00007fe55902f000)
         libQtXml.so.4 => /usr/lib64/libQtXml.so.4 (0x00007fe558de9000)
         libQtCore.so.4 => /usr/lib64/libQtCore.so.4 (0x00007fe5588fe000)
         libclucene-core.so.1 => /usr/lib64/libclucene-core.so.1 
(0x00007fe55855e000)
         libclucene-shared.so.1 => /usr/lib64/libclucene-shared.so.1 
(0x00007fe55833e000)
         libsword-1.7.4.so => /usr/lib64/libsword-1.7.4.so 
(0x00007fe557fa0000)
         libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fe557c17000)
         libm.so.6 => /lib64/libm.so.6 (0x00007fe55791a000)
         libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe557703000)
         libc.so.6 => /lib64/libc.so.6 (0x00007fe55735e000)
         libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007fe557154000)
         libjpeg.so.8 => /usr/lib64/libjpeg.so.8 (0x00007fe556eea000)
         libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007fe556cad000)
         libwebp.so.5 => /usr/lib64/libwebp.so.5 (0x00007fe556a4e000)
         libxslt.so.1 => /usr/lib64/libxslt.so.1 (0x00007fe55680f000)
         libz.so.1 => /lib64/libz.so.1 (0x00007fe5565f9000)
         libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007fe556290000)
         libgstapp-1.0.so.0 => /usr/lib64/libgstapp-1.0.so.0 
(0x00007fe556082000)
         libgstpbutils-1.0.so.0 => /usr/lib64/libgstpbutils-1.0.so.0 
(0x00007fe555e4d000)
         libgstvideo-1.0.so.0 => /usr/lib64/libgstvideo-1.0.so.0 
(0x00007fe555bcc000)
         libgstaudio-1.0.so.0 => /usr/lib64/libgstaudio-1.0.so.0 
(0x00007fe555973000)
         libgstbase-1.0.so.0 => /usr/lib64/libgstbase-1.0.so.0 
(0x00007fe555713000)
         libgstreamer-1.0.so.0 => /usr/lib64/libgstreamer-1.0.so.0 
(0x00007fe5553eb000)
         libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 
(0x00007fe55519a000)
         libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 
(0x00007fe554e8a000)
         libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x00007fe554bc3000)
         libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 
(0x00007fe554985000)
         libQtOpenGL.so.4 => /usr/lib64/libQtOpenGL.so.4 
(0x00007fe554685000)
         libQtNetwork.so.4 => /usr/lib64/libQtNetwork.so.4 
(0x00007fe554340000)
         libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe554123000)
         libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007fe553eb7000)
         libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007fe553b79000)
         libfreetype.so.6 => /usr/lib64/libfreetype.so.6 
(0x00007fe5538dd000)
         libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007fe5536d5000)
         libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007fe5534b8000)
         libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007fe5532a8000)
         libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007fe55309d000)
         libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007fe552e97000)
         libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007fe552c8c000)
         libXinerama.so.1 => /usr/lib64/libXinerama.so.1 
(0x00007fe552a89000)
         libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007fe552877000)
         libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007fe552630000)
         libdl.so.2 => /lib64/libdl.so.2 (0x00007fe55242c000)
         librt.so.1 => /lib64/librt.so.1 (0x00007fe552224000)
         /lib64/ld-linux-x86-64.so.2 (0x00007fe55c2c0000)
         libicui18n.so.52.1 => /usr/lib64/libicui18n.so.52.1 
(0x00007fe551e10000)
         libicuuc.so.52.1 => /usr/lib64/libicuuc.so.52.1 
(0x00007fe551a91000)
         libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007fe551821000)
         liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007fe5515f8000)
         libgsttag-1.0.so.0 => /usr/lib64/libgsttag-1.0.so.0 
(0x00007fe5513be000)
         liborc-0.4.so.0 => /usr/lib64/liborc-0.4.so.0 (0x00007fe55113a000)
         libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 
(0x00007fe550f36000)
         libffi.so.4 => /usr/lib64/libffi.so.4 (0x00007fe550d2d000)
         libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fe550abe000)
         libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007fe550894000)
         libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007fe550629000)
         libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 
(0x00007fe5501d0000)
         libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 
(0x00007fe54ffcd000)
         libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 
(0x00007fe54fdca000)
         libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 
(0x00007fe54fbc4000)
         libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 
(0x00007fe54f9c1000)
         libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007fe54f792000)
         libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007fe54f58f000)
         libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007fe54f38d000)
         libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007fe54f175000)
         libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 
(0x00007fe54ef70000)
         libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fe54ed50000)
         libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007fe54eb4a000)
         libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007fe54e939000)
         libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007fe54e72a000)
         libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007fe54e525000)
         libicudata.so.52.1 => /usr/lib64/libicudata.so.52.1 
(0x00007fe54e324000)
         libidn.so.11 => /usr/lib64/libidn.so.11 (0x00007fe54e0f0000)
         libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007fe54dec5000)
         libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 
(0x00007fe54dc7d000)
         liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 
(0x00007fe54da6e000)
         libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2 
(0x00007fe54d822000)
         libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007fe54d61e000)
         libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007fe54d34e000)
         libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 
(0x00007fe54d11e000)
         libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fe54cf1a000)
         libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 
(0x00007fe54cd0d000)
         libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fe54caf6000)
         libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007fe54c8d9000)
         libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fe54c6d5000)
         libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fe54c4af000)

**Comment by gholmlund** [comment]
The ldd command did not show any reference to libkhtml. It looks normal. Is it possible you have more than one BibleTime installed somewhere. Please run from the command line "/usr/bin/bibletime" and report if this has the error.

**Comment by rcabane** [comment]
YES !
You have found the weakness : I had an old executable bibletime file 
within my ~/bin directory.
So I erased it, /et voila.
/Many thanks !/
/Robert/
/
