### ISSUE TITLE
Update translations from Transifex for stable-2.11

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#142]
Before releasing 2.11.2, the translations need to be updated from Transifex. I think I only did `tx pull --all` and pushed the changes to stable-2.11, although I should have also executed `make messages howto handbook` according to [Translation Management](https://github.com/bibletime/bibletime/wiki/Translation-Management). The latter command fails on my machine. First because the `/usr/share/xml/docbook/stylesheet/nwalsh/html/chunk.xsl` file is missing on my machine. If I corrected the latter filename in [`cmake/docs/docs.xsl`](https://github.com/bibletime/bibletime/blob/master/cmake/docs/docs.xsl#L3) to `/usr/share/sgml/docbook/xsl-stylesheets/html/chunk.xsl` I still got some other weird errors probably due to reasons explained in [Translation Management](https://github.com/bibletime/bibletime/wiki/Translation-Management).

Given that we want to release 2.11.2 soon, can someone else please ensure that the translations are updated? Thanks!

**Comment by gholmlund** [comment]
I had to fix 8 tagging errors on transifex, then I was able to update the translation to git.
