### ISSUE TITLE
Release 2.11.2

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#146]
It's long been time.

* Release guide: https://github.com/bibletime/bibletime/wiki/Releasing-BibleTime

**Comment by jaakristioja** [comment]
Thanks to God and His servants for the great work! :-)

@mgruner @gholmlund Please upload OS X and Windows binaries.

**Comment by gholmlund** [comment]
Latest BibleTime for Windows is uploaded. Thanks for the release Jaak

**Comment by mgruner** [comment]
Just uploaded mac build, with bundled qt 5.11.0. @gholmlund the windows binary seems quite small (just 9 MB), is this correct?
@jaakristioja thanks a lot for a new build.

**Comment by mgruner** [comment]
@jaakristioja @gholmlund I had to delete the mac build again, as there is more information about what is broken now. Need to investigate.

**Comment by gholmlund** [comment]
@jaakristioja  @mgruner  I deleted the windows version because the size is wrong. I will investigate.

**Comment by mgruner** [comment]
@jaakristioja @gholmlund new mac build available, should fix the issues.

**Comment by gholmlund** [comment]
@jaakristioja @mgruner  New Windows installer available.
