### ISSUE TITLE
BibleTime 2.11.2 Crashes When I Try To Download New Books

### ISSUE THREAD

**Issue by vikramght** [bibletime/bibletime#147]
BibleTime 2.11.2 Crashes When I Try To Download New Books In Windows 8.1 !! - 

Re-Download & Re-installation Doesn't Solves The Problem.

**Comment by gholmlund** [comment]
Please tell us which OS you are running. If it is windows, download the install file again. A problem was found in the earlier version.

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.
