### ISSUE TITLE
qt5 version support changed stopping it compiling with earlier versions

### ISSUE THREAD

**Issue by timsoftgit** [bibletime/bibletime#150]
the bibletime v2.11.2 release has changed the CMakeLists.txt file which causes an issue for slackware linux distribution because the most recent version of qt5 available for stable slackware (14.2) is 5.7.1
changing the line containing  VERSION 5.9  to VERSION 5.7.1 fixes this and allows bibletime to compile and run on slackware. If this change doesn't effect compiling with newer versions of qt5, the following patches the file to work.
sed -i "s/VERSION 5.9/VERSION 5.7.1/g" CMakeLists.txt
any chance of this being implemented? thanks..

**Comment by jaakristioja** [comment]
Support for Qt versions earlier than 5.9 was removed in the stable-2.11 branch with 7b19f3695414667728cd2f083bc75a582eae197f and in the master branch with 508e6fbc70220ca658e53f9474c1bb908dce495f to work around [Qt bug 35164](https://bugreports.qt.io/browse/QTBUG-35164). See https://github.com/bibletime/bibletime/issues/86 for details. Using Qt earlier than version 5.9 would probably mean broken translations. We're not switching back to older versions of Qt unless we have a working workaround for the Qt bug. Personally, I'm sceptical that someone will create a new workaround.

**Comment by timsoftgit** [comment]
the curent stable version of slackware (15.0) comes with qt5.15.3 so this is not an issue on this end either any more,
