### ISSUE TITLE
Increasing text size

### ISSUE THREAD

**Issue by Nicdeane** [bibletime/bibletime#151]
I have just started using Bibletime. It is great! However, the text size is a little small and this makes reading books (Calvin's Institutes) a little difficult. Is there a way of increasing the text size?
I am running Linux Mint 19 Cinnamon with a 1920 x 1080 display, which although it means there is lots of visible space, the text is quite small. Ctr-++ to zoom in doesn't appear to change anything in Bibletime.
Any help here?
Many thanks!
Nic Deane

**Comment by gholmlund** [comment]
Look at the menu "Settings/Configure"BibleTime". Then choose "Font", your language, and "use Custom Font". Then pick the desired font and size.

**Comment by Nicdeane** [comment]
Thank you very much! I've followed your instructions and all is now fine. I had tried that but where the Font Style was initially set at Bold Italic, when you move to Size there was nothing there and it didn't accept any size number. However, when you move down to Bold, Italic or Regular the Font Size comes up and you can choose the Font size. Many thanks for answering my query. God bless,
Nic
