### ISSUE TITLE
Leaving

### ISSUE THREAD

**Issue by mgruner** [bibletime/bibletime#152]
Dear @jaakristioja and @gholmlund,

for me, it is time now to leave BibleTime, after many years. I want to ask if there is anything that you need from me, that I can contribute with regards to documentation, access information or similar.

Best regards and God bless,
Martin

**Comment by jaakristioja** [comment]
Hope all is fine? Thank you for everything! =] Lord bless!

I can't currently think of anything we need. If anything should come up later, is it okay to contact you?

**Comment by gholmlund** [comment]
We will miss you. Thanks for all the many contributions you have made.
