### ISSUE TITLE
fails to compile on Ubuntu 18.04 with cmake error "Could not find CLucene."

### ISSUE THREAD

**Issue by BlackArbsCEO** [bibletime/bibletime#154]
Here's the full error output:

```
========================= Installation results ===========================
/media/bcr/HDD/Bible_Notes/bibletime-2.11.2/build-release.sh: 6: [: Linux: unexpected operator
-- Setting up build environment for BibleTime version 2.11.2
-- CLucene library dir not found.
CMake Error at cmake/FindCLucene.cmake:80 (MESSAGE):
  Could not find CLucene.
Call Stack (most recent call first):
  CMakeLists.txt:131 (FIND_PACKAGE)
```
Also the relevant package is installed and updated:
`libclucene-core1v5 is already the newest version (2.3.3.4+dfsg-1)`

**Comment by greg-hellings** [comment]
Did you, in fact, install the CLucene development package?

**Comment by BlackArbsCEO** [comment]
if this is not the correct package please advise:
```
libclucene-core1v5 is already the newest version (2.3.3.4+dfsg-1)
```

**Comment by greg-hellings** [comment]
You need the dev package that goes with it. Often something like `libclucene-core1v5-dev` or similar. That includes the headers, pkg-config files, and other things that allow packages to compile against it.

**Comment by BlackArbsCEO** [comment]
thanks for the assist, with that and a few more packages i got it working.
