### ISSUE TITLE
bibletime does not display texts

### ISSUE THREAD

**Issue by dabeegmon** [bibletime/bibletime#155]
Greetings
Have had a version of bibletime for use for quite a few years and have appreciated its usefulness. Only wish for item would be an easy way to add one's own comments into a file attached to the texts.
This last install of bibletime 2.11.1 on Debian buster (10 or testing) running lxde for a windowing system was quite challenging taking quite a long time and there being a whole mountain of dependencies.
When I asked the help column for the version besides that information a number of problem boxes open. They seem to all start with 
>/home/memyself/data:text/html;charset=UTF-8,%3html%3E%3Chead% . . .   .
What this might refer to isn't even greek it seems more like unobtainium. If more information is desired please advise.

**Comment by jaakristioja** [comment]
Hello @dabeegmon !

I'm sorry, but I couldn't completely understand what you're saying. It seems that there should actually be two issues:
1. A feature request about commenting works.
2. A bug report which causes something like `/home/memyself/data:text/html;charset=UTF-8,%3html%3E%3Chead%....` being displayed somewhere, when running BibleTime 2.11.1 on Debian Buster?

For clarity, these should probably be tracked as separate issues here on GitHub. So I kindly suggest, that we continue discussing the bug under this issue, and please file a new issue about the feature request / wish item with a bit more detail.

Regarding the bug, can you please be more detailed about how to reproduce this? I'm not sure if I understood correctly what you meant by "help column" and "version". Did you mean to say that you chose "Help" from the main menu of BibleTime, then a submenu opened and you selected "About BibleTime" from that submenu, and then a dialog window opened in which the problem can be observed? Can you please attach a screenshot that?

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.

**Comment by dabeegmon** [comment]
On Mon, Mar 9, 2020 at 3:36 PM Jaak Ristioja <notifications@github.com>
wrote:

> Closed #155 <https://github.com/bibletime/bibletime/issues/155>.
>
>
> Well - - - - as nothing I did changed anything - - - including some
updates a few
weeks ago - - - - I've stopped trying to use Bibletime. As program would
start
and then as I started to do anything Bibletime would close. Couldn't find
anything
in any logs (yes I looked) so - - - - - waiting until maybe something
changes.

Regards
