### ISSUE TITLE
I have translate the BibleTime GUI 100% finished one year ago in 

### ISSUE THREAD

**Issue by aaron2wh** [bibletime/bibletime#156]
I have translate the BibleTime GUI 100% finished one year ago in    https://www.transifex.com/bibletime/bibletime/translate/#zh_TW/bibletime_ui/2401365
but it seems there is no one to check it and compile to the update version.
I have waited for a whole year, now. it seems the Chinese GUI not released in the updated version. could you help with that.
thank you in ahead for the sake of all Chinese users.
please...........

**Comment by aaron2wh** [comment]
sorry, I am not a coder, I am just a normal Chinese Christian want to do something for our chinese users.
the links above made me crazy. 
is there a easy way for me to translate the unfinished part just like the way here. 
https://www.transifex.com/bibletime/bibletime/translate/#zh_TW/bibletime_ui/2401365

**Comment by gholmlund** [comment]
@jaakristioja  I have done a 'tx pull' and nothing was updated. It seems we already have the latest of all translations. I used linguist on the bibletime_ui_zh_TW.ts file. It looks fully translated. I ran BibleTime 2.11.2 with LANG=zh_tw. It looked fully translated. 
@aaron2wh  Are you using BibleTime version 2.11.2?

**Comment by jaakristioja** [comment]
@gholmlund What I mean is that perhaps the strings on Transifex are not up to date. The problem might be that the translators have some old copy of the strings on transifex.com. For example, we have `tr("Rename folder")` in [`src/frontend/bookmarks/cbookmarkindex.cpp:98`](https://github.com/bibletime/bibletime/blob/stable-2.11/src/frontend/bookmarks/cbookmarkindex.cpp#L98) and the related `<message>` element in [messages/bibletime_ui_zh_TW.ts:2021](https://github.com/bibletime/bibletime/blob/stable-2.11/i18n/messages/bibletime_ui_zh_TW.ts#L2021) shows that it is unfinished:

```xml
    <message>
        <location filename="../../src/frontend/bookmarks/cbookmarkindex.cpp" line="98"/>
        <source>Rename folder</source>
        <translation type="unfinished"></translation>
    </message>
```

However, when I search for "Rename folder" on Transifex.com, [it shows nothing](https://www.transifex.com/bibletime/bibletime/viewstrings/#zh_TW/bibletime_ui?q=text%3A%27Rename+folder%27). It seems that these strings are alltogether missing on transifex.com.

**Comment by gholmlund** [comment]
I ran the "make messages howto handbook" commands documented on the wiki. And did a tx push. It did not update the "Rename folder" and several other bookmark related phrases. 
Looking at the cmake scripts, I cannot see anything that runs the qt "lupdate" command. I will look into this.

**Comment by gholmlund** [comment]
The lupdate was working. I was able up update transifex from our latest stable-2.11 sources. The final problem I has was downloading the bibletime_ui_zh_TW.ts from transifex. It had translations for several of the bookmark actions that were not in git. It would not sync down correctly, even after I did a tx force (-f). I finally deleted that file locally and then pulled it from transifex. 

I checked several other languages and they were up to date for those bookmark translations. It seems that transifex was silently failing to sync that one file. 

Transifex does need a translation for "Rename folder" in the  zh_TW language.

**Comment by aaron2wh** [comment]
> @jaakristioja I have done a 'tx pull' and nothing was updated. It seems we already have the latest of all translations. I used linguist on the bibletime_ui_zh_TW.ts file. It looks fully translated. I ran BibleTime 2.11.2 with LANG=zh_tw. It looked fully translated.
> @aaron2wh Are you using BibleTime version 2.11.2?

I am using 2.11.2 Mac version, no chinese UI

**Comment by jaakristioja** [comment]
Hmm... the zh_TW translation only has 17 untranslated strings in the stable-2.11 branch, so it should be mostly translated.

@aaron2wh If you don't see any translated strings at all, maybe you're experiencing the same issue as described in https://github.com/bibletime/bibletime/issues/148 but with Chinese instead of Russian?

**Comment by gholmlund** [comment]
I believe the problem we have had with translation updates it related to file timestamps. The Transifex pull and push commands rely on timestamps to know when to move the file. However, git does not set timestamps based on modification times. They are set to the check out time. When pulling files from Transifex I believe we need to use the force option, "-f" to ensure we get the translated strings. We probably also need to use force when pushing if we are sure nothing on Transifex is newer we have locally.

**Comment by gholmlund** [comment]
I have documented the timestamp issue on the BibleTime Wiki. I believe this will take care of issues with the documentation not getting updated correctly. I am closing this issue.

**Comment by aaron2wh** [comment]
https://www.transifex.com/bibletime/bibletime/translate/#zh_TW/bibletime_ui/2401455
please check, I have finished this GUI translation to Chinese, anyone in charge can add to the BibleTime Mac dmg?

**Comment by jaakristioja** [comment]
Reopening to be sure this makes it to version 3.0.3.

**Comment by aaron2wh** [comment]
thanks a lot, waiting for the new release

**Comment by jaakristioja** [comment]
Translations updated in stable-3.0 branch by 778714d96afcab490cea72072f691c0cd4b186c5. Closing. Thanks!
