### ISSUE TITLE
Bibletime will not start after re-install

### ISSUE THREAD

**Issue by RobinBownes** [bibletime/bibletime#158]
I am running Linux Mint 18.3 with a Mate GUI. I have been using Bibletime for a number of years already. That means that I've worked through and overcome many "issues" over the years.

A while ago, I reinstalled my OS, and thus reinstalled Bibletime (current ver 2.10, if I remember correctly). Since then, I've experienced numerous problems. Blank text in settings and configuration screens, missing Personal Commentary file (even though I'd restored it from a backup), Window layouts not persistent, MAG text not working, etc.

So, I removed Bibletime, purged the installation, and manually removed the //usr/share/bibletime folder, as well as the (hidden) .bibletime folder in my home folder.

I then reinstalled Bibletime, apparently with no errors. However, Bible time does not start at all now. When I run Bibletime from the command line, I receive the following error message - 

(BibleTime 2.10.1) WARNING: Cannot find icon directory relative to "/usr" 
(BibleTime 2.10.1) FATAL: Error initializing directory cache!
Please report this bug at http://bugs.bibletime.info/Aborted

Since http://bugs.bibletime.info/Aborted no longer seems to exist, I'm reporting the bug here. I'd appreciate any and all feedback and assistance. Thanks.

**Comment by gholmlund** [comment]
Please tell us how you installed BibleTime. From repository? From source?

Does the directory /usr/share/bibletime/icons exist and is readable?

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.
