### ISSUE TITLE
The translation from Transifex seems not to be update

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#159]
I translated to French the howto and the handbook on transifex, but it seems not to be update on github. Please have a look on it.

**Comment by LAfricain** [comment]
I discovered, that the bibletime_ui_fr.ts is missing from /i18n/messages/?  Any explanation?

**Comment by gholmlund** [comment]
The bibletime_ui_fs.ts was removed on Dec. 16, 2013.
814d1b511dce38bd247e86f9c11eb9a8307f0d10
It appears that this was done on purpose because it was not being maintained at that time.

**Comment by gholmlund** [comment]
Moving translations from transifex is not automatic. Someone has to do it. Also, it is only done for stable branches such as stable-2.11. The master branch is not supposed to be connected to transifex.
Normally translations are pulled from transifex, updated to the latest source, and pushed back to transifex when we start the process of a new release. Then before the release we pull from transifex again to get the final translations for that release.

**Comment by LAfricain** [comment]
Ok thanks for these explanations, for the stable branch is it possible to do something. And why do po files appear for other languages? Finally the manual and the tutorial are not updated for two years.
How to solve the problem :) ?

**Comment by LAfricain** [comment]
Some relation with #156?

**Comment by gholmlund** [comment]
I tried to update to stable-2.11 from transifex and found one change, the handbook_fr. When I try to build with it I get multiple parse errors. I don't know the handbook format and tools and cannot fix these problems.

**Comment by gholmlund** [comment]
I am not sure about any relationship with #156. The version numbers, 2.11.0_rc1, are on the master branch. You need to be on the stable-2.11 branch. Version numbers on the master are not meaningful. The stable-2.11 branch has version 2.11.2 which is the last released version.

**Comment by LAfricain** [comment]
OK I will tried with the stable branch. What kind of errors in the translation?

**Comment by gholmlund** [comment]
Errors from handbook_fr:
../docbook/hdbk-operation.docbook:54: parser error : Opening and ending tag mismatch: para line 54 and mousebutton
        <para>Si vous cliquez avec le bouton </mousebutton>droit</mousebutton> d
                                                           ^
../docbook/hdbk-operation.docbook:54: parser error : Opening and ending tag mismatch: sect3 line 51 and mousebutton
        <para>Si vous cliquez avec le bouton </mousebutton>droit</mousebutton> d
                                                                              ^
../docbook/hdbk-operation.docbook:63: parser error : Opening and ending tag mismatch: sect2 line 26 and para
Society.</para>
               ^
../docbook/hdbk-operation.docbook:64: parser error : Opening and ending tag mismatch: sect1 line 24 and sect3
      </sect3>
              ^
../docbook/hdbk-operation.docbook:106: parser error : Opening and ending tag mismatch: chapter line 1 and sect2
    </sect2>
            ^
../docbook/hdbk-operation.docbook:161: parser error : Opening and ending tag mismatch: para line 157 and mousebutton
le bouton </mousebutton>droit</mousebutton> de la souris et choisissez
                        ^
../docbook/hdbk-operation.docbook:161: parser error : Opening and ending tag mismatch: sect3 line 149 and mousebutton
le bouton </mousebutton>droit</mousebutton> de la souris et choisissez
                                           ^
../docbook/hdbk-operation.docbook:164: parser error : Opening and ending tag mismatch: sect2 line 118 and para
<guimenuitem>HTML</guimenuitem> (éditeur de base en mode graphique).</para>
                                                                            ^
../docbook/hdbk-operation.docbook:176: parser error : chunk is not well balanced

**Comment by gholmlund** [comment]
You are correct, there were other files that update. I did not use the "force" option to download them. But, I also see parse errors in the howto_fr.

**Comment by gholmlund** [comment]
howto_fr
../docbook/howto-importance.docbook:115: parser error : xmlParseEntityRef: no name
est le discours direct du Seigneur Dieu (Mc 7, 6 & Is 29, 13). C'est de
                                                  ^
../docbook/howto-importance.docbook:321: parser error : chunk is not well balanced

^
../docbook/index.docbook:54: parser error : Failure to process entity howto-chap1
&howto-chap1; &howto-chap2; &howto-chap3;
             ^
../docbook/index.docbook:54: parser error : Entity 'howto-chap1' not defined
&howto-chap1; &howto-chap2; &howto-chap3;
             ^
../docbook/howto-interpretation.docbook:264: parser error : Opening and ending tag mismatch: quote line 254 and para
eau. Les Mormons devaient rire en réalisant le ridicule de leur position.</para
                                                                               ^
../docbook/howto-interpretation.docbook:265: parser error : Opening and ending tag mismatch: para line 254 and section
    </section>
              ^
../docbook/howto-interpretation.docbook:298: parser error : Opening and ending tag mismatch: section line 228 and chapter
</chapter>
          ^
../docbook/howto-interpretation.docbook:299: parser error : Premature end of data in tag chapter line 1

^
../docbook/howto-interpretation.docbook:299: parser error : chunk is not well balanced

^
../docbook/index.docbook:54: parser error : Failure to process entity howto-chap3
&howto-chap1; &howto-chap2; &howto-chap3;
                                         ^
../docbook/index.docbook:54: parser error : Entity 'howto-chap3' not defined
&howto-chap1; &howto-chap2; &howto-chap3;
                                         ^
unable to parse ../docbook/index.docbook
make[3]: *** [CMakeFiles/howto_fr.dir/build.make:57: CMakeFiles/howto_fr] Error 6

**Comment by LAfricain** [comment]
Ok I Corrected both handbook and howto, please try again, and say me.

**Comment by gholmlund** [comment]
There were still errors in both handbook and howto. I was able to fix them. Here is a summary.
    Missing ";" after &bibletime (multiple)
    Missing </quote>
    Missing </guimenuitem>
I have pushed these changes to transifex and github. This includes other languages also.

**Comment by LAfricain** [comment]
Thank you very much! I close the issue.
