### ISSUE TITLE
Broken icon in title bar under Wayland

### ISSUE THREAD

**Issue by Alexander-Wilms** [bibletime/bibletime#160]
This
```
#if (QT_VERSION >= QT_VERSION_CHECK(5, 7, 0)) && defined(Q_OS_LINUX)
	a.setDesktopFileName("bibletime");
#endif
```
would need to be added here: https://github.com/bibletime/bibletime/blob/master/src/frontend/bibletimeapp.cpp#L34

Here's a PR for another Qt application with the same issue with screenshots: https://github.com/texstudio-org/texstudio/pull/330

For the Flatpak, that line will need to be patched to use the reverse DNS ID.

**Comment by Alexander-Wilms** [comment]
Because In didn't apply and test this change.

**Comment by gholmlund** [comment]
I did testing with KUbuntu18.10 with Wayland. The title bar icon was there with or without setDesktopFileName. Then testingwith Fedora 28 Gnome/Wayland the icon was NOT there with or without setDesktopFileName. It seems to me that Wayland is a moving target.

**Comment by gholmlund** [comment]
@Alexander-Wilms
![bt2](https://user-images.githubusercontent.com/3507381/47748256-9ecfb000-dc47-11e8-8c8f-84e889460add.png)
I am using KUbuntu18.10 with Wayland. Just running BibleTime (master branch) I see that there is no window border as in the left of the attached picture. 
Doing: env |grep QT I see:
   QT_WAYLAND_FORCE_DPI=96
   QT_WAYLAND_DISABLE_WINDOWDECORATION=1
   PLASMA_USE_QT_SCALING=1
   QT_AUTO_SCREEN_SCALE_FACTOR=0

If I unset QT_WAYLAND_DISABLE_WINDOWDECORATION I see the window border and the BT icon as in the right of the attached picture. 

Which operating system are you using?
Which Qt?

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.
