### ISSUE TITLE
bibletime doesn't open after update of pclos xfce

### ISSUE THREAD

**Issue by hwms43** [bibletime/bibletime#162]
here is what I get when I try to start the program from the command line:

bibletime
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-hw-xfce'
(BibleTime 2.11.2) WARNING: QVariant::load: unknown user type with name Search::BtSearchOptionsArea::SearchType.
(BibleTime 2.11.2) FATAL: Could not find QtWebEngineProcess
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted

**Comment by gholmlund** [comment]
What operating system are you using? 
Was BibleTime installed from package or source? 
What Qt version?

**Comment by hwms43** [comment]
Os is Linux PCLOS xfce. It was installed from package. Don't know anything about qt. It still works in the Kde version of PCLOS Linux.

⁣Sent from BlueMail ​

**Comment by gholmlund** [comment]
Looking at the Fatal message above, I believe that the dependencies of BibleTime were not correct specified by the pclos  team. The QWebEngine package is missing.
