### ISSUE TITLE
Cannot display maps

### ISSUE THREAD

**Issue by Castir** [bibletime/bibletime#165]
Thank you for the replies.  I was quite pleasantly surprised to find Bibletime in Linux Mageia 6's Core Release on the ISO disc.  I converted my Windows 8 Lenovo Laptop after some weird experiences and losses with forced updates to 8.1 & 10.  

I still always update when alerted, yet see this is still at 2.11.0 on the Help tab in the app.  The maps were no deal breakers, just inquisitive to see how things have changed in the meantime.  The specific divisions by borders at the time can also throw good light on prevailing mental attitudes.  Loosely speaking of course.  May be update on maps long known already.

Problem solved though, I think.  Went to pkgs.org just now and got the
Archlinux  bibletime-2.11.2-1-x86_64.pkg.tar.xz.  Oops!  I see I have the .zip and .dmg (apple-diskimage) as well.  Downloaded on 28/11/2018.  Must have gotten distracted with other things Linux as I am a newbie there too.

Anyway, not too serious.  Carry the Bible in my head as it is.  No brag. Godly gifts of good memory plus Strict Calvinist upbringing.  Then one day, I started questions.  Was that a blast?!  Christ never qualified who or what you may ask or find.  God will happily answer even your dumbest most ornery question.  As long as you have an interest in a real answer.

Thank you, gentlemen.  I am sure this issue is now settled.

**Comment by Castir** [comment]
I have just started using Bibletime after installing various books, commentaries and maps.  The maps interested me and I tried to open some from the bookshelf, but all I get is shown in the attachment.

![maps_2018-11-27_12-02-06](https://user-images.githubusercontent.com/16389510/49074342-2dcaea80-f23d-11e8-8f08-3eb85e474fab.png)

The maps are there, I can display them as .jpg files in Ristretto.

![ristretto_2018-11-27_12-11-14](https://user-images.githubusercontent.com/16389510/49074580-9d40da00-f23d-11e8-8d7e-91162b02c468.png)

**Comment by jaakristioja** [comment]
Works for me with BibleTime 2.11.2 on Linux.

**Comment by Castir** [comment]
This is a Lenovo G580 converted to first Mageia 5, then clean installed to 6.  Mageia is a fork off Mandrake/Mandriva.  Great distro. Very easy to install and work with.  Fedora, RPM.  That was after several bad crashes and critical data losses from forced updates from Win8 to 8.1 and 10.  Yes, I do do backups, but lost two days.

Some detail;
[caldon@localhost ~]$ lspcidrake -v
xhci_pci        : Intel Corporation|7 Series/C210 Series Chipset Family USB xHCI Host Controller [SERIAL_USB] (vendor:8086 device:1e31 subv:17aa subd:3977) (rev: 04)
Card:Intel 810 and later: Intel Corporation|2nd Generation Core Processor Family Integrated Graphics Controller [DISPLAY_VGA] (vendor:8086 device:0116 subv:17aa subd:3977) (rev: 09)
ehci_pci        : Intel Corporation|7 Series/C216 Chipset Family USB Enhanced Host Controller #1 [SERIAL_USB] (vendor:8086 device:1e26 subv:17aa subd:3977) (rev: 04)
ehci_pci        : Intel Corporation|7 Series/C216 Chipset Family USB Enhanced Host Controller #2 [SERIAL_USB] (vendor:8086 device:1e2d subv:17aa subd:3977) (rev: 04)
shpchp          : Intel Corporation|7 Series/C210 Series Chipset Family PCI Express Root Port 2 [BRIDGE_PCI] (vendor:8086 device:1e12) (rev: c4)
unknown         : Intel Corporation|2nd Generation Core Processor Family DRAM Controller [BRIDGE_HOST] (vendor:8086 device:0104 subv:17aa subd:3977) (rev: 09)
i2c_i801        : Intel Corporation|7 Series/C216 Chipset Family SMBus Controller [SERIAL_SMBUS] (vendor:8086 device:1e22 subv:17aa subd:3977) (rev: 04)
snd_hda_intel   : Intel Corporation|7 Series/C216 Chipset Family High Definition Audio Controller [MULTIMEDIA_AUDIO_DEV] (vendor:8086 device:1e20 subv:17aa subd:3977) (rev: 04)
alx             : Qualcomm Atheros|AR8162 Fast Ethernet [NETWORK_ETHERNET] (vendor:1969 device:1090 subv:17aa subd:3979) (rev: 10)
mei_me          : Intel Corporation|7 Series/C216 Chipset Family MEI Controller #1 [COMMUNICATION_OTHER] (vendor:8086 device:1e3a subv:17aa subd:3977) (rev: 04)
ath9k           : Qualcomm Atheros|AR9485 Wireless Network Adapter [NETWORK_OTHER] (vendor:168c device:0032 subv:17aa subd:3218) (rev: 01)
lpc_ich         : Intel Corporation|HM76 Express Chipset LPC Controller [BRIDGE_ISA] (vendor:8086 device:1e59 subv:17aa subd:3977) (rev: 04)
shpchp          : Intel Corporation|7 Series/C216 Chipset Family PCI Express Root Port 1 [BRIDGE_PCI] (vendor:8086 device:1e10) (rev: c4)
unknown         : Intel Corporation|7 Series Chipset Family 6-port SATA Controller [AHCI mode] [STORAGE_SATA] (vendor:8086 device:1e03 subv:17aa subd:3977) (rev: 04)
hub             : Linux 4.14.100-desktop-1.mga6 ehci_hcd|EHCI Host Controller [Hub|Unused|Full speed (or root) hub] (vendor:1d6b device:0002)
hub             : Intel Corp.|Integrated Rate Matching Hub [Hub|Unused|Full speed (or root) hub] (vendor:8087 device:0024)
hub             : VIA Labs, Inc.         |USB2.0 Hub              [Hub|Unused|Full speed (or root) hub] (vendor:2109 device:2811)
hub             : VIA Labs, Inc.         |USB2.0 Hub              [Hub|Unused|Full speed (or root) hub] (vendor:2109 device:2811)
usb_storage     : Seagate |Expansion [Mass Storage|SCSI|Bulk-Only] (vendor:0bc2 device:2312)
usb_storage     : Seagate |Expansion [Mass Storage|SCSI|Bulk-Only] (vendor:0bc2 device:2312)
btusb           : Atheros Communications|Bluetooth USB Host Controller [Wireless|Radio Frequency|Bluetooth] (vendor:0cf3 device:3004)
rtsx_usb        : Generic|USB2.0-CRW (vendor:0bda device:0129)
hub             : Linux 4.14.100-desktop-1.mga6 ehci_hcd|EHCI Host Controller [Hub|Unused|Full speed (or root) hub] (vendor:1d6b device:0002)
hub             : Intel Corp.|Integrated Rate Matching Hub [Hub|Unused|Full speed (or root) hub] (vendor:8087 device:0024)
hub             : Linux 4.14.100-desktop-1.mga6 xhci-hcd|xHCI Host Controller [Hub|Unused|Full speed (or root) hub] (vendor:1d6b device:0002)
usbhid          : Logitech|USB Receiver [Human Interface Device|Boot Interface Subclass|Mouse] (vendor:046d device:c52f)
hub             : Linux 4.14.100-desktop-1.mga6 xhci-hcd|xHCI Host Controller [Hub|Unused|Full speed (or root) hub] (vendor:1d6b device:0003)
hid_generic     : Logitech USB Receiver
hid_generic     : Logitech USB Receiver
[caldon@localhost ~]$ 

I cannot get the .xz file to install 2.11.2.  It is of a Debian strain.  Attempted a number of variants.
 2.11.0 comes with the Mageia Core Release.

But, happiness.  The maps are not critical, was just veery curious to see them. Killed the cat . . .
