### ISSUE TITLE
Adding commentary from soniclight - plano texas

### ISSUE THREAD

**Issue by drduker** [bibletime/bibletime#167]
What can we do to get this open commentary into the Bibletime app?

It looks like they have pdf and html versions of the commentary available.

https://planobiblechapel.org/soniclight/
Dr. Thomas Constable - Professor at DTS

btw, just started using bibletime and really excited about using it and that it is actually in github

**Comment by gholmlund** [comment]
Dr. Constable,

Contributions of commentaries and other modules need to be done through 
the Crosswire Bible Society. I have some references to their site listed 
below.

https://crosswire.org

https://wiki.crosswire.org/Main_Page

https://wiki.crosswire.org/DevTools:Modules

They will require a license or copyright statement from the author that 
clearly allows the document to be distributed.

Gary Holmlund

**Comment by drduker** [comment]
Sorry, my bad.  I’m actually not Dr. Constable.  He is the main writer.


My name is Lucas Pick.
