### ISSUE TITLE
MacOS shortcut keys should not be the same as common system shortcuts

### ISSUE THREAD

**Issue by drduker** [bibletime/bibletime#168]
MacOS shortcut keys should not be the same as common system shortcuts (command+x is used for "Cut" strings to paste them)

To go ahead a chapter with command+x 
or 
go back a chapter with command+X

I suggest making this command+left arrow to go back a chapter and command+right to go forward a chapter as defaults.  Another option would be to use alt-x or control x.  The goal is to allow the user to just use one had for navigation so they can use their mouse with the other hand.

Instead of Y for moving books, why not use B since it is closer to the command key and B is for book!

**Comment by gholmlund** [comment]
1. You cannot "Cut" a BibleTime text window so it is not a conflict of functionality. 
2. It is very easy for each person to change the shortcuts to those they like. 
Other BibleTime users may be used to the current shortcuts so I am hesitant to change them.
