### ISSUE TITLE
Bug - Bible not updating when switching chapter

### ISSUE THREAD

**Issue by drduker** [bibletime/bibletime#169]
Bug - Bible not updating when switching chapter

I've noticed several times that the chapter or anything else in the bible resource isn't updating after adding and removing "Show scripture cross-references".

Symptom: the text of where it last is working doesn't move.  

Work around:  Close the resource and reopen it usually fixes it.

Environment:
2.11.12 -bibletime version
macos 10.14.1
macbook pro 15in 2017

Side note: how could I debug this myself while it is running live?  I would like to see what is happening in the code.  This way I could provide more helpful/detailed feedback.  Thanks!

**Comment by gholmlund** [comment]
I cannot reproduce this on my macos 10.14.

**Comment by gholmlund** [comment]
Closing as not reproducible.
