### ISSUE TITLE
Help, Background Color has changed

### ISSUE THREAD

**Issue by internet-police** [bibletime/bibletime#171]
Hello everyone!
A few days ago the background color in my bibletime has suddenly changed from the standard grey to black,
i find this very irritating and want it back to normal, but there seems to be no option in the settings to change the background color.
Where does bibletime have its color scheme?

I suspect this has changed after i installed python-pywal which is a tool to autogenerate color schemes for the terminal but im not 100% sure on this,
all other programms still have the grey color theme except bibletime

**Comment by jaakristioja** [comment]
By background colour you mean the background colour behind the text of the works you're studying in BibleTime, or the background colour other widgets in the application as well? Could you please attach a screenshot of this to this issue?

Are you sure that this only affects BibleTime or other non-themed Qt-based applications as well?

Please also state the version of BibleTime, the version of Qt and the flavour and version of your operating system.

**Comment by jaakristioja** [comment]
The display style templates which can be selected from "Settings" → "Configure BibleTime" → "Display" → "Available display styles" are usually stored in `/usr/share/bibletime/display-templates`.

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.
