### ISSUE TITLE
After text search copy verse does not work Linux Peppermint 9

### ISSUE THREAD

**Issue by lombarddirk** [bibletime/bibletime#174]
Good Day
After a text search when you drag the verse to the main display to view it you cannot copy that text but only the whole chapter. You have to close the Bible and reopen it before you can copy the text.

**Comment by gholmlund** [comment]
I cannot reproduce this. The verse copy is only enabled if you are hovering over a verse number or a verse cross reference. Perhaps this explains what you were seeing?

**Comment by jaakristioja** [comment]
Please reopen if this still occurs.
