### ISSUE TITLE
Clicking on a verse number triggers high CPU and window no longer updates

### ISSUE THREAD

**Issue by big-ox** [bibletime/bibletime#175]
bibletime --version
BibleTime 2.11.2, QT 5.11.3
on Fedora 28.

When clicking on a verse number, one of the QtWebEngineProc processes consumes a large amount of CPU.  gstack shows a bunch of threads waiting/polling.  The Bible window's text is not responsive, but navigation shortcut keys will update the verse number in the picker widget.

**Comment by jaakristioja** [comment]
This is very likely a Qt regression. I doubt we can do anything from our side to fix it. Sorry!

**Comment by gholmlund** [comment]
I was able to reproduce this problem using Fedora 8, BibleTime 2.11.2, and Qt .11.2. Also reproduced with Qt 5.11.3. It quit being a problem with Qt 5.12.2.
Since this is clearly Qt related and appears to be fixed in Qt, I am closing this.
