### ISSUE TITLE
Bibletime crashes on Ubuntu 18.04 x64 kernel 4.18.0-16-generic

### ISSUE THREAD

**Issue by cscj001** [bibletime/bibletime#176]
I tried to launch Bibletime in the environment shown above from a terminal and here is the error message I receive: `/usr/bin/bibletime

(BibleTime 2.11.1) WARNING: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
(BibleTime 2.11.1) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)`

Any ideas as to what is going wrong?  Bibletime was working under kernel 4.18.0-15-generis.

**Comment by jaakristioja** [comment]
Looks like some graphics driver issue. Try running BibleTime with `QT_OPENGL=software` set as an environment variable to force Qt to use software rendering for OpenGL. And also make sure that `DISPLAY` is set to the correct value in case you're running on X.

Other than that, this is not an issue specific to BibleTime. You can find more about this issue by searching the web. I think this is not something we would be able work around in BibleTime in any reasonable timeframe.

**Comment by cscj001** [comment]
The environment variable was the answer.  What in the message told you that, and where could I have gone to find out about the proper setting for the environment variable?  Thank you for the quick response.

**Comment by jaakristioja** [comment]
> What in the message told you that

I just searched for "Failed to create OpenGL context for format QSurfaceFormat" on the web and found a bunch of related issues.

> where could I have gone to find out about the proper setting for the environment variable?

I'm not sure what the best solution for setting the environment variable would be. And I don't know the specifics of setting environment variables in Ubuntu. Setting `QT_OPENGL` system-wide might not be a good solution, perhaps it would help if you write a wrapper script for BibleTime instead, e.g. something like this:

```sh
#!/bin/sh
export QT_OPENGL=software
exec /usr/bin/bibletime "$@"
```

**Comment by jaakristioja** [comment]
This also duplicates #125 and #170.
