### ISSUE TITLE
GA code on bibletime.github.io / bibletime.info

### ISSUE THREAD

**Issue by mgruner** [bibletime/bibletime#177]
Dear all, bibletime.github.io / bibletime.info uses a google analytics code with a property that no longer exists. Please consider removing GA support or using a new property for this.
Thank you very much and best regards,
Martin

**Comment by jaakristioja** [comment]
Didn't verify. Decided to remove the GA tracker. https://github.com/bibletime/bibletime.github.io/commit/7799c7a01c25ff0332c8243de9d17e4f395f29b3
