### ISSUE TITLE
BT doens't display Psalm with canonical titles

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#178]
The psalms in a module with canonical titles are not displayed. the windows is empty:
The osis is like that:
```
<div type="subSection">
        <chapter sID="Ps.4" osisID="Ps.4" n="4"/>
        <title>Preghiera della sera</title>
        <p></p>
        <!-- d -->
        <title type="psalm" canonical="true"><verse sID="Ps.4.1" osisID="Ps.4.1" n="1"/>Al maestro del coro. Per strumenti a corda. Salmo. Di Davide.<verse eID="Ps.4.1"/></title>
        <lg>
          <l level="1"><verse sID="Ps.4.2" osisID="Ps.4.2" n="2"/>Quando ti invoco, rispondimi, Dio, mia giustizia:</l>
          <l level="1">dalle angosce mi hai liberato;</l>
          <l level="1">pietà di me, ascolta la mia preghiera. <verse eID="Ps.4.2"/></l>
```
If the osis it like that, it displays but with a return to the line after the verse number:
```
<div type="subSection">
        <title>Preghiera del mattino</title>
        <p>
          <verse sID="Ps.5.1" osisID="Ps.5.1" n="1"/>
          <verse eID="Ps.5.1"/>
       </p>
        <!-- d -->
        <title type="psalm" canonical="true">Al maestro del coro. Per flauti. Salmo. Di Davide.</title>
        <lg>
          <l level="1"><verse sID="Ps.5.2" osisID="Ps.5.2" n="2"/>Porgi l'orecchio, Signore, alle mie parole:</l>
          <l level="1">intendi il mio lamento. <verse eID="Ps.5.2"/></l>
```
On xiphos, I have not this issue, in the first option. For the second I have, but it is the the good way to write osis tag.

**Comment by gholmlund** [comment]
Please tell us the module used for the above example?

**Comment by LAfricain** [comment]
It's a private module :) But I can send you the osis file with psalms. it is converted from usfm to osis with u2o.py.
[ps.osis.zip](https://github.com/bibletime/bibletime/files/2984101/ps.osis.zip)

**Comment by gholmlund** [comment]
I took your ps.osis.xml file and used osis2mod to make a module. Your file represents the top issue above. 
Using xiphos 4.07 I see the text without any title. I also see the extra return after the line number. 
Using BibleTime 2.11.stable I see the text without any title. The extra return is not there.
Using BibleTime master branch it is like 2.11.stable.

I have attached screen shots of what I saw. The title is missing in all cases. I am not very knowledegable about Osis. Can anyone else can comment on this?

**Comment by gholmlund** [comment]
![bibletime_master](https://user-images.githubusercontent.com/3507381/54630460-21aaa900-4a37-11e9-83df-9b79c7e9c1ed.png)
![bibletime2 11-stable](https://user-images.githubusercontent.com/3507381/54630462-22433f80-4a37-11e9-8b81-27f3aee61d8a.png)
![xiphos4 07](https://user-images.githubusercontent.com/3507381/54630463-22433f80-4a37-11e9-87bb-7a2f6018fea4.png)

**Comment by LAfricain** [comment]
I did a mistake look the psalm 3, you will see the blank windows. I tried multiples combination of osis tag. But even for the psalm 4 I have not the same result...
If you can read the psalm 3 that means I have a problem, maybe I need to compile the last version (I use 2.11.2+e0cc...)

**Comment by gholmlund** [comment]
With psalm 3, the 1st verse is blank. All other verses look correct. This is the same with both BibleTime versions and with Xiphos.

Note: Xiphos is using sword 1.7.3. My BibleTime was using sword 1.8.1

**Comment by LAfricain** [comment]
Okay, almost you have a blank verse :) The question is what to do? For the Psalm 3 I respected the usfm and osis rules. Then is it possible to do something in BT?Or need I to manage other with the tags? But if I do this last solution, the problem will appear with an other module that use canonical titles...

**Comment by LAfricain** [comment]
I use xiphos with 1.8.1 too. I tested on Ubuntu 18.04 the Bibletime in the official repo. The same.

**Comment by gholmlund** [comment]
I tried it with sword's diatheke command line tool. I also saw the 3:1 issue. 
Are you sure of the syntax. The Osis examples I have found do not have the verse inside of the title tags.

**Comment by gholmlund** [comment]
Since sword's diatheke tool show the problem, it cannot be BibleTime's problem. Closing

**Comment by LAfricain** [comment]
Maybe you close a little bit quickly :) Because BT can't display this part of the bible even XIphos does. And I discover that BT on android displays it as well??
What to you mean with diatheke?

**Comment by gholmlund** [comment]
Diatheke is a command line tool that is part of the sword package. It can be used on a command line to show the text for a specified verse.
Which part is missing from BT?

**Comment by LAfricain** [comment]
>  Which part is missing from BT?

All the Psalms with canonicals titles.

**Comment by gholmlund** [comment]
I willl use Psalms 3 in you module has an example.
 
With BibleTime I don't see a title or verse 1. Verses 2 and on are displayed.

With Xiphos I don't see a title or verse 1. Verses 2 and on are displayed.  (Same as BT)

Using diatheke (diatheke -b Psalm -k Psalms 3:1-5) I don't see verse 1. I do see verses 2 and on. The title text is there, but it is inside of "title" tags which are not valid in the body of html. 

Since diatheke (sword) shows the problem, it is not a BibleTime problem. I believe it is likely that  your Psalms module has incorrect markup.

**Comment by LAfricain** [comment]
> With BibleTime I don't see a title or verse 1. Verses 2 and on are displayed.

Strange to me nothing is displayed?? Only on BT mobile all is well displayed, but not in the desktop version.
![psalm3](https://user-images.githubusercontent.com/19690477/55276618-19cfec00-52f6-11e9-9785-36d51cb17ed2.png)

> With Xiphos I don't see a title or verse 1. Verses 2 and on are displayed. (Same as BT)

My xiphos version shows all very well(4.1.0) download from Ubuntu Disco.

>I believe it is likely that your Psalms module has incorrect markup.

This is the question... Why BT on Android shows it well and xiphos too, but not BT on desktop? I spoke about this with @DavidHaslam, the tag seems my to be ok. But really I will not pretend it. Maybe he will come and give an advice. Maybe you have an idea how to write it?
My diatheke result:
```
diatheke -b ItPs -k Psalms 3:1-5
Psalms 3:1: Salmo di Davide quando fuggiva il figlio Assalonne.
Psalms 3:2: Signore, quanti sono i miei oppressori!<l eID="gen50" level="1"/> <l level="1" sID="gen51"/>Molti contro di me insorgono. <l eID="gen51" level="1"/>
Psalms 3:3: Molti di me vanno dicendo:<l eID="gen52" level="1"/> <l level="1" sID="gen53"/>«Neppure Dio lo salva!». <l eID="gen53" level="1"/>
Psalms 3:4: Ma tu, Signore, sei mia difesa,<l eID="gen54" level="1"/> <l level="1" sID="gen55"/>tu sei mia gloria e sollevi il mio capo. <l eID="gen55" level="1"/>
Psalms 3:5: Al Signore innalzo la mia voce<l eID="gen56" level="1"/> <l level="1" sID="gen57"/>e mi risponde dal suo monte santo. <l eID="gen57" level="1"/>
(ItPs)
```

**Comment by gholmlund** [comment]
In your previous comment, the HTML tags are missing. Probably the github bug software is doing this. In my output the Psalm 3:1 text starting with "Salmo" is inside of title HTML tags, which is not right. Do you see this also? 

Note: I see the same missing Ps 3:1 in BT Mobile as I see in BT.

**Comment by LAfricain** [comment]
> In my output the Psalm 3:1 text starting with "Salmo" is inside of title HTML tags, which is not right. Do you see this also?

No, I have the output as I send it to you. I don't know if it is correct.

> Note: I see the same missing Ps 3:1 in BT Mobile as I see in BT.

This bug is really mysterious :) In BT mobile all displays very well!!

> To use the ps.osis.xml you sent I am using osis2mod with no extra options.

I use it with the Catholic option but I'm not sure it will do a difference.

**Comment by LAfricain** [comment]
Ok I found the solution!!!
I choose a custom css it seems to be the reason why I had this different result! Thanks for help.

**Comment by LAfricain** [comment]
No it's not that??? If I use only the osis file with Psalm it is ok, but if I use all the bible osis file the problem remains... This explain with only the psalm file you could read it. Maybe I have an other place with an error. I will look.

**Comment by LAfricain** [comment]
I change the osis structure, and even if I have the break after the verse 1, BT can display the Psalms. Let us consider it is a problem with the osis structure.
