### ISSUE TITLE
Errors when compiling on Ubuntu 18.04

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#180]
I would like to compile the last version. But when I try I have this error:
```
Could NOT find Sword: Found unsuitable version "", but required is at least
  "1.7.0" (found )
```
I installed the 1.8.1 sword version from the Ubuntu disco repository.
An other strange thing, currently my compiled version is 2.11.2 but when I try to compile the last sources, cloned from github It says:
```
-- Setting up build environment for BibleTime version 2.11.0_rc1+79804f2375336badf56a759278ff2d56871ed46c
```
2.11.0???

**Comment by gholmlund** [comment]
I see you are trying to compile the master branch which is not released. The version has not been established for it yet. This is as expected.
I believe that the sword version required needs to be changed to 1.8.1. I will look into this.

**Comment by gholmlund** [comment]
BibleTime now requires sword 1.8.1.
