### ISSUE TITLE
Internal links and Strong  link in dictionnaries not working

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#182]
In the greek-italian module (not yet upload but you can find it [here](https://gitlab.com/crosswire-bible-society/dizionario-greco-italiano)), I add internal links to words and to external links to strong's number. But in Bibletime the links don't works. In Xiphos it works very well

**Comment by gholmlund** [comment]
Just to be clear, are you asking for the internal links to show in the MAG windows or to change the location of the module in the text window?

**Comment by LAfricain** [comment]
Both if possible :) Maybe when we pass with the mouse on the link it is shown in the mag, but when we click on a word with an internal link it will jump to this word in the same windows.
Thanks!

**Comment by gholmlund** [comment]
This is a TEI type module. A TEI  document supports OSIS reference using the "osisRef" attribute and non-osis references using the "target" attribute. BibleTime does not currently support the "target' attribute.  This is why some items that should render as links are not doing so.
Note: See backend/filters/teitohtml.cpp

Reference: https://wiki.crosswire.org/TEI_Dictionaries#OSIS_References

**Comment by LAfricain** [comment]
Ok and do you think to add the support for target attribute? If I change to osisRef for Strong links, It works on BT, but it crashes with Xiphos. And for the internal link. It doesn't work.

**Comment by gholmlund** [comment]
I am working on it. There are multiple issues to fix.

**Comment by LAfricain** [comment]
Ok perfect!

**Comment by gholmlund** [comment]
I am looking at the 4th entry in the module you provided. It is the entry that also has a Strong 838 reference.  Just after "da" is the reference  αὐξάνω 

The source for this reference is: "ref target= αὐξάνω". Is this expected to be an internal reference?
This target is not a reference to any location in this module. 

I am having difficulty finding any target reference that points to a valid internal key in this module.

**Comment by LAfricain** [comment]
It's strange, when I copy/stick your `αὐξάνω` I find nothing in the dic. But the word exists. If I copy `αὐξάνω` directly from the dic I find the entry lines 21148, but not the 4th (the 4th is Ἀβαδδὼν).
It's really possible that some internal link don't have a real entry. I add the link when the text said "See to..." or "from" but the major of it have.
If you need examples of good target ref:
`βάρος` `βάσις`, `ἕβδομος`...

**Comment by gholmlund** [comment]
I believe your Strong's numbers are incorrectly specified. In the Crosswire wiki  I see the Osis Strong's documented as:                 strong:H0853             (G for Greek, H for Hebrew)
Your references are like:    StrongsGreek:828

I cannot find "StrongsGreek" on the Crosswire wiki. I also note that using your module with Xiphos I see that the Strongs numbers don't work. 

Notes:
https://wiki.crosswire.org/OSIS_Bibles#Marking_lemmas_.26_morphology

**Comment by LAfricain** [comment]
> I also note that using your module with Xiphos

Yes you are right, I proposed the release with strongs numbers. It works, but the xml validation failed, then I tried to found the why. I thought to find it. I push the new version, but I did check the link in Xiphos!! And now it doesn't work anymore!! I will have a look to it.
For the strongsGreek you are right, it is not as proposed in the crosswire wiki, but other think proposed in the wiki in fact doesn't works as xr which is not accepted by the xml validation.
However, i saw this way to write it, but now I don't remember where :(
If you want to work on this maybe use an other dic till I solved this problem in mine.

**Comment by gholmlund** [comment]
I am testing with your latest module. I see the Strongs still  uses "target" instead of the osis tags. This should be changed. 
           ref target="StrongsGreek:839"
For the internal references I am about to push a change to master which is an enhancement to support "target" for these references. However, I still don't see any references that point to any of the keys the module provides.

**Comment by LAfricain** [comment]
Even with this words: βάρος βάσις, ἕβδομος?
It work for me in XIphos. For strong how to you want I change it? It runs in Xiphos ;)

**Comment by gholmlund** [comment]
I had two problems with the  TEI '"target" Strongs. I had not found the documentation for it. I have found it now. Also, it did not work on Xiphos for me. It turns out that I am using StrongsRealGreek which BibleTime is happy with, but the TEI reference to StrongsGreek. Once I have this, and use Xiphos it does work. I have checked in a fix needed for this to work in BibleTime.

I will look at the self references next.

**Comment by gholmlund** [comment]
For lexicons when a key is entered and it does not match any key in the module, sword can find the nearest match for this key and use it.
Entering the key βάρος both Xiphos and BibleTime do not find this key. They find ΒΆΡΟΣ. They show the following text:

**[*Dizionario greco-italiano*]
(baros)
probabilmente dalla stessa parola di βάσις (tramite la nozione di andata giù, vedi βάθος ) TDNT - 1: 553,95
Numero Strong: 922
sostantivo neutro
1) pesantezza, peso, carico, tribolazione
+ ἐν gravoso
acc. sing.
(+ ἐν ) autorità: 1 pesare: 4
uno pesare: 1
Totale: 6**
 
The text above has a link βάσις. I can hover over it and lookup the text for the link. In Xiphos I see this:

**Dizionario greco-italiano: βάσις
@LINK αὗται**

This looks a little strange. In BibleTime's MAG window I see only:

**βάθος**

I have debugged BibleTime and find that when it does not find an exact match, it only shows the requested key. It appears that Xiphos is showing something from a non-exact match.

I have yet to find any links in your module that match any keys of the module. This includes your example key βάρος and using Xiphos and BibleTime.

**Comment by LAfricain** [comment]
Is this fix in the master branch?
I pulled the master branch, compile it, but the strong's links don't work anymore.

**Comment by gholmlund** [comment]
The fix I made is in the master branch. 
The fix was necessary, but did not fix the problem. As I describe above(May 21), I got the same results with Xiphos and BibleTime. I believe that there is still an issue in your module.

**Comment by LAfricain** [comment]
> The fix was necessary, but did not fix the problem.

Okay thank you for the explanation.

>I got the same results with Xiphos and BibleTime.

Not me. When I use my module (not the current in the crosswire server) it's working  well Xiphos with: ` <ref target="StrongsGreek:0002">2</ref>`.

>there is still an issue in your module

Okay do you have an idea how to correct it?

Thank you for help!

**Comment by gholmlund** [comment]
So, your issue is about hovering over the "2" in  "Numero Strong: 2"? This works fine for me in BibleTime. I was testing things like "βάθος" which don't show anything except "βάθος" in the MAG window.
I am  using your getlab module.

**Comment by LAfricain** [comment]
> So, your issue is about hovering over the "2" in "Numero Strong: 2"?

Yes the strong numbers don't work for me. I have no links shown, it's normal text.
>I was testing things like "βάθος"

Where exactly?

**Comment by gholmlund** [comment]
I was testing things like "βάθος"
    | Where exactly?
You can see this in the example above (May 21) at the 3rd line.


    | Yes the strong numbers don't work for me. I have no links shown, it's normal text.
My strong numbers are blue indicating links. If you don't see this something is wrong with your build process. Make sure you are doing all of the following steps.

git branch     (verify you are on the master branch)
git pull 
git log           (The latest entry is on Oct. 1st
cmake ../bibletime
make clean
make
make install
 When you run BibleTime, the window title will display a git commit string that should match the Oct. 1st string from "git log".

**Comment by LAfricain** [comment]
Now it's ok! The strong numbers work. Thank you for help!
