### ISSUE TITLE
Support Dark Mode on MacOS

### ISSUE THREAD

**Issue by gholmlund** [bibletime/bibletime#183]
MacOS 10.14 supports a new "Dark Mode". Qt 5.12.x now supports this dark mode by automatically switching widget colors. However, BT has a combination of issues affecting color. Text that is rendered  using html (or rich text) specifies it own colors. Text windows, Mag windows, text preview in config dialog, and most of the About dialog show black text on white background even when menus, bookshelfs, etc. are white text on black background when in dark mode. For now the BibleTime app has been forced to only use light mode.
I investigated supporting dark mode. Just switching black/white colors when rendering text fixes much of the issue. The remaining issue relates to other colors in our display-template files such as Jesus words, cross references, etc. We need a different set of these for light vs dark mode. Perhaps a color map file that works with the display-template files would allow users to specify these colors.

**Comment by JJRcop** [comment]
Including a Dark.css as an included shipped display-template could fix this, but maybe not in the way that @gholmlund wants.

Applying a color inversion to the current display-template could also fix this but then it's not a designed experience for dark mode.
