### ISSUE TITLE
Program Fonts in 2.11.1 Are Too Small

### ISSUE THREAD

**Issue by rbeltz48** [bibletime/bibletime#184]
I am running BibleTime 2.11.1 in Linux Mint. 19. The fonts which are built into the program on the top panel and the Bookshelf names are extremely small. Previous BibleTime versions are much easier on the eyes. Changing the Bible text font has no bearing on the program or Bookshelf fonts. I know this is an older version of BibleTime but that is all that is available in the Linux Mint 19 repository. Is there a fix for this? Thanks.

**Comment by gholmlund** [comment]
BibleTime does not have any control that affects text for menus and other widgets. The Qt library that we use chooses a default font from the operating system. By setting an environment variable it is possible to scale the entire BT ui. From a terminal enter "export QT_SCALE_FACTOR=1.25 and then run BT from that terminal. You can experiment with the factor. If you run BT from a terminal, this only affects Qt programs ran from the same terminal. You could set this factor globally, but then it may change the size of other Qt programs. I hope this helps.

**Comment by gholmlund** [comment]
Do you have a high res (4K) monitor?

**Comment by rbeltz48** [comment]
My Lenovo Thinkpad display is 1440X900. 
        
      
    On 05/16/2019 03:50 PM, gholmlund
      wrote:
    
    
      Do you have a high res (4K) monitor?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      [
{
"@context": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMX3Y4N6YQ2QQDIYCMWTPVW3KHA5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS4E6A#issuecomment-493208184">"https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMX3Y4N6YQ2QQDIYCMWTPVW3KHA5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS4E6A#issuecomment-493208184"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMX3Y4N6YQ2QQDIYCMWTPVW3KHA5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS4E6A#issuecomment-493208184">"https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMX3Y4N6YQ2QQDIYCMWTPVW3KHA5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS4E6A#issuecomment-493208184"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]

**Comment by rbeltz48** [comment]
To: gholmlund,
          BibleTime Staff
          
          Than you for your response. The default fonts chosen by the
        Qt library seems to have a problem with
          choosing a readable font that both
          young and old alike can easily read. I am now 70
        yrs. old and have been using Linux since 2006, and BibleTime for
        about the past 10 years. I have never had a problem with any BT
        fonts until now with Ver. 2.11.1. Previous BT versions worked
        fine and fonts were easy on the eyes. 
        
        I have used many different types of PCs in the past 37 years. I spent
          more than 20 years in the computer field as a
          Programmer/Analyst, consultant and business entrepreneur. I have worked in more than 30 different companies and
            industries in 6 different U.S. states, in addition to owning two successful businesses. 
          
          From one professional to another,
            it would have been much easier if you would have simply told
            me to run Qt5ct and configure the fonts to my liking, which I have done. I also had the
              same problem with another Bible program running under Wine
              and ran the utility winecfg to change the graphics setting and obtain a larger menu font.
              
              Previous BT fonts: 
                General - Noto Sans 9
                Fixed Width - Monospace 10. 
                
                I changed them both to size 12 fonts and I am a happy
                    camper. Please close this thread. Thanks again.
                    
                    Sincerely,
                      Rick Beltz
          I.T Professional, Ret.  
        
        ___________________________________
      
    On 05/16/2019 03:45 PM, gholmlund
        wrote:
    
    
      BibleTime does not have any control that affects text for menus
        and other widgets. The Qt library that we use chooses a default
        font from the operating system. By setting an environment
        variable it is possible to scale the entire BT ui. From a
        terminal enter "export QT_SCALE_FACTOR=1.25 and then run BT from
        that terminal. You can experiment with the factor. If you run BT
        from a terminal, this only affects Qt programs ran from the same
        terminal. You could set this factor globally, but then it may
        change the size of other Qt programs. I hope this helps.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view

          it on GitHub, or mute

          the thread.
      [
{
"@context": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMXZ6NAKWMJWHVUMSJX3PVW2V3A5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS3XOY#issuecomment-493206459">"https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMXZ6NAKWMJWHVUMSJX3PVW2V3A5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS3XOY#issuecomment-493206459"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMXZ6NAKWMJWHVUMSJX3PVW2V3A5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS3XOY#issuecomment-493206459">"https://github.com/bibletime/bibletime/issues/184?email_source=notifications\u0026email_token=AECVMXZ6NAKWMJWHVUMSJX3PVW2V3A5CNFSM4HNG326KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVS3XOY#issuecomment-493206459"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]
