### ISSUE TITLE
Bad display of hebrew lemmata (Strong's Bible Dictionary v2)

### ISSUE THREAD

**Issue by Perticus** [bibletime/bibletime#185]
Wether in Mag or new window. Not all the lemmata are affected.

For example, hovering over Psalm 81:3
- Ugly: 05375 H5375 × ×¡×” × ×©×‚× nÃ¢ÏŽÃ¢' nÃ¢sÃ¢h naw-saw' naw-saw'
- Correct: 02172 H2172 זמרה zimrâh zim-raw' 

I am a new user, and not a developper. Is there an explanation? Can I help?

**Comment by gholmlund** [comment]
I see the same bad results using both BibleTime and Xiphos. This is a problem with the StrongsHebrew version 2.0 (beta). I would report it to Crosswire. 
http://tracker.crosswire.org/secure/Dashboard.jspa (Choose Modules section)
