### ISSUE TITLE
Bibletime crashes after opening

### ISSUE THREAD

**Issue by dabeegmon** [bibletime/bibletime#187]
Just updated by system from Debian 10 to 11 (may have some bearing on the issue). (Running LXQT 0.14 on Nouveau)
Due to a power outage I had to shut down my system (usually have very long uptimes) earlier this week (was a clean shut down but done in a hurry so I hadn't shut Bibletime down prior to system shut down). 

When I open bibletime the normal box appears. If I try to expand the box across both monitors (previously possible) bibletime crashes. If I leave the box as is and try to open a text bibletime crashes. 
Have been reading through system logs and am not finding anything directly related.
Any ideas as to what could be wrong?

**Comment by gholmlund** [comment]
My first guess would be the settings file was corrupted. BibleTime state is saved in it. I would move or rename $HOME/.bibletime/bibletimerc. and try again. If this does not fix the issue you can move/rename the file back and you have not lost the settings.

**Comment by gholmlund** [comment]
Another thought. If BibleTime was not installed as a package (which would update) it could crash if not reinstalled. If you originally built it from source, you will need to do this again.

**Comment by dabeegmon** [comment]
On Wed, Jul 17, 2019 at 5:20 PM gholmlund <notifications@github.com> wrote:

> Another thought. If BibleTime was not installed as a package (which would
> update) it could crash if not reinstalled. If you originally built it from
> source, you will need to do this again.
>
If only I could remember which method I used - - - do know I have run into
times when Debian packages of the 'current' version were not very current
and so I installed from source, which was quite an odyssey.

So if I had installed from source would the only way to change to a package
be to delete the whole works and start over?

Regards

>
>

**Comment by gholmlund** [comment]
I don't believe you need to delete the previous version. The newly compiled version would just copy onto it. Don't do anything to the $HOME/.bibletime and $HOME/.sword directories.

If you built it from source the default location would be to put it into /usr/local/bin/bibletime, etc. If is were a package it would be in /usr/bin/bibletime. 

type:     which bibletime
Display the path to bibletime.

**Comment by dabeegmon** [comment]
On Wed, Jul 17, 2019 at 6:00 PM gholmlund <notifications@github.com> wrote:

> I don't believe you need to delete the previous version. The newly
> compiled version would just copy onto it. Don't do anything to the
> $HOME/.bibletime and $HOME/.sword directories.
>
> If you built it from source the default location would be to put it into
> /usr/local/bin/bibletime, etc. If is were a package it would be in
> /usr/bin/bibletime.
>
> type: which bibletime
> Display the path to bibletime.
>
Thank you - - - looks like I installed from a package.

**Comment by gholmlund** [comment]
Perhaps the upgrade did not go right. I would remove the bibletime package and reinstall it.

**Comment by dabeegmon** [comment]
I had for far too long many other things that took precedence. Today I thought I would try to see if I could get bibletime going again. 
Now running on a debian 11 (testing or bullseye) system fully up to date. Physical hardware is down to one graphics card and therefore only 2 monitors in use set up to be one virtual screen of 3840 by 1080 (was previously running 4 monitors with a virtual screen of 3840 horizontal and 3000 vertical pixels). 
I checked and yes there had been a recommendation to reinstall bibletime so I did the # apt install --reinstall bibletime. Seemed to install successfully. 
So opened an instance of bibletime and asked for one text to open in the window. Then I tried to expand the window to larger than one physical monitor (I got to about a 3400 pixel wide window). At that point I had a totally unresponsive desktop. Moved to another system and used ssh to log into my main system and used $ killall bibletime to kill the offending process. I am not sure if what I'm finding in the kernel log would be helpful. I'm thinking that with the way this bibletime/qt combination is working on my system that I just need to uninstall bibletime - - - its seems to have become unusable - - - - which I really don't want to do!

**Comment by jaakristioja** [comment]
Sadly we don't have the resources to support every user setup, including pre-release versions of Linux distros. This also seems more of a Qt or system issue, and not directly a result of a some bug in BibleTime.

I'm closing this to keep the BibleTime GitHub issues list more clean. Please reopen if this still turns out to be a bug in our code.
