### ISSUE TITLE
How to uninstall in linux? 

### ISSUE THREAD

**Issue by flamendless** [bibletime/bibletime#188]
How to uninstall in linux, mainly arch - based distro? 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gholmlund** [comment]
This is really an operating system question. If you installed it with pacman, this will remove it.
pacman --remove bibletime

You can also remove $HOME/.sword and $HOME/.bibletime

**Comment by flamendless** [comment]
Yeah I've tried with my package manager but it wasnt installed with package manager. I guess im gonna delete them manually
