### ISSUE TITLE
[Feature request] Import TheWord modules

### ISSUE THREAD

**Issue by bryce-lynch** [bibletime/bibletime#190]
Bibletime is the only native, full-featured Bible study program available for free on Linux. While there are many modules one can choose from, there are way more available for TheWord (for windows and wine), commentaries in particular.

I've already tried a few conversion tools (e.g. biblemulticonverter) but since nothing seems to work, I thought I'd ask here. Can we have an import function in a future release?

**Comment by gholmlund** [comment]
All of our documents are in Sword format which is supported by the CrossWire Bible Society (crosswire.org). They are the people that import various documents into the Sword format. I would suggest talking with them about this. Any of these documents must be either licensed for this use, or out of copyright. Here is their mailing list:
http://www.crosswire.org/mailman/listinfo/sword-devel
