### ISSUE TITLE
Bible Books

### ISSUE THREAD

**Issue by SFC2033** [bibletime/bibletime#191]
When I put mouse on down arrow that is titled select book only old testament books are listed.  In order to get to the new testament I have to go next to the book titled next book and click until I see the new testament book that I want to get to.  Any help would be greatly appreciated

**Comment by gholmlund** [comment]
When the list of books reaches the bottom of the computer screen, it should wrap around and start a second column of books to the right of the first column. This works for me on all of the versions that I can test. 
Can you tell us more about your setup:
   Operating system and version
   Qt version
   How was BibleTime installed. Repository or built from source?

**Comment by SFC2033** [comment]
Wow thanks for getting back to me.
5.1.18-300.fc30.x86_64
Fedora 30
Installed through dnf RPM Fusion Repository

Check the screenshot out.  I just pulled up the list and only the old
testament is seen.  But if I put my mouse where the new testament is it is
blank.  Just a blue bar.  But if I click it pulls up a new testament book.
Thanks again

**Comment by gholmlund** [comment]
I am trying to reproduce this with Fedora 30 and BibleTime 2.11.2  installed with dnf. It works correctly for me. I don't know what else to try.

**Comment by SFC2033** [comment]
Maybe it has to do with that I upgraded to fc 30 through and instead of a
clean install

**Comment by gholmlund** [comment]
Yes. Perhaps removing and reinstalling BibleTime will help.

**Comment by historical-theology** [comment]
@SFC2033 , pardon the late contribution to this discussion, but I would also note that Bibletime does not have a way to switch between different translations/editions automatically. For example, if I am browsing the Septuagint but need to check something in the SBL Greek NT, then I must manually switch from one to the other. 

If a particular translation/edition does not have a certain book, then that book will (of course) not show.

**Comment by jaakristioja** [comment]
Please reopen if the original issue still persists.
