### ISSUE TITLE
Source links in the "about" module are not well displayed

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#193]
Just see the picture:
![about](https://user-images.githubusercontent.com/19690477/66177195-85d93700-e62e-11e9-88a5-3d6ff729d09d.png)
You see in front of  Text source, you have: ...https://gitlab.com/crosswire-bible-society/nomidellabibbia">Nomi della Bibbia... Not well displayed as a like like that:  <a href="https://gitlab.com/crosswire-bible-society/nomidellabibbia">Nomi della Bibbia</a>

**Comment by gholmlund** [comment]
Crosswire indicates the TextSource field is: "Indicates, either in prose (such as "CCEL") or as a URL of the source of the text". A url does not include tagged html text.

**Comment by LAfricain** [comment]
Ah ok good to know I will change this  in the files.
