### ISSUE TITLE
Possible issue with source formatting

### ISSUE THREAD

**Issue by skyblue002** [bibletime/bibletime#195]
I'm not sure if this is an issue or not.

I have sources set to show line numbers and to have line breaks after each verse, like so:
![BibleTime screenshot showing line breaks and line numbers](https://user-images.githubusercontent.com/41849249/66277946-b1e4fa00-e872-11e9-8f38-3e15aa9ccb15.png)

After setting everything up like that, if I open another source (e.g. another version of the Bible or even just another verse in the same Bible), the settings revert to not showing line numbers and not having line breaks after each verse:
![BibleTime screenshot after formatting reverts](https://user-images.githubusercontent.com/41849249/66277970-f96b8600-e872-11e9-9fd2-63ad14fd6f91.png)
(Note: To open up this passage, I double-clicked on a bookmark I had made.)

When studying, having to go back and check "show verse numbers" and "use linebreaks after each verse" over and over again becomes very time-consuming. That said, I am not sure if this is how the app was made to behave or if this is an issue.

If it is an issue, just let me know what information you need to troubleshoot and fix the problem. I'd be happy to help.

If it isn't an issue, may I please suggest a feature be added to specify user-chosen defaults for every time a new source is opened?

Until that time, would it be possible for me to change the source such that those settings are specified after compiling? I could always compile a custom version for the time being. I would just need to know which files to edit, as I'm sure that BibleTime, being such a feature-rich program, has very many source files.

Thank you!

**Comment by gholmlund** [comment]
When BibleTime opens a new window it uses default settings for these options. You can set the default values for these in the Settings dialog. Select "Desk" and then "Text Filters". You should see the defaults there.

**Comment by skyblue002** [comment]
Thank you very much, @gholmlund ! I greatly appreciate it. I'm very thankful this option already exists, and thank you for letting me know about it. :)
