### ISSUE TITLE
How to disable autoscroll

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#197]
The autoscroll is very difficult to use in particular in the Daily devotion. Is it possible to disable it?
The auto scroll it like stuck on one place and it's not possible to move in the place you wish to go.
If you want to make test I use the freCallit module from crosswire.

**Comment by gholmlund** [comment]
Can you explain in more detail what the issue is for you?

**Comment by LAfricain** [comment]
The scroll is working intermittently. Some times the autoscroll function doesn't disable, preventing me from clicking hyperlink.

**Comment by gholmlund** [comment]
Autoscroll turns on if you type "Shift/Up" or "Shift/Down". To pause it type the spacebar. To stop it hit any other key.
Is it not working this way for you?

**Comment by LAfricain** [comment]
No... the cursor seems to be "stick" on the text. It's difficult to explain!! I think we need an option to disable completly the autoscroll. I have the same problem with fredaw module.

**Comment by gholmlund** [comment]
I have updated the snap. 

Auto scrolling is started by Shift - Down Arrow or Shift - Up Arrow
It is paused by the spacebar
It is stopped by 
  1. hitting any other key
  2. Selecting another BibleTime text window
  3. Change the reference using the menu bar controls
  4. Use the mouse wheel (new)
  5. Use the scroll bar. (new)

**Comment by gholmlund** [comment]
I will look further at copy/paste after this defect is done.
BibleTime does not do dictionary lookup at this time.

**Comment by LAfricain** [comment]
> I will look further at copy/paste after this defect is done.

Ok thanks

> BibleTime does not do dictionary lookup at this time.

Ok then I will open a new issue with feature request.

**Comment by LAfricain** [comment]
Congratulations! It's working :)
A work around for the copy/past: select the entry, it's shown in the Mag windows, then copy what you want... But the copy by click right doesn't still work.

Suggestion: is it possible to propose a ppa with new versions of Bibletime. Snap is ok, but we have all in double. Or if you propose me an archive with all the source and debian folder I can push it on my [ppa](https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac) where is already sword-1.8 and Xiphos. Or I can open a new just for the crosswire tools.

**Comment by gholmlund** [comment]
I have used snap for testing defects because one build will run on many different os versions. A snap can also be installed without over writing your original BibleTime.

A ppa must be build for each os version. When we have the next BibleTime stable release we might consider a ppa.

**Comment by LAfricain** [comment]
> A ppa must be build for each os version.

Oh yes you are right!

> When we have the next BibleTime stable release we might consider a ppa.

Good news ;)
