### ISSUE TITLE
Ref links in Frecallit can't be opened in the bible module

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#198]
I would like to open the biblical refs in the frecallit module directly in the Bible module, like before. Now it shown in the mag but I can't open it in the bible. Any idea?

**Comment by gholmlund** [comment]
Have a second Bible window open. Drag the reference into the Bible window.

**Comment by LAfricain** [comment]
> Drag the reference into the Bible window.

This feature is really cool! Just to know it!
