### ISSUE TITLE
Bibletime 2.11.+ very unstable on Debian 9+

### ISSUE THREAD

**Issue by troypulk** [bibletime/bibletime#199]
I have been dealing with this for a long time and my thought is I'll wait for it to get fixed.

So in the mean time I'll downgrade to the last working version 2.10.2.

So when I'm trying to build it in Debian 11 testing qt5 files are missing, will qt4 work?

I remember reading some where around here that it's a qt5 issue, is this still the case, what's the status of this now?

So I ended up using my laptop and installing a Distro that has a working version (2.10.2) but that's inconvenient since the laptop is not my daily driver.

Is this a Debian thing and I will need to wait for them or is this a Bibletime thing?

Thanks

**Comment by gholmlund** [comment]
BibleTime 2.11.1 was not compatible with Qt 5.11. BibleTime 2.11.2 worked around this problem.

BibleTime 2.10.x will work with Qt4 or Qt5. You will have to set cmake variable BT_FORCE_USE_QT4 to 1 to prevent automatic use of Qt5. 
BibleTime 2.11.x requires Qt 5.9 or later.

**Comment by troypulk** [comment]
Thanks,
Why is 2.11.+ so unstable? I have:

```
solydx:~$ inxi -SGMCm
System:    Host: solydx Kernel: 5.2.0-3-amd64 x86_64 bits: 64 Desktop: Xfce 4.14.1 
           Distro: solydxk-11 11 
Machine:   Type: Desktop Mobo: MSI model: 890GXM-G65 (MS-7642) v: 1.0 serial: <root required> 
           BIOS: American Megatrends v: 1.8 date: 12/24/2010 
Memory:    RAM: total: 7.30 GiB used: 5.69 GiB (78.0%) 
           RAM Report: permissions: Unable to run dmidecode. Root privileges required. 
CPU:       Topology: Dual Core model: AMD Phenom II X2 555 bits: 64 type: MCP L2 cache: 1024 KiB 
           Speed: 3200 MHz min/max: 800/3200 MHz Core speeds (MHz): 1: 3200 2: 3200 
Graphics:  Device-1: AMD RS880 [Radeon HD 4290] driver: radeon v: kernel 
           Display: x11 server: X.Org 1.20.4 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD RS880 (DRM 2.50.0 / 5.2.0-3-amd64 LLVM 9.0.0) v: 3.3 Mesa 19.2.1
```
The last version that worked with out any issues was 2.10.1.

Most the issues are GUI, clicking inside the reading view makes it freeze and it does't highlight the verse when clicked which makes selecting a new bible version freeze as well. Scrolling is also very slow.

**Comment by gholmlund** [comment]
I am not aware of problems like you describe with BibleTime 2.11.2.
I am writing this from Debian 10 where I have ran BibleTime 2.11.2 which came from the Debian repository. It is running fine for me.

**Comment by troypulk** [comment]
The version 2.11.2 I have also comes from the Debian repository.

I'll reinstall with a brand new install on my laptop to see if something else is causing it, RAM or something I'll look around.

**Comment by troypulk** [comment]
> BibleTime 2.11.1 was not compatible with Qt 5.11. BibleTime 2.11.2 worked around this problem.
> 
> BibleTime 2.10.x will work with Qt4 or Qt5. You will have to set cmake variable BT_FORCE_USE_QT4 to 1 to prevent automatic use of Qt5.
> BibleTime 2.11.x requires Qt 5.9 or later.

When building v2.11.2 in Debian 11 testing it says it's missing "Qt5LinguistTools" it's not listed in the repository.

Do you know which repo it appears?

Thanks

**Comment by gholmlund** [comment]
qttools5-dev-tools in the debian repository.

**Comment by troypulk** [comment]
Thanks,

how do you set BT_FORCE_USE_QT4 to 1

**Comment by gholmlund** [comment]
add this option to the cmake command:
-D BT_FORCE_USE_QT4=1

If you are using the build-release script you will have to edit it where the cmake command is.

**Comment by troypulk** [comment]
Thanks,
The line is:
IF(NOT BT_FORCE_USE_QT4)
  # Automatically use Qt5 if available
  FIND_PACKAGE(Qt5Core QUIET)
ENDIF()

So you put the 1 after QT4?

I rebuilt v2.11.2 from scratch and it works normal, now I'll try it on my main driver along with 2.10.1.

Thanks

**Comment by gholmlund** [comment]
> So you put the 1 after QT4?
If you run cmake directly add -D BT_FORCE_USE_QT4-1 to the cmake command.
If you build using the build_release file, edit that file on the cmake line.

**Comment by troypulk** [comment]
Thanks,

I rebuilt v2.11.2 from scratch on my main PC and it works normal with no lagging or need to restart.

I ran it in console and got this read out, is it normal?
```
@solydx:~/bibletime-2.11.2$ /usr/local/bin/bibletime
Error reading ulBuffNum
Error reading ulBuffNum
Error reading ulBuffNum
Error reading ulBuffNum
(BibleTime 2.11.2) WARNING: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16420, resource id: 8492789, major code: 40 (TranslateCoords), minor code: 0
(BibleTime 2.11.2) WARNING: QXcbConnection: XCB error: 3 (BadWindow), sequence: 16928, resource id: 8493031, major code: 40 (TranslateCoords), minor code: 0
```
I think the reason it was buggy and lagging before is because either Debian or my distro some how influenced the install, I didn't change anything just added the building files.

It works now so thank you for your help.

**Comment by gholmlund** [comment]
The ulBuffNum error comes from the sword library. I probably indicates a format error in some module.
The XCB error is from the Qt library.
I have frequently seen both errors and they are in libraries outside of BibleTime.

**Comment by gholmlund** [comment]
Since it is working for you, I am closing this.

**Comment by troypulk** [comment]
Okay, Thank you.

On 2019-11-03 4:14 pm, gholmlund wrote:

> Since it is working for you, I am closing this. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/bibletime/bibletime/issues/199?email_source=notifications&amp;email_token=AGLUNNF3LAL7QCV35MQ4YVDQR5LPFA5CNFSM4JCMDUXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC6AWSY#issuecomment-549194571
[2]
