### ISSUE TITLE
Fails to build from source on s390x on Debian

### ISSUE THREAD

**Issue by xnox** [bibletime/bibletime#20]
Could you please take a look at the following build log to see if there is a bug in bibletime and/or qt builds on s390x architecture:

https://buildd.debian.org/status/fetch.php?pkg=bibletime&arch=s390x&ver=2.10.1-1&stamp=1413951294

**Comment by jaakristioja** [comment]
Is this still an issue?

**Comment by xnox** [comment]
it is not, builds fine now.

**Comment by mgruner** [comment]
Thanks!
