### ISSUE TITLE
NET Bible not staying unlocked on start-up when loaded as a parallel passage

### ISSUE THREAD

**Issue by tpenguinltg** [bibletime/bibletime#201]
When the NET Bible is loaded as a parallel passage on start-up, the text shows and I can freely navigate the module. I can also add and remove the module in any of the windows that were already present on start-up. However, the module appears locked in the list in the sidebar, and attempting to unlock it fails (the code is autofilled, so it's still stored in the config file). When I create a new window by selecting another Bible, NET is not listed as an available option to add or replace. Interestingly, if the module is loaded in any window by itself on startup (i.e. not parallel), even if it is parallel in another window, the module remains unlocked. I assume this is the case for other unlockable bibles, but I only have NET.

This behaviour does not apply to the unlockable NETnotes commentary, which works as expected.

I'm using BibleTime v2.11.2 with Sword v1.8.1as distributed by [Arch Linux](https://www.archlinux.org/packages/community/x86_64/bibletime/).

**Comment by gholmlund** [comment]
I have reproduced this as described above. I happens with 2.11.2 and the master branch.

**Comment by gholmlund** [comment]
I am working to fully understand this problem. I seems to be a caching problem in the sword library. BibleTime code for unlocking has not changed, but with the latest sword (1.8.1) this problem occurs.

There is a simple work around. in $HOME/.sword/mods.d/net.conf, find the line "CipherKey=". Add the key immediately after the =.

**Comment by tpenguinltg** [comment]
> There is a simple work around. in $HOME/.sword/mods.d/net.conf, find the line "CipherKey=". Add the key immediately after the =.

This was actually one of the things I tried before making this issue. I still see the described behaviour.

**Comment by gholmlund** [comment]
I have fixed the stable-2.11 and master branches.

**Comment by tpenguinltg** [comment]
I can confirm this is fixed on `master`. Thanks!
