### ISSUE TITLE
Problem with locale bm or my

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#202]
BTdoesn't recognize the my-utf8.conf file proposed by sword for the locale of the book names. I need to change the file to bm-utf8.conf.
And in the bible text, the myanmar is not well display:
For **ဗျာဒိတ်တော်ကျမ်း** I have:
![Revelation](https://user-images.githubusercontent.com/19690477/68135602-f4413b80-fef1-11e9-8628-0fa229c0224c.png)
And for **ရှင်ယောဟန်ဩဝါ**, I have:
![john1](https://user-images.githubusercontent.com/19690477/68135766-323e5f80-fef2-11e9-8fbc-be7b90c9d9c7.png)

The two first letters are not well sticked together.

**Comment by LAfricain** [comment]
What kind of information?

**Comment by gholmlund** [comment]
I think this is a sword issue. BT does not directly handle these files. 
If it really is a BT issue I would need:
1. The file
2. Where you put the file
3. What you mean by "doesn't recognize"
4. The font and how the bible text was displayed. 
5. Any think else that would help reproduce these issues.

**Comment by LAfricain** [comment]
Copy the conf file (attached file) in /usr/share/sword/locales.d/ Open BT, in the language option, look for Burmese (my), nothing appears. Change the conf file from my to bm. the language appears in the list. What is expected: my should be recognized as locale for Burmese.
[my-utf8.zip](https://github.com/bibletime/bibletime/files/3822876/my-utf8.zip)

/

**Comment by gholmlund** [comment]
![image](https://user-images.githubusercontent.com/3507381/68501190-6bd4da80-0212-11ea-9dfc-c57a8f70c402.png)
The my-utf8.conf file works ok for me in both stable-2.11 and master branches.
