### ISSUE TITLE
Holding Shift does not lock the Mag viewer

### ISSUE THREAD

**Issue by tpenguinltg** [bibletime/bibletime#205]
The Mag viewer contents do not lock when holding Shift while moving over other items that have data.

**Steps to reproduce**

1. With a Strong's lexicon configured and a Bible with Strong's references loaded (e.g. ESV2011), hover over a word with a Strong's reference.
2. Hold the Shift key.
3. Hover over another word with a Strong's reference.
4. Observe that the contents of the Mag viewer changes.

The above also happens when the cursor is on the way and stops at Mag viewer while the Shift key is held: the viewer updates to the last thing with data that was hovered over along the way. Footnotes will also trigger this behaviour.

**Expected behaviour:** The contents of the Mag viewer should not change.

I am using a build from commit 637c02b with sword 1.8.1 and Qt 5.13.1 on Arch Linux.
The described behaviour does not occur and works as expected on BibleTime v2.11.2.

**Comment by gholmlund** [comment]
This was a regression from 2.11.2. It is fixed now.

**Comment by tpenguinltg** [comment]
A little late, but I can confirm that 77a77901 has indeed fixed this.
