### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#206]
The plan is to move towards a 3.0.0 release, starting with the release of 3.0.0_beta1 as soon as possible. Thanks to @gholmlund for compiling the following list of changes:

> Notable changes since 2.11.2:
> 
> Enhancements:
> 
> * Text windows now have continuous scrolling from the beginning to end of a module. At the end of a chapter just keep scrolling to see the next chapter.
> * You don't have to open the Personal Commentary for writing. Edit it in a normal text window or even when it is a parallel column in a text window.
> * Automatic text scrolling up or down with variable speed and pause.
> * Copy to clipboard by choosing the beginning and ending reference.
> * A search filter was added in the "Install Works" page of the Bookshelf Manager.
> * You can select text from a single column when using parallel texts in a window.
> * Added a user interface to delete or create search indices.
> * The first time the Bookshelf Manager is used in a session, the remote libraries are updated.
> 
> Bugs fixed:
> 
> * Locked Bible not unlocking properly
> * Place not being saved in Daily Devotional.
> * Problems with MAG window references using  hebrew modules OSHB and OSMHB
> * Unable to create a search scope for deuterocanonical books
> * Searching with quotes not working.
> * MAG windows Strongs references not working unless config settings were saved.
> 
> Build requirements:
> 
> * C++11 compiler
> * Qt 5.9 or later
> * Sword 1.8.1

Since this list is quite notable indeed, it was decided to bump our major version number, so the next release will be BibleTime 3.0.0 instead of 2.12

While we do have our [development cycle](https://github.com/bibletime/bibletime/wiki/Development-cycle) document, we don't usually follow it precisely. However, we can use it as a blueprint for the timeline of version 3.0. I suggest we do one beta and one RC before the final 3.0.0 release, hence I propose the following preliminary timeline:

* ASAP: [Feature freeze](https://github.com/bibletime/bibletime/wiki/Development-cycle#Feature-freeze), 3.0_beta1
* Week 2 (before Christmas): stable-3.0 [branch creation](https://github.com/bibletime/bibletime/wiki/Development-cycle#stable-branch-creation), [string freeze](https://github.com/bibletime/bibletime/wiki/Development-cycle#string-freeze) in the stable-3.0 branch, [switching Transifex](https://github.com/bibletime/bibletime/wiki/Development-cycle#switch-transifex-to-current-branch) to use the stable-3.0 branch (and notifying translators), releasing 3.0_rc1 from the stable-3.0 branch.
* Week 6 (around January 18): Release 3.0.0 final.

Does this seem reasonable?

I will try to finish [release procedures](https://github.com/bibletime/bibletime/wiki/Releasing-BibleTime) for 3.0_beta1 on Tuesday the latest.

**Comment by jaakristioja** [comment]
Given the short cycle, perhaps it would make more sense to push strings to Transifex and notify translators earlier?

**Comment by jaakristioja** [comment]
I renamed the 2.12.0 milestone to [3.0](https://github.com/bibletime/bibletime/milestone/7). It also has a number of unresolved issues we should handle. I've already postponed some of them, but what about the rest?

There also issues which have not been assigned to a milestone and these should be assigned some the appropriate milestone, including any which have already been resolved. I've also created new milestones for [3.0.1](https://github.com/bibletime/bibletime/milestone/12), [3.1.0](https://github.com/bibletime/bibletime/milestone/13) and [4.0.0](https://github.com/bibletime/bibletime/milestone/14).

**Comment by jaakristioja** [comment]
> Given the short cycle, perhaps it would make more sense to [push strings](https://github.com/bibletime/bibletime/wiki/Translation-Management#pushing-current-state-to-transifex) to Transifex and notify translators earlier?

After some thought, I will do just that, even though it goes against [documented procedures](https://github.com/bibletime/bibletime/wiki/Development-cycle). I will pull the current translations from Transifex into the stable-2.11 branch, and then push the strings from master to Transifex. I will also disable Transifex on the stable-2.11 branch and once a stable-3.0 branch will be created @ RC1, I will again disable Transifex for master. I will also write a short announcement about this on Transifex.

**Comment by jaakristioja** [comment]
[3.0 beta 1](https://github.com/bibletime/bibletime/releases/tag/v3.0_beta1) has been released.

**Comment by entodoays** [comment]
Running the snp gives me the following error:
`This application failed to start because it could not find or load the Qt platform plugin "wayland-egl" in "".
`

**Comment by jaakristioja** [comment]
@entodoays This issue is meant for discussing the 3.0 release process. For specific bugs, please file a [new issue](https://github.com/bibletime/bibletime/issues/new).

**Comment by jaakristioja** [comment]
[3.0 beta 2](https://github.com/bibletime/bibletime/releases/tag/v3.0_beta2) has been released. 

@gholmlund and I decided to do another beta instead of a RC because of new features. This will probably shift the next pre-release to around January 18, and 3.0 final to February or later.

**Comment by jaakristioja** [comment]
I plan to release 3.0 final before August 3. I don't think we need another RC.

**Comment by jaakristioja** [comment]
Tagged and release added to GitHub: https://github.com/bibletime/bibletime/releases/tag/v3.0

I will try do the rest of the procedures I've usually done after an hour or so.

**Comment by jaakristioja** [comment]
> I will try do the rest of the procedures I've usually done after an hour or so.

Done.

**Comment by jaakristioja** [comment]
I suppose we can close this. :-)
