### ISSUE TITLE
Unreadable text in about dialog with dark-colored system themes

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#208]
Happens with current master branch on KDE with dark color themes applied. 

![Screenshot_20191211_221227](https://user-images.githubusercontent.com/2684083/70656828-7a743e80-1c63-11ea-9469-dd62e2a21c25.png)

Related to #183.

**Comment by gholmlund** [comment]
Closing this bug because it is specific to the about dialog. 
It is related to #183 , but that is about the text window. Supporting text windows with a dark mode is doable, but might be to much to do during beta the phase.
