### ISSUE TITLE
Verse number drawn incorrectly with some display templates.

### ISSUE THREAD

**Issue by gholmlund** [bibletime/bibletime#209]
![image](https://user-images.githubusercontent.com/3507381/70767060-a8658b80-1d14-11ea-9164-9dd82354e01f.png)
Above is an example of the display of verse numbers with some of the display templates. You will see a partial drawing of the verse number which is offset from the complete drawing. This behaviour started about two weeks ago when this line was added to the display templates.
    * { background-color: #fff; color: #000; }
I don't blame this line, but if you comment it out the verse display works correctly. Clearly this is a Qt problem. I am using 5.12.6 and 5.13.2 and both show the problem. If you comment out the vertical-align of "entryname" the problem will also go away. The templates that work do not use vertical-align:super. As a work around we may have to do this for all templates.

I have created a tiny Qt program that demonstrates this problem and plan to submit a Qt defect.

**Comment by gholmlund** [comment]
https://bugreports.qt.io/browse/QTBUG-80759

**Comment by gholmlund** [comment]
@jaakristioja  When you added this line, what did it fix?
    * { background-color: #fff; color: #000; }
If I remove it, I have not seen any problem. 
If I change the "*" to "body", the double verse number problem stops. This seems like a reasonable workaround.

**Comment by gholmlund** [comment]
@jaakristioja   I believe I found what it fixed. Some cases of text in the MAG window.
Changing "*" to "body" works for those MAG cases and works around the double verse issue.

**Comment by jaakristioja** [comment]
@gholmlund See message of commit 0380b0963ed6bcec3678df24337b9dfa110462a9. The `*` selector means all elements. In theory this commit should only change the color, hence this is possibly a problem in the HTML display component were using. I'm not sure about BibleTime, but as far as I know at least in some web browsers `<html>` and `<body>` are different elements whereas their dimensions differ and their bounding rectangles (as well as the bounding rectangles of any other elements) might not contain each other and even intersect. A common case I've seen is that based on its contents the `<body>` element might only fill the upper half of `<html>`. Hence I opted for `* `.

Fortunately, it currently appears that commit e4355b2efff0b904c81d9c88093b24cec91d9c05 did not make things worse on my system. :-)
