### ISSUE TITLE
3.0 beta 1 snap package doesn't run

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#211]
When running the snap package mentioned in the title I get:

> This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Reinstalling the application may fix this problem.
> Aborted (core dumped)

**Comment by gholmlund** [comment]
Short story: Fixed
Long story: Snaps can only be built on Ubuntu 16.04 or 18.04. With 18.04 the Qt version is 5.9.5. I enabled the qt wayland plugin and did get BibleTime running. It does not look right and it crashes frequently. I found others on the internet with similar issues. They recommendation was to disable the qt wayland plugin and use qt x11 instead. An qt x11 app will run on wayland using xwayland. I did this and tested on ubuntu 19.10. It seems to run very well now.

I uploaded a new snap. The name change a little. See the release notes.
