### ISSUE TITLE
Update copyrights for 2020

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#215]
The copyright notices in source code headers and such need to be updated for 2020.

Although, I'm not sure whether the year(s) in the copyright notices is needed at all. Perhaps only for the U.S?

**Comment by jaakristioja** [comment]
Ran `make fix_cpp_headers` in commit 0cfe7ade586072b5eac0cd12a77681112dbea93c, but changes might be required elsewhere as well.

**Comment by gholmlund** [comment]
I did a search for other copyright places. I found and fixed 1 place.

**Comment by jaakristioja** [comment]
Thanks, @gholmlund! Closing.
