### ISSUE TITLE
Nothing is available for download from Crossway

### ISSUE THREAD

**Issue by cscj001** [bibletime/bibletime#219]
I use BibleTime on Ubuntu 18.04 x64.  The BibleTime version is 2.11.1.  I have wanted an ESV Bible for quite a while.  I have one from Crossway on my Android phone.  BibleTime lists Crossway as a source for Bibles, Commentaries, et al, but when I try to see what is available there, nothing shows.  Is this a Crossway issue, a BibleTime issue, or a Ubuntu issue?  Depending on who owns this issue, do you have any contact for that development group?  Thank you.

**Comment by gholmlund** [comment]
Crossway asked Crosswire to remove the ESV Bible from their repository.
http://www.crosswire.org/pipermail/sword-devel/2019-June/047095.html
