### ISSUE TITLE
How to install local resources

### ISSUE THREAD

**Issue by HinzundKunz** [bibletime/bibletime#221]
Hello,
I have a few local resources (.zip files with the directory structure of /mods.d and /modules etc.) that I would like to install in Bibletime, but I can't find a way to do it. It used to work with just copying the file structure into ./sword, but it doesn't anymore...
Any help would be appreciated

**Comment by gholmlund** [comment]
I don't believe anything has changed with BibleTime. I do what you describe frequently.

Possibly if you have the snap version you need to know that the .sword directory is in a special location. $HOME/snap/bibletime/current/.sword

**Comment by HinzundKunz** [comment]
I just found out that as I use the flatpak version (the version in the ubuntu repositories does not display text), I had to give access to my home folder, then everything works as expected; so I am closing this report.
