### ISSUE TITLE
Double-clicking a verse number makes the bible scroll with mouse pointer movements

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#223]
This is a bug in the latest beta (3.0.0 beta2) on Linux (Ubuntu 19.10, wayland).

If you double click any verse number in the main bible text window, the text will continue scrolling when the mouse pointer is moved. The only way to reset this behaviour that I've found was to close Bibletime and open it again.

**Comment by gholmlund** [comment]
This appears to be a Qt bug in the handling of a double click.. It happens with Qt 5.9.9 but not with 12.7 or 14.1. Since we don't use double click on a text window, I disabled it.
