### ISSUE TITLE
Plain text personal commentary editing

### ISSUE THREAD

**Issue by pmwhite** [bibletime/bibletime#225]
Perhaps a decision was made, and I am not aware of it, but I just built the beta version from source, and the option to edit personal commentaries in plain text seems to have been removed. I like the feature of being able to edit a verse of the personal commentary from the reading window; however, because the font size is specified when the commentary portion is written, I cannot holistically increase the font size of the Biblical text and the commentary. I increased the font size in the configuration window, but the commentary stayed at 9 pt, which is smaller than I would like. I imagine plain text notes would not have that behavior.

**Comment by gholmlund** [comment]
Added back the choice of plain text or html. 

Two phrases will need translation. They are:
"Edit Plain text"
"Edit HTML text"

**Comment by pmwhite** [comment]
Wow, thanks for putting the work into that; I definitely appreciate it. Something that is a little annoying, but not a deal-breaker, is that any line breaks don't get ignored when displayed in reading mode, reason being that the plain text is still being displayed as html, which doesn't recognize bare line breaks. Perhaps each line break should make the whole line get contained in a `<p>` tag, but that might not be the correct behavior, since that would create a vertical separation between every line. The other minor thing is that choosing between the two options for every verse would get tedious, especially since people would probably choose the same option every time; perhaps having a global setting would be better, even if that makes forces people to only use one.

I am personally am an avid vim user, so my ideal setup is for the window to open a vim editor. I actually hacked together a really simple version of such a setup. Below is the patch that I wrote. I took a slightly different route than you did with the plain text editor; when I load the text into vim, I am preserving the HTML; I would argue this is correct behavior, since the only HTML that will show up is HTML that I personally have written. In contrast, if you strip the HTML before letting people edit it, then one cannot manually add HTML to the note, which seems to be a powerful feature. Got any thoughts about this?

Note, this is incomplete because I have some vim configuration that makes html editing a little easier. Manually editing HTML is not too bad, and it means I can add bulleted lists, or anything else that HTML supports (I haven't tested the limits though).
```
diff --git a/src/frontend/display/modelview/btqmlinterface.cpp b/src/frontend/display/modelview/btqmlinterface.cpp
index 1059b5e1..1b225b46 100644
--- a/src/frontend/display/modelview/btqmlinterface.cpp
+++ b/src/frontend/display/modelview/btqmlinterface.cpp
@@ -15,8 +15,11 @@
 #include <QApplication>
 #include <QClipboard>
 #include <QDebug>
+#include <QTemporaryFile>
+#include <QProcess>
 #include <QScreen>
 #include <QTimer>
+#include <signal.h>
 #include "../../../backend/config/btconfig.h"
 #include "../../../backend/drivers/cswordbookmoduleinfo.h"
 #include "../../../backend/drivers/cswordlexiconmoduleinfo.h"
@@ -175,16 +178,31 @@ QString BtQmlInterface::getRawText(int row, int column) {
 }
 
 void BtQmlInterface::openEditor(int row, int column) {
-
-    BtTextEditDialog dlg;
-    QString verse = m_moduleTextModel->indexToKeyName(row);
-    dlg.setTitle(tr("Edit") + " " + verse);
-
-    dlg.setText(getRawText(row, column));
-    int rtn = dlg.exec();
-    if (rtn == 0)
-        return;
-    setRawText(row, column, dlg.text());
+    QString previousText = getRawText(row, column);
+    QTemporaryFile file;
+    file.open();
+    Q_ASSERT(file.isOpen());
+    QString filename = file.fileName();
+    file.write(previousText.toUtf8());
+    file.close();
+    QProcess process;
+    QStringList arguments;
+    arguments << "--nofork" << "-c" << "set lines=20 columns=80 | execute 'normal tt' | write" << filename;
+    qint64 *processId = new qint64();
+    process.startDetached("/bin/gvim", arguments, QString(), processId);
+    while (kill(*processId, 0) == 0) {}
+    delete processId;
+    file.open();
+    QTextStream in(&file);
+    QString content;
+    if (!in.atEnd()) {
+        content.append(in.readLine());
+    }
+    while (!in.atEnd()) {
+        content.append(" ");
+        content.append(in.readLine());
+    }
+    setRawText(row, column, content);
     return;
 }
 ```

**Comment by gholmlund** [comment]
I was able to provide a good fix for the plain text line break issue. 

Regarding having plain text  strip the html. I can see for use with vim that striping might not be the right choice, but for the general user I believe it is the right choice.

**Comment by pmwhite** [comment]
It is your decision of course, but I'll make a case for not stripping html.
It isn't even about my personal vim use case.

If the user selects plain text when initially editing, then when he saves,
he will not have any html formatting. Thus, in this case the html need not
be stripped because there is never any html formatting except that which is
intentionally added, and which would be annoying to that user to have
removed.

If however the user selects the rich text mode initially, but then chooses
plain text later, then saving in plain text form will remove all
formatting, including paragraph breaks, that was added in rich text mode.
This is unintuitive and could be avoided by keeping the html. Admittedly,
the user might be confused by this, but it would also be a sign to the user
to go back to the rich text editor.

I'm partial to not stripping html, but I can see a reasonable case for the
alternative.

**Comment by gholmlund** [comment]
You are speaking from the point of view of a person knowing html syntax. I don't believe most of our users have that point of view. 
Also, if the user switches to plain text and html is stripped, they are seeing a preview of what they will save. They can still hit the cancel button to not save the entry. 
There is a technical reason also. The QTextEdit, which displays the text in the dialog box, does not show the html characters. It shows the text formatted as the html indicates. This happens even though the QTextEdit is set to show plain text. The user won't be able to change that formatting and will be confused.
