### ISSUE TITLE
Tiny fonts on Windows

### ISSUE THREAD

**Issue by tsbockman** [bibletime/bibletime#23]
The default fonts for BibleTime on Windows are tiny.

I installed BibleTime 2.10.1 on Windows 8.1 64-bit, and the default font for content was set as:
&nbsp;&nbsp;&nbsp;&nbsp;MS Shell Dlg 2 - Normal - size 8.
This is painfully small for extended reading on a typical system.

For comparison, I also tried BibleTime 2.9.2 on Linux Mint 17 KDE 64-bit, where the default font for content appeared to be:
&nbsp;&nbsp;&nbsp;&nbsp;Oxygen Sans - Book - size 14.
This is much more reasonable.

Additionally, the default text ("This is the Mag viewer area...") of the Mag pane is extremely small on Windows, but fine on Linux. It appears to be about size 7, in a compact font.

**Suggested Fix:** Change the default content font on Windows to:
&nbsp;&nbsp;&nbsp;&nbsp;Tahoma - Normal - size 14.
More generally, any size between 12 and 18 would be a reasonable default. Tahoma is available on all Windows machines; if you want a serif font I suggest Times New Roman.

The Mag pane font should be made at least as large as the font used on the other UI elements.

**Comment by Daniel721** [comment]
This is not an issue for me, at least not one that can be count, becouse I am allways changing the font size when I am first installing bibletime, and I am using this application only in linux.

**Comment by gholmlund** [comment]
Fixed by setting the default font point size to 14 if it is smaller than 14. (Windows only)
