### ISSUE TITLE
Biblletime doesn't work with the last trunck libsword

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#230]
With the new commits in sword, bibletime doesn't work. I have this error:
```
bibletime: error while loading shared libraries: libsword-1.8.1.so: cannot open shared object file: No such file or directory

```

**Comment by gholmlund** [comment]
This just means that you need an entry in /etc/ld.so.conf.d to tell your operating system to look for sword there. A conf file with "/usr/local/lib" is needed there. Then run ldconfig.
