### ISSUE TITLE
Memory leak when clicking on verse number

### ISSUE THREAD

**Issue by HinzundKunz** [bibletime/bibletime#231]
When clicking on a verse number in BT 2.11.2 flatpak, cpu spikes to 100% (one core), and QtWebEngineProcess starts leaking memory until I close the window that I clicked the verse number in. This happens in different languages (I tried German and English).

**Comment by jaakristioja** [comment]
As with many similar issues we've seen here, I suspect this is yet another bug in Qt and there is not much we can due to fix it (mostly due to lack of manpower). We will very soon (hopefully in a matter of days) release BibleTime 3.0 RC1. Hopefully the new Flatpak package will not bundle the same bug.

**Comment by HinzundKunz** [comment]
Am Freitag, 8. Mai 2020, 22:34:04 CEST schrieb Jaak Ristioja:
> As with many similar issues we've seen here, I suspect this is yet another bug in Qt and there is not much we can due to fix it (mostly due to lack of manpower). We will very soon (hopefully in a matter of days) release BibleTime 3.0 RC1. Hopefully the new Flatpak package will not bundle the same bug.
> 
> 
I just got the 3.0 rc1 installed, it does not seem to be affected by that bug. Only that all verses now start on a new line and I can't find a way to change that...

**Comment by gholmlund** [comment]
version 3.0 does not use the QWebEngine any more so I would expect to not see this bug. The new line option was removed. It is not possible to implement it and to have the continuous scrolling past chapter and book boundaries.
