### ISSUE TITLE
Handbook has no back to index

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#241]
When I look BibleTime handbook with detailed subject and then want to return to previous level of titles, there are no buttons or links to do that. Only link to previous or next section of handbook. Please, add a link "return back to previous index" or such.

**Comment by jaakristioja** [comment]
I'm not sure I understand correctly. Could you please be more precise or give some concrete example? I'm assuming you meant the HTML version and not the PDF.

On [this handbook page](https://bibletime.info/generated_docs/v3.0_rc1/handbook/html/en/hdbk-op-bookshelfmanager.html), for example, there are the "Prev", "Next", "Up" and "Home" hyperlinks for navigation.

**Comment by ilkant** [comment]
Oh, sorry. I found that link bottom of handbook page. There was "back to index" link. Iam sorry. This issue can be closed or removed.

**Comment by jaakristioja** [comment]
No problem. :-)
