### ISSUE TITLE
Update list of translators for 3.0

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#245]
The list of translators might be out of date needs to be updated in [`BtAboutDialog::retranslateContributorsTab()`](https://github.com/bibletime/bibletime/blob/ef9836e4a54fbd1d872238962048c9182e911ac5/src/frontend/btaboutdialog.cpp#L152) for the stable-3.0 (before the release of 3.0) and master branches.

Since this is a task which need to be done each time translations are pulled from Transifex (at least once in preparation of every release), the procedure needs to be documented on the ["Translation Management"](https://github.com/bibletime/bibletime/wiki/Translation-Management) wiki page, with a reference to the procedure in the ["Things to Check Before Release" section of the "Releasing BibleTime"](https://github.com/bibletime/bibletime/wiki/Releasing-BibleTime#things-to-check-before-release) wiki page as well.

See also pull request https://github.com/bibletime/bibletime/pull/237.

**Comment by jaakristioja** [comment]
This might not be as simple as I expected this to be. The translations fetched from Transifex by the command-line `tx` tool does not seem to include information about the translators.

**Comment by jaakristioja** [comment]
Since setting up a more automated solution for this will not happen before 3.0, I kindly ask all translators who want their name to be added to (or corrected or removed from) the list of translators in the About dialog to comment here.

**Comment by dagsoftware** [comment]
please add:
**DAG Software (Ďanovský Ján)** - _(dagsoftware; slovak; GUI)_

**Comment by ilkant** [comment]
Iam on the list #2. My name can be added to the new list.

Ilpo Kantonen - (GUI 100 %, HowTo 100 %, mobile 100 % translated).

**Comment by jaakristioja** [comment]
It is not a new list, we're just updating the existing list.

Updated the list in 0b5c4feb5 in the master branch and 4699ca629 in the stable-3.0 branch.

**Comment by jaakristioja** [comment]
Actually, I think it is best to let translators themselves choose whether they want to be included in the list of contributors or not. For this reason, I just used the Transifex announcements feature to send them a reminder. I hope we can remember to send new ones in the future.

Closing as WONTFIX.
