### ISSUE TITLE
The snap version of 3.0 RC1 lacks an icon

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#251]
On Ubuntu 20.04 LTS the Bibletime 3.0 RC1 snap lacks an icon and Gnome Dash shows a generic app icon instead.
Minor Bug.

**Comment by gholmlund** [comment]
Fixed in:
repository bibletime/build-snap
commit 307c7a15da2c5c6c3d14b4bdfe220753caad6e54
