### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#254]
Today I tried opening Bibletime 3.0.0RC1 (snap) on Ubuntu 20.04 in an X11 session and got a Segmentation fault:
```
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object width does not accept value [75 100)
Segmentation fault (core dumped)

```

**Comment by entodoays** [comment]
Today I tried opening it again and it didn't segfault. Maybe one of the updates has solved the problem.

**Comment by jaakristioja** [comment]
Without a backtrace it is very difficult to assess the bug.

I understand that it works now. Please reopen if this persists and you can provide a backtrace.

**Comment by entodoays** [comment]
Can you please tell me how to provide a backtrace? I tried to get more 
info, but got confused on how to go about it.

**Comment by jaakristioja** [comment]
Does it still happen?

I don't know exactly, but I suppose you have to run the snap using something like `snap run --gdb bibletime` and when it crashes and gives you the gdb command line, type the command `bt` to print the backtrace. Thou `thread apply all bt full` will probably output more details.

**Comment by entodoays** [comment]
The problem vanished with some system update, but would like to know how 
to help bug fixing should this or other issues arise.
