### ISSUE TITLE
Remove build-debug.sh and build-release.sh

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#257]
I would really like to remove the `build-debug.sh` and `build-release.sh` files. These just seem to be causing extra trouble for our users when they run into compile-time issues with CMake not properly finding packages etc. Its not trivial to teach them to use CMake if these scripts fail. Additionally, since `build-release.sh` by default calls CMake with `-D CMAKE_INSTALL_PREFIX=/usr/local` this causes users to run the script as root.

I think it is reasonable to remove these files and assume basic knowledge of compiling CMake projects for people who try to compile BibleTime from source. README.md should be updated accordingly.

@gholmlund What do you think? I think I might have a memory of having raised this issue before and having met some objections.

**Comment by gholmlund** [comment]
@jaakristioja  Sorry I missed this originally. I never use these scripts. It is Ok with me to remove them.

**Comment by jaakristioja** [comment]
Fixed with commit 171fb95e2d6fd49f4cdb5e6d22a1a0b369cfded6 in the master branch. I don't think it would make good sense to backport this to the 3.0 branch. Closing.
