### ISSUE TITLE
BIbleTime 3.0 installs /usr/bin/DisplayView.qml on Linux

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#260]
As [noted](https://www.crosswire.org/pipermail/bt-devel/2020-August/011537.html) by @greg-hellings, on Linux BIbleTime 3.0 installs the /usr/bin/DisplayView.qml file which is probably not needed.

This seems to be caused by the [QTBUG-55259](https://bugreports.qt.io/browse/QTBUG-55259) workaround in [cmake/BTApplication.cmake:178-185](https://github.com/bibletime/bibletime/blob/stable-3.0/cmake/BTApplication.cmake#L178) which installs the file even for non-affected platforms.

**Comment by gholmlund** [comment]
The Display.qml file is required to be present for the display of text windows. The only choice is what path it is located on. Currently there is no other path setup where it could be moved to without some changes in code. Perhaps it can be compiled in as a resource file.

**Comment by greg-hellings** [comment]
I'll just package it with Bible Time for now in Fedora. That is, unless the patch point is easy to relocate it. Hopefully we can figure another place for it to live later.

**Comment by gholmlund** [comment]
@greg-hellings   For linux only cmake/BTApplications.cmake and src/frontend/display/modelview/btquickwidget are needed.
