### ISSUE TITLE
Finnish Biblia contains english apocryphal book names

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#262]
Look the issue #261 to understand the background to this issue.

I opened FinBiblia and FinPR92 (finnish language bibles). Scandinavic letters looks fine. But the FinBiblia had more bible books than before. I think that now there are also apocryphal books too. That is not bug of BibleTime. But their book names were english text. That is a bug.

The FinPR92 does not contain apocryphal books. I think that this is not bug of BibleTime. And not a bug of Sword library.

And thanks releasing new version 3.0. Many things works ok.

**Comment by ilkant** [comment]
The book names not finnish are: Tobit, Judith, Eshter (Greek), Wisdom, Shirac, Baruch, Prayer of Azariah, Bel and the Dragon, 1&2&3&4 Maccabees, 1&2 Esdraz, Prayer of Manasses, Additional Psalm.

They have finnish names, but they are not in BibleTime translatable texts.

**Comment by gholmlund** [comment]
The book name translations are contained in sword files. On linux you will find them at /usr/share/sword/locales.d or /usr/local/share/sword/locales.d. For Finish see the fi.conf and fi-utf8.conf files. You could add the translations to these files.
Please file a defect report to the sword project to get this fixed.
