### ISSUE TITLE
Linking test_btsourcesthread fails with undefined references to libsword symbols

### ISSUE THREAD

**Issue by timsoftgit** [bibletime/bibletime#264]
trying to compile bibletime 3.0
the error message given when the make process fails is...

```
/tmp/cc7xMIkP.ltrans4.ltrans.o: In function `Filters::OsisToHtml::handleToken(sword::SWBuf&, char const*, sword::BasicFilterUserData*)':
<artificial>:(.text+0x857): undefined reference to `sword::SWBuf::SWBuf(char const*, unsigned long)'
<artificial>:(.text+0x980): undefined reference to `sword::SWBuf::SWBuf(char const*, unsigned long)'
<artificial>:(.text+0xac8): undefined reference to `sword::SWBuf::SWBuf(char const*, unsigned long)'
<artificial>:(.text+0xba0): undefined reference to `sword::SWBuf::SWBuf(char const*, unsigned long)'
<artificial>:(.text+0x12a7): undefined reference to `sword::SWBuf::SWBuf(char const*, unsigned long)'
/tmp/cc7xMIkP.ltrans4.ltrans.o:<artificial>:(.text+0x14d5): more undefined references to `sword::SWBuf::SWBuf(char const*, unsigned long)' follow
collect2: error: ld returned 1 exit status
CMakeFiles/test_btsourcesthread.dir/build.make:169: recipe for target 'test_btsourcesthread' failed
make[2]: *** [test_btsourcesthread] Error 1
CMakeFiles/Makefile2:2331: recipe for target 'CMakeFiles/test_btsourcesthread.dir/all' failed
make[1]: *** [CMakeFiles/test_btsourcesthread.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

this is on slackware 14.2. cmake (using cmake v3.17.2) completes, and the error is given when running make, before running make install

**Comment by timsoftgit** [comment]
I should say that sword 1.8.1 patched with rev 3721 is installed (and works for xiphos)

**Comment by jaakristioja** [comment]
Looks like a bug.

If you just want to build BibleTime and don't care about the tests, you can just comment out the following line in `cmake/BTApplication.cmake`:

```cmake
INCLUDE("${CMAKE_CURRENT_SOURCE_DIR}/cmake/BTTests.cmake")
```

But if you have time, could you please do the following:

1. Start with a clean build
2. Run `cmake` as you did
3. Run `make` as you did
4. Run `make VERBOSE=1`
5. Please paste the output of steps 2 and 4 to this issue.

**Comment by timsoftgit** [comment]
as requested, output from running cmake and running make VERBOSE=1 after running make

[cmake.output.txt](https://github.com/bibletime/bibletime/files/5033811/cmake.output.txt)
[makeverb.output.txt](https://github.com/bibletime/bibletime/files/5033815/makeverb.output.txt)

**Comment by timsoftgit** [comment]
note. (in case you're wondering at the non-standard location of cmake binary,)  a local version of cmake 3.17.2 is temporarily installed in /tmp/tmpcmake/bin with it's supporting files, and added to the beginning of the PATH variable
for use my build script as the (os) system version of cmake is too old (3.5.2).

**Comment by jaakristioja** [comment]
Thank you. I believe this information is sufficient. We'll likely fix this issue for 3.0.1.

**Comment by timsoftgit** [comment]
great. In the meantime i'll try the "commenting out of tests" suggestion, so that I can at least get 3.0 out the door, so to speak.

**Comment by timsoftgit** [comment]
commenting out of tests works as a workaround.
sed -i "/BTTests/s/^/#/" cmake/BTApplication.cmake
run in the src dir does the trick.

**Comment by jaakristioja** [comment]
The largely orphaned tests are now removed from the `master` and `stable-3.0` branch by commits d05797db79074c526987329dff78d89eef8c501c and 09805c4f39b6aea90a57a3b3dba65a4770dfe1ef respectively. See bugs #320 and #321 for details.
