### ISSUE TITLE
Incomplete initialization of FilterOptions in CInfoDisplay

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#27]
In `src/frontend/cinfodisplay.cpp` in methods `decodeCrossReference()` and `decodeFootnote()` the variable struct

    FilterOptions filterOpts;

is incompletely initialized before passing it on to other functions. Reported by Coverity and these do look like bugs.

Martin, this looks like your code (45c9cc34 and 0023b4a0).

**Comment by gholmlund** [comment]
Fixed by commit 9fc107b
