### ISSUE TITLE
Support for multiple canons

### ISSUE THREAD

**Issue by tikajr** [bibletime/bibletime#270]
As it is now, bibletime assumes a 66 book protestant canon (unless there's a setting I haven't noticed).

Seeing as there is not, and never has been, [a single universally accepted Christian bible canon](https://en.wikipedia.org/wiki/Biblical_canon#Table), and [the vast majority of Christians world-wide do not follow the Protestant canon](https://en.wikipedia.org/wiki/List_of_Christian_denominations_by_number_of_members), it would make sense to add support for other canons.

While I myself am a non-sectarian Christian with feet in many denominations, my home base is Catholicism, so I post this issue as a Catholic keen to support this project.

With that said, I understand that the priority of this might be low if you have hard demographic-statistics which show that most users of this software are protestants or evangelicals

**Comment by greg-hellings** [comment]
A few things to note:
1) BibleTime doesn't keep track of the canon, that is taken from SWORD
2) SWORD supports canons other than the 66 book Protestant canon. A list of the canons supported, including their contents, can be found by looking into [the SWORD source](http://crosswire.org/svn/sword/trunk/include/) at the files titled "canon_*.h"

A quick listing there shows canons named for the major source or work(s) that they are based on, all in addition to the default 66 book KJV work, which is assumed when one of these is not specified.

* Calvin
* Catholic
* Catholic2 (two major variants of the Catholic canons in use)
* Darby French
* German (not to be confused with Luther)
* KJV + Apocrypha
* Leningrad (derived from the Leningrad Codex and its related texts)
* Luther (based on Martin Luther's translations)
* LXX (from the Septuagint)
* MT (from the Masoretic Text)
* NRSV
* NRSV + Apocrypha
* Orthodox
* Segond
* Synodal
* Synodal Protestant
* Vulgate

Others can be added to the list if needed, but that seems to cover most all of the texts that people have brought to SWORD. The engine will only add new canon lists when a work that requires them comes out. However, as each new one increases the memory required to run the engine, Sword is conservative about adding new canons, only doing so when a real incompatibility arises. If one work is just a strict subset of an existing canon system, then it will not be added. For instance, if a work follows the Vulgate but leaves out chapter 1 of every book, then a new system won't be created for it.

The module itself needs to specify the canon that it uses. So you can't just say, "I'm using the KJV, but I want to reference it with a Catholic versification system". The module itself tells BibleTime what system to use and self-reports its viable chapter and verse ranges and book order. Thus, multiple versification systems are available and used, but it's likely invisible to the user.

**Comment by tikajr** [comment]
Hmm, perhaps there's a bug then.

I've opened four bibles in parallel (Vulgate, ASV, Byz, HebModern) but the dropdown to select book follows the protestant canon. There's no way to access the catholic books as far as i can tell

**Comment by gholmlund** [comment]
In parallel, BibleTime can only use a single canon. I believe the left column canon is used.

**Comment by greg-hellings** [comment]
Well, ironically, none of those modules use anything other than the KJV versification!

Some of those modules are downright ancient in terms of Sword version. The ASV and Vulgate modules were created back in 2006, long before SWORD supported anything other than KJV. HebModern was just created this past February, but explicitly requests the KJV versification. Byz was created in 2014.

I imagine that, if a source can still be found, the Vulgate should be recreated in the Vulgate versification at the very least. But that's a task for the CrossWire module folk.
