### ISSUE TITLE
High-light adjustment

### ISSUE THREAD

**Issue by ArnoVersfeld** [bibletime/bibletime#273]
When portions are high-lighted the high-light is higher than the font height and influences the readability when more than one line is high-lighted. 
Could the high-light height please be changed to be the same height as the font height.
[High-Light.docx](https://github.com/bibletime/bibletime/files/5140157/High-Light.docx)

**Comment by jaakristioja** [comment]
Contents of the [docx from the comment above](https://github.com/bibletime/bibletime/files/5140157/High-Light.docx):

> ![Screenshot_20200904_191542](https://user-images.githubusercontent.com/2684083/92261976-170df900-eee3-11ea-90b3-dedb11a244c3.png)
> 
> 
> Above is the same portion to illustrate my request.
> There is a “g” in arrogance and “p” in pride.
>
> With the first line high-lighted the “g” and “p” are clear.
> 
> With two lines high-lighted the bottom part of the “g” and “p” is barely visible,
> Hence my request that the high-light be changed to be exactly the same
> as height as the font size.
> 
> Many thanks
> Arno.

**Comment by gholmlund** [comment]
@ArnoVersfeld - Can you tell us which font is used in the above example and what is the reference for this text. 
I have not been able to reproduce your issue. By choosing different fonts I have been able to see either "touch  without overlap" or "a gap". 

I  don't believe BibleTime has any control over this selection overlap. I may be that just choosing a different font will fix your issue.

**Comment by ArnoVersfeld** [comment]
The font is set to DejaVU Sans, Style Oblique.
I've tried a number of different fonts but get the same results with all of them.
I'll look into Ubuntu itself and see if I can find anything that may  be causing the problem.
Are you using Windows for your tests ? It may be that the two Operating Systems are not functioning in the same way.

**Comment by gholmlund** [comment]
I have been testing with the latest Fedora and Ubuntu, using KDE Plasma. I did some more testing now and I still cannot reproduce this issue.

**Comment by ArnoVersfeld** [comment]
Thank you so much for your trouble with this challenge !
I feel that there are, more than likely, far more important matters for you to attend to and seeing I don't high-light portions every time I use Bibletime I rather close this issue.
You folk are doing a great job with this program and I can't thank you enough for it !
