### ISSUE TITLE
Add MySword (.bbl.mybible) and e-sword (BBLX and BBLI) module file support? Perhaps better Aramaic support with SEDRA lexicon numbers?

### ISSUE THREAD

**Issue by machshev** [bibletime/bibletime#274]
Apologies for putting quite a lot in this ticket, I'm just floating the idea at the moment and can split it down into more actionable steps later if it gets the support.

Thank you so much for creating Bibletime, I have been using it since the first versions and find it to be easily the best bible study tool out there at the moment. The desktop app is great for writing up studies, where I can copy and paste sections of text for commentary. On my android phone, I use the BibleLexicon SWORD based app and also MySword out of necessity as there is a module I have that is only available in e-sword/MySword format. At the moment I've no way of using these modules on my desktop (Fedora Linux), as mysword is android only. E-sword can be installed on Linux using Wine, but it's far from a good solution.

There are some bblx modules that I've paid for that I can't find equivalents for in standard SWORD module format (otherwise I'd have just used those instead). These are Peshitta texts with the corresponding Lexicon using SEDRA numbers (http://sedra.bethmardutho.org/about/openapi), both of which are available as open texts. I'd like to make a SWORD module for these but haven't got the time right now.

I've considered making a conversion tool in Python that will convert MySword modules into SWORD modules (and may do that anyway), but couldn't make the resulting modules available to others as they are paid for (despite being based on open texts). It's not an ideal solution either as it means running it against every new module (and module version) and maintaining that would be difficult unless there was buy-in from every module provider to distribute in all the main formats - which just isn't going to happen. I could resolve my problem with a bespoke solution, but If Bibletime supported these other module formats directly then that would mean that everyone in a similar situation would have immediate use of all modules in each respective ecosystem.

The .bbl.mybible, BBLX, and BBLI formats are all SQLite DB files with a very similar schema. Some e-sword modules have verses as encrypted blobs, which clearly would not be supported... however many seem to be plain text with fairly simple HTML/XML format. I've briefly looked at the BibleTime source code and unless I've misunderstood there seems to be the infrastructure there already for different formats `/src/backend/filters/XYZtohtml.cpp`.

So an initial implementation could be to support the `.bbl.mybible` format, which at least in the modules I've got, are in HTML format anyway.
1. Use SQLite library to open the module file
2. the filter would then pass through the verse text unchanged

An example of the text for Matt 1:1,

```
כתבא <a href='d-OANT-dict S10762'>S10762</a> K'ThaaVaA Book דילידותה <a href='d-OANT-dict S9144'>S9144</a> D'eeyLeeyThuuTheH of The Genealogy דישוע <a href='d-OANT-dict S9568'>S9568</a> D'YeShuu of Yeshua משיחא <a href='d-OANT-dict S12523'>S12523</a> MSheeyKhaA The Messiah ברה <a href='d-OANT-dict S3245'>S3245</a> B'ReH The Son דדויד <a href='d-OANT-dict S4227'>S4227</a> D'ThaWeeyTh of David ברה <a href='d-OANT-dict S3245'>S3245</a> B'ReH The Son דאברהם <a href='d-OANT-dict S167'>S167</a> D'aAVRaaHaaM of Abraham
```

This would provide the bible text, and search support, but not the lexicon lookup. The example above shows SEDRA numbers, which are in the form SXXXX rather than the HXXXX, and GXXXX numbers used by strongs. These are specified with anchor tags with href to directly reference a specific dictionary `.dct.mybible` module which is also a simple SQLite DB file. So that would have to be supported as well, and then the bible text HTML filtered to provide the format BibleTime expects for lexicon lookup for HXXXX, GXXXX, and perhaps at a later point SXXXX?

Anyway, what do you think? I'm happy to have a go at this myself if people think this would be useful, otherwise, I might just take the easy route and write a conversion script to get round my particular issues. Perhaps open up some pull requests to add support for SEDRA numbers for Aramaic NT texts, and create a SWORD module for the Peshitta with SEDRA numbers and a SWORD module for a SEDRA keyed lexicon if I've got time.

**Comment by jaakristioja** [comment]
I apologize for not responding earlier. I think your idea is very good and I would like to support it, but to be honest it would be a terribly huge amount of work. Since getting things like this accepted to the Sword library will likely not succeed (you could try but I'm very sceptical), and BibleTime does not have the manpower to do this, I think you are better off writing a conversion script. I'm sorry if this is a disappointment.
