### ISSUE TITLE
highlighting of choosen text

### ISSUE THREAD

**Issue by youngoldi** [bibletime/bibletime#279]
At the version 2 the choosen (by search) bible texts was highlighted so it was easy to see and find it again.
Would it be possible get this highlighting back?
(If it just not working at my Mac Catalina then it may be a bug)

**Comment by gholmlund** [comment]
I have tried to reproduce this on linux and Mac (10.14). I have tried both light and dark modes. I don't see any problem in the search dialog. Here is an image of what I typically see. 
![search](https://user-images.githubusercontent.com/3507381/96021618-8ccf8380-0e04-11eb-8792-e4855ff0c8f1.png)

**Comment by youngoldi** [comment]
thanks gholmlund
You are right, in the search window I get the highlighting too.
perhaps I could not explain it right: I mean the choosen verse in the main window is not more highlighted, like I did manually in the sample picture:
![BT3 0_highlighting_sample](https://user-images.githubusercontent.com/62396046/96043276-5da62a00-0e77-11eb-9bbe-3f110e7e4743.jpg)

So it looked in BT2 on my old Mac:
![Bildschirmfoto 2020-10-15 um 00 08 50](https://user-images.githubusercontent.com/62396046/96045698-ff7b4600-0e7a-11eb-8c31-d2557baec4f8.png)
