### ISSUE TITLE
Incomplete initialization of FilterOptions in BtHtmlReadDisplay

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#28]
In `src/frontend/display/bthtmlreaddisplay.cpp` in method `text()` and `decodeFootnote()` the variable struct

    FilterOptions filterOpts;

is incompletely initialized before passing it on to other functions. Twice! Reported by Coverity and these do look like bugs.

Gary, this looks like your code (aa86cf92).

**Comment by gholmlund** [comment]
Fixed by commit 9fc107b
