### ISSUE TITLE
Hash Verification of Modules

### ISSUE THREAD

**Issue by monark88** [bibletime/bibletime#280]
Hello. I've searched through the BT source, and even the SWORD module format itself.  I could be missing something, but I'm not seeing any hash verification of modules.  I don't see any hashes in the SWORD modules for individual verse text, nor hashes for the zip modules themselves, where a client could verify that we did in fact obtain an unaltered version of the module.  My issues is this: **How can we know that a module has not been modified during transit, or while at rest on the crosswire servers, or local device?**

I have played with this to great extent on my own, and have written a little tool that will convert the modules to SQLite DBs, along with a hash of each verse so that I can see the changes between module versions.  I'm just wondering if anything like this exists within either the SWORD project's infrastructure or application code, as I feel in the coming years we should be prepared for malicious actors looking to modify the precious contents of these modules.

EDIT: Also, if this is not the proper place for this type of question/suggestion, please direct me to the proper channel.

**Comment by greg-hellings** [comment]
There is no hashing or similar verification algorithms used in Sword. If such would to be implemented it should be done at the level of the engine and would need to be discussed on sword-devel. Since CrossWire owns most of the repositories, and the others are owned by people who collaborate at that level, then the appropriate place to discuss and implement such a feature would be there where repository owners would be involved.

**Comment by jaakristioja** [comment]
In addition to what Greg stated, I would like to add that I think it is unlikely that something like this will be added to the Sword library in the foreseeable future. It is most unfortunate that security and code quality does not seem to be one of their priorities. Given the current situation in the world I think we are already running late.

PS: Anybody want to hire me to work full-time to create an alternative to the Sword library? :-)
