### ISSUE TITLE
Clicking on verse number should make that verse the reference box

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#283]
At the moment, when you click on a verse number in the bible window nothing happens. I think it would be good if this action makes the verse become the selection in the reference box in the navigation toolbar.

**Comment by gholmlund** [comment]
If you click/drag the verse slightly and drop it onto the text window, it does what you suggest.

**Comment by entodoays** [comment]
I tried it and it is true. It's not that intuitive though. It hadn't crossed my mind that you may do that.

**Comment by gholmlund** [comment]
I have added the requested feature.
