### ISSUE TITLE
Unable to import SWORD module as ZIP file

### ISSUE THREAD

**Issue by Dockerfile256** [bibletime/bibletime#286]
I have downloaded the ESV SWORD module from the wayback machine (for some reason, it was removed from Crosswire a while back). I have it working perfectly on AndBible (the open-source Bible reading app for Android). However, I occasionally like to read the Bible on the desktop, and I think that bibletime is great software for doing so.

To import my ZIP file, I tried to use the bookshelf manager to add a Local repository. However, it won't detect the "ESV.zip" file contained in the directory that I point it at. This could be a bug, or it could just be my ignorance. However, any help would be appreciated.

Thank you and God bless!

**Comment by jaakristioja** [comment]
As far as I know our backend (the Sword library) does not support reading from ZIP files. You would probably have to unpack it manually somehow.

PS: As for the availability of ESV, please see [this sword-devel thread](http://crosswire.org/pipermail/sword-devel/2019-June/047088.html). There might be some licensing issues involved so be sure not to do anything illegal. :-)

**Comment by tuomas2** [comment]
Just a little correction here: [AndBible](https://github.com/AndBible/and-bible/) has supported installing modules from zip files for ages already (I don't remember exact date but surely before december 2020, probably already 2016-2017 or so).
