### ISSUE TITLE
OSHB and Morphologie

### ISSUE THREAD

**Issue by jd-s** [bibletime/bibletime#296]
I have a question regarding morphologie and OSHB Bible. While in Greek NT Bibletime shows detailed morphological information, in OSHB I only receive short forms like HNcmsa. 

* How are these morphological information managed in general? Are these coming from modules?
* How can I modify them, for example to translate these information to other languages?

Thanks!

**Comment by LAfricain** [comment]
Hello,
First you need to install two modules. OSBH and OSHM (language english).
Did you try the last version of bibletime? On ubuntu 20.04 you can use the ppa. With the ppa version on my ubuntu 20.04 it's working well.
For the translation, I had the same idea for the French. You need to use the english as template and translate all the words: https://github.com/openscriptures/morphhb/blob/master/parsing/Oshm.xml
Maybe it's also possible to use a script on the oshm repo. But I didn't investigate a lot.

**Comment by LAfricain** [comment]
This issue can be closed
