### ISSUE TITLE
MyOwn.css didn't appear to settings BT 3.0.0

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#298]
I copied Simple.css to MyOwn.css and changed text to white and background black. And I put that file to ~/.bibletime/display-templates/MyOwn.css. It didn't appear to BibleTime Settings at next program starting. Then I copied it to /usr/share/bibletime/display-templates. Didn't appear to Bibletime at next program starting. Then I edited ~/.bibletime/bibletimerc to have MyOwn.css. Again it didn't appear to Bibletime at next program starting.

What should I change that it could get effect to program?

**Comment by gholmlund** [comment]
The style files in display-templates now come in pairs. There are Simple.css and Simple.cmap files. The color information is now in the *.cmap files. See the README.txt file in the BibleTime display-templates directory. 

This was done to support the dark mode that BibleTime now has. If the operating system is in dark mode, BibleTime will automatically go to dark mode.

**Comment by ilkant** [comment]
I see no README.txt file in the BibleTime display-templates directory. Not in /usr/share/... either ~/.bibletime/...

**Comment by ilkant** [comment]
The dark mode was not my aim to change style. I think that I need more with verse number. More space after it and not so little numbers that I can't see them. Black / white text was a test.

**Comment by ilkant** [comment]
Is there somewhere an example of Bibletime .cmap file? I think that Google brings QSetting .ini examples, but they don't help me to  write Bibletime style .cmap file.

**Comment by ilkant** [comment]
I copied from GitHub a .cmap file to ~/.bibletime/display-templates directory and /usr/share/bibletime/display-templates directory as MyOwn.cmap. And restarted BibleTime. Didn't appear to settings.

**Comment by gholmlund** [comment]
My comments refer to BibleTime 3.0. If you are using older versions the .cmap file is not used. But the .css files should appear in the settings as you mentioned.

**Comment by ilkant** [comment]
I use 3.0.0.

**Comment by ilkant** [comment]
When I start BT 3.0.0 at console:
$ bibletime
Qt: Session management error: Could not open network socket

Bug BibleTime runs ok and without MyOwn style.

**Comment by gholmlund** [comment]
My mistake. The README.txt file is only in the source files, not the install package. You can see it here.

https://github.com/bibletime/bibletime/blob/master/src/display-templates/README.txt

**Comment by gholmlund** [comment]
If you are running the snap of BibleTime 3.0, snap does not use the standard directories. Put your style files here:

$HOME/snap/bibletime/current/.bibletime/display-templates

**Comment by ilkant** [comment]
Yes! Now it appears to Settings display templates. And Bibletime have texts white with black background. Thanks. Now I can continue to develop best style for me.

It is complicated environment when apt installs other place than snap.

**Comment by ilkant** [comment]
One comment. The preview on Settings dialog displays text as red. And BT shows black text when i have set it so. I mean that preview is not wysiwyg. Text colors are different.

**Comment by gholmlund** [comment]
We will keep this open to look into the Settings dialog issue. Thanks.

**Comment by jaakristioja** [comment]
Please let's try not to have multiple different issues under a single GitHub issue as this hurts issue tracking. I'm closing this one as a question and opening a new GitHub issue for the Settings dialog problem.
