### ISSUE TITLE
Cannot copy verses Mac OS X

### ISSUE THREAD

**Issue by buckeyered80** [bibletime/bibletime#30]
The option to copy references (with text, reference only, or reference with text) upon right clicking any verse number is grayed out in the Mac OS X version. Anyone else have this issue?

**Comment by whodafly** [comment]
Which version of BibleTime are you using?

**Comment by whodafly** [comment]
I can confirm this on 2.10.1-2, ESV, KJV and NETtext

**Comment by buckeyered80** [comment]
Yes. It is version 2.10.1-2. I have tried with all of these versions: KJV, KJVA, LEB, ESV, WEB, NHEB and Godsword.

**Comment by gholmlund** [comment]
For me they work on stable-2.10 and master branches, if I right click on the verse number. They are grayed out if clicking elsewhere on the text.

**Comment by gholmlund** [comment]
After examining the source code it is clearly designed to enable the menu when over a verse number or an embedded cross reference. This should work correctly. If it is not working, it would likely be a Qt issue and perhaps only a Qt on Mac issue. 

Please provide the Qt version number. You can see it in the Help > About BibleTime menu. 

Also, it this only seen on Mac?

**Comment by buckeyered80** [comment]
Qt version 4.8.6. I don't have the issue on Linux. I don't have a Windows machine to test.

**Comment by mgruner** [comment]
Works fine for me when I click on the reference with 2.10.1-2 in ESV on El Capitan. Please feel free to provide more info!

**Comment by buckeyered80** [comment]
It works now after the upgrade to El Capitan. Not sure what the issue was now.
