### ISSUE TITLE
Bookmark file writing access denied

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#301]
BT 3.0.0 installed with snap. I tried to save bookmarks to file. It popped up file creation access denied. The directory is  ~/snap/bibletime/9/

That directory:
drwxr-xr-x 6 userme userme 4096 helmi  18 02:00 .
drwxr-xr-x 4 userme userme 4096 helmi  18 02:00 ..

Is that issue of BIbleTime or my computer?

BTW, finnish translations were bad at bookmark saving. I fixed them with Transifex.

**Comment by gholmlund** [comment]
The directory ~/snap/bibletime/9/.bibletime is the one to check the permissions.The first 4 chars should be "drwx" for all owner permissions.

**Comment by ilkant** [comment]
Maybe this is same issue. When I push handbook in toolbar, it produces access denied in btowser screen. The directory is:

file:///snap/bibletime/9/share/doc/bibletime/handbook/html/fi/index.html

**Comment by ilkant** [comment]
The first problem solved. Is this second problem file permissions ok? It is root but I use BibleTime with my own user privileges.

-rw-r--r-- 1 root root 9267 elo     3  2020 /snap/bibletime/9/share/doc/bibletime/handbook/html/fi/index.html

**Comment by gholmlund** [comment]
Your permissions for the index.html file are correct. It may be a chromium permission issue. 
Try entering /snap/bibletime/9/share/doc/bibletime/handbook/html/fi/index.html into chromium as the url. See if that loads correctly.

**Comment by ilkant** [comment]
I bought a new computer. I'll get it in 2 weeks. I look forward to it. If the problem with handbook opening persists, I'll return here. The problem can be aroused when I installed OS to new hard disk and username is same. But in system user id can be different.

**Comment by jaakristioja** [comment]
Please reopen if this is still an issue after the 2 weeks mentioned.
