### ISSUE TITLE
"Saves chapter as" does not save chapter right-clicked on

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#303]
When I open a Bible to BT 3.0.0 and point mouse on 1 Samuel 12 verse 3 for example. Then I push mouse right button and save whole chapter in txt mode and in html mode.

But they are from 1. Samuel 11 chapter. texts. Maybe this is issue of index which begins value 0.

**Comment by gholmlund** [comment]
The "save" is based on which chapter is showing in the toolbar. Perhap it should be changed?

**Comment by ilkant** [comment]
Ok. I made a new test. I scrolled text to chapter 14 and verse 3. It saved chapter 13. But it was on screen: last two verses. And chapter 13 in toolbar. Nice to know that it takes chapter in toolbar.

**Comment by jaakristioja** [comment]
This is indeed confusing and should be changed somehow. Perhaps there should even be a "Save chapter" dialog which lets one change the chapter as well as the output format?
