### ISSUE TITLE
Change sample text in settings dialog

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#306]
The sample text in the settings dialog only contains the words of Jesus, and is hence (for most styles) rendered red. This is not optimal in this context, as the user might want to see more features of the chosen display style in the preview widget. The sample text should be changed to something which contains regular text as well, and if possible, other features e.g. headings.

Although I'm currently not in favor of allowing the users to select verses for the sample text, we should still keep this possibility open.

**Comment by gholmlund** [comment]
How about John 3 from the NASB. It has footnotes, cross references, Jesus words,headings, and regular text.
![image](https://user-images.githubusercontent.com/3507381/109045375-56462700-7688-11eb-99d2-ef7e04ee06ca.png)

**Comment by jaakristioja** [comment]
Yes why not, unless this causes copyright issues. Anyway, you can choose! :-)

**Comment by jaakristioja** [comment]
@gholmlund  Thanks, this looks way better now! 👍🏻
