### ISSUE TITLE
[BUG]Bibletime 3.0  Chinese font size can't be changed at MacOS Catalina 

### ISSUE THREAD

**Issue by aaron2wh** [bibletime/bibletime#309]
**Describe the bug**
A clear and concise description of what the bug is. Please only describe one issue per bug report.
Bibletime 3.0  Chinese font size can't be changed at MacOS Catalina and the default size is too small to read.
i think it mayber because Chinese font is a 2bit font. just my thought.
and when i installed bibletime 3 to High Sirra, there is no such bug.

**To Reproduce**
1. Go to 'Preferrance'
2. Click on 'Fonts.'
3. Scroll down to 'zh-hans/ zh-hant.'
4. 'use custom font' change font size and apply 
5. nothing changed

**Expected behavior**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**System information (please complete the following information):**
 - OS and OS version: [e.g. Debian 10, Windows 10] macOS Catalina
 - BibleTime Version [e.g. 3.1_rc2] 3.0
 - How BibleTime was installed [e.g. from system packages, Snap, Flatpak, installer, compiled from source code]download from GitHub
 - Versions of modules related to the crash (if known)
 - (If compiled from source) Sword Version
 - (If compiled from source) Qt Version

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.

**Comment by aaron2wh** [comment]
![截屏2021-04-21 上午9 24 27](https://user-images.githubusercontent.com/43267693/115483543-8cb4b280-a283-11eb-9cdf-3226264eb3ec.png)
![截屏2021-04-21 上午9 25 00](https://user-images.githubusercontent.com/43267693/115483548-8fafa300-a283-11eb-8324-69cc324b1f43.png)

**Comment by gholmlund** [comment]
In the picture above you show setting the "English" custom font. You need to set the "Chinese" custom font. 
I tried this with the ".AppleSimplifiedChineseFont" and set the font size to 36. It appeared easy to read when I open a Chinese Bible.

**Comment by aaron2wh** [comment]
I have tried many time, it just don't work. when you close and reopne the preferrance panel , it changed back to this pic again.
have you tried in Catalina?

**Comment by gholmlund** [comment]
I tried it on 11.1 Big Sur which is all I have access to. I doubt that the os version is causing this. 
You could try to directly edit the preferences.
In the file <home dir>/Library/Application Support/BibleTime/bibletimerc, I have the following related to fonts.

[fonts]
Chinese=".AppleSimplifiedChineseFont,36,-1,5,50,0,0,0,0,0"
English="Arial,13,-1,5,50,0,0,0,0,0"

Before editing the file check it exists and has read and write permissions.

**Comment by aaron2wh** [comment]
I have edit the file but nothing changed.
could you attach the whole bibletimerc file if possible

**Comment by aaron2wh** [comment]
haha, I just figure out myself. I edit the file adding following lines:
[font%20standard%20settings]
Zh-Hant=true
zh-Hans=true

[fonts]
zh-Hans=".AppleSimplifiedChineseFont,18,-1,5,50,0,0,0,0,0"
zh-Hant=".AppleSimplifiedChineseFont,18,-1,5,50,0,0,0,0,0"


its zh-Hant/s not Chinese.
and also shoud enable the true value.
anyway thank you, your idea gave me inspiration.

**Comment by gholmlund** [comment]
Glad that you found the issue.
