### ISSUE TITLE
BibleTime "hangs" when updating bookshelf on MacOS X "Yosemite", April 2015

### ISSUE THREAD

**Issue by DerekNelson-Wills** [bibletime/bibletime#31]
Whilst attempting to update the bookshelf, post-installation, BibleTIme "hung" whilst indexing "Abbott" dictionary.

A full "bug-trace" is available.

**Comment by jaakristioja** [comment]
Sorry for the late reply. Can you share the bug-trace with us please?

**Comment by DerekNelson-Wills** [comment]
Dear Jaak,

I did send the bug-trace with my email.  I can only guess that it was “stripped out” somewhere along the route.

If the same happens again, I will save the bug-trace as a document and attach it, rather than including it in the email text.

Sorry about this,

Derek.

**Comment by jaakristioja** [comment]
It were best if you included it here.

**Comment by jaakristioja** [comment]
Timed out. Closing. Reopen if needed.
