### ISSUE TITLE
BibleTime 3 doesn't show letters in OpenBSD/adJ 6.8

### ISSUE THREAD

**Issue by vtamara** [bibletime/bibletime#310]
**Describe the bug**
I just ported BibleTime 3 to OpenBSD/adJ 6.8.  However it doesn't show the text of of the bible, although the text is there because when I move the mouse it shows the strong concordance, and I can copy and paste the text in an editor:

![prob-vis](https://user-images.githubusercontent.com/701221/112034139-2d407700-8b0c-11eb-8352-0356a3121845.jpg)

**To Reproduce**
1. On OpenBSD/adJ 6.8 compile the port of BibleTime available at: <https://github.com/pasosdeJesus/adJ/tree/adJ_6_8_bibletime_3/arboldes/usr/ports/mystuff/textproc/bibletime>
2. Run `bibletime`
3. Install any Bible and try to see its text

**Expected behavior**
Being able to see the text as it is possible with BibleTime 2.11.2, on OpenBSD/adJ 6.8  (port available at https://github.com/pasosdeJesus/adJ/tree/ADJ_6_8/arboldes/usr/ports/mystuff/textproc/bibletime ):

![bibletime2-11-2](https://user-images.githubusercontent.com/701221/112034735-cb344180-8b0c-11eb-94bf-555357943d07.jpg)

**Screenshots**
Included

**System information (please complete the following information):**
 - OS and OS version: OpenBSD/adJ 6.8
 - BibleTime Version 3.0
 - How BibleTime was installed: from source following compilation instructions of the port's Makefile: https://github.com/pasosdeJesus/adJ/blob/adJ_6_8_bibletime_3/arboldes/usr/ports/mystuff/textproc/bibletime/Makefile
 - Versions of modules related to the crash (if known): any
 - (If compiled from source) Sword Version: 1.8.1
 - (If compiled from source) Qt Version: 5.13.2

**Additional context**

**Comment by gholmlund** [comment]
1. Can you try changing the "display styles" under Settings/Configure BibleTime.
2. Run "bibletime --debug" and it will output various messages. Please save this in a text file and attach it.

**Comment by vtamara** [comment]
2. Result of `bibletime --debug` just start and then quit:

```
% bibletime --debug   
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-vtamara'   
LOOKING UP LOCALE DIRECTORY...                                                  
Checking for provided SWConfig("sword.conf")...                                 
Checking working directory for sword.conf...          
Checking working directory for mods.conf...         
Checking working directory for mods.d...                                                                                                                        
Checking working directory ../library/ for mods.d...   
Checking $SWORD_PATH...                                                         
Parsing /etc/sword.conf:/usr/local/etc/sword.conf...              
Checking for /etc/sword.conf...                                                 
Checking for /usr/local/etc/sword.conf...                                       
Checking $ALLUSERSPROFILE/Application Data/sword/...                            
Checking $HOME/Library/Application Support/Sword/...
found (/home/vtamara/).                                                         
Checking /home/vtamara/ for mods.d...                                           
Checking home directory for ~/.sword...                                         
Checking for /home/vtamara/.sword/mods.conf...      
Checking for /home/vtamara/.sword/mods.d...
found.                                                                                                                                                          
LOOKING UP LOCALE DIRECTORY COMPLETE.                                           
LOOKING UP MODULE CONFIGURATION...                                              
Checking for provided SWConfig("sword.conf")...                   
Checking working directory for sword.conf...                                    
Checking working directory for mods.conf...                                     
Checking working directory for mods.d...                                        
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...                                                         
Parsing /etc/sword.conf:/usr/local/etc/sword.conf...                            
Checking for /etc/sword.conf...                                                 
Checking for /usr/local/etc/sword.conf...             
Checking $ALLUSERSPROFILE/Application Data/sword/...
Checking $HOME/Library/Application Support/Sword/...                                                                                                            
found (/home/vtamara/).                                                         
Checking /home/vtamara/ for mods.d...                                           
Checking home directory for ~/.sword...                                         
  Checking for /home/vtamara/.sword/mods.conf...                                
  Checking for /home/vtamara/.sword/mods.d...                                   
found.                                                                          
LOOKING UP MODULE CONFIGURATION COMPLETE.           
(BibleTime 3.0.0) Debug: return an empty key for 05624                          
(BibleTime 3.0.0) Debug: return an empty key for 05624                          
(BibleTime 3.0.0) Debug: return an empty key for 05624                          
(BibleTime 3.0.0) Debug: return an empty key for 05624

**Comment by vtamara** [comment]
1. Changing the "display styles" under Settings/Configure BibleTime.

Doesn't present change where the text should be presented.
I tried with HighContrast.css:

![style-highcontrast](https://user-images.githubusercontent.com/701221/112189190-c5546400-8bd1-11eb-8dc0-a8a0a9254504.jpg)

green.css

![style-green](https://user-images.githubusercontent.com/701221/112189335-e74de680-8bd1-11eb-9309-7069c4ac6dfa.jpg)

Crazy.css:

![style-crazy](https://user-images.githubusercontent.com/701221/112189599-2b40eb80-8bd2-11eb-920f-de903b9cb6dc.jpg)

**Comment by tsbockman** [comment]
> ```
> (BibleTime 3.0.0) Debug: return an empty key for 05624                          
> (BibleTime 3.0.0) Debug: return an empty key for 05624                          
> (BibleTime 3.0.0) Debug: return an empty key for 05624                          
> (BibleTime 3.0.0) Debug: return an empty key for 05624
> ```

I am also getting this error message, albeit [with different symptoms](https://github.com/bibletime/bibletime/issues/328). I figured out that `5624` is [the last Strong's Greek number](https://www.biblehub.com/strongs.htm), which seems like a useful clue to me...

**Comment by gholmlund** [comment]
I don't believe we have official support for OpenBSD. I note that Qt does not have official support. It only has community support.

However, I did install OpenBSD 6.9 (the latest) which has Qt 5.15.2. I compiled BibleTime 3.0 from source and tested it. It works correctly showing the text as expected in the text windows and in the MAG window.

I don't believe I can help further.
