### ISSUE TITLE
Clicking "Handbook" or "Bible Study Howto" doesn't do anything

### ISSUE THREAD

**Issue by CrawfordRD** [bibletime/bibletime#311]
I have just installed v3.0.0 on a Linux Mint PC. Overall, the software package seems to run well, but when I click "Help > Handbook" or "Help > Bible Study Howto", nothing happens. FYI, it was installed using Linux Mint's "Software Manager" application. Here are the details of the package from that application:
    Details (Flatpak)
    Package: infor.bibletime.BibleTime
    Version 3.0.0
    Size: 87.2 MB of disk space freed
    Flathub
    Architecture: x86_64
    Branch: stable

Thank you for your hard work on this application.

**Comment by jaakristioja** [comment]
Thanks for reporting this! If you need to access the documentation right away, please see https://bibletime.info/generated_docs/

**Comment by gholmlund** [comment]
I reproduced the problem on ubuntu 20.04 with a flatpak of BibleTime. It may be a few days before I can investigate further.

**Comment by gholmlund** [comment]
Reproduced with a simple qt gui program. I found it is a Qt bug.
https://bugreports.qt.io/browse/QTBUG-81597

**Comment by gholmlund** [comment]
Closing because the problem is in Qt
