### ISSUE TITLE
[BUG] BibleTime 2.11.1 on Ubuntu 18.04: Could not find QtWebEngineProcess

### ISSUE THREAD

**Issue by Coolwater357** [bibletime/bibletime#312]
bibletime installed from Ubuntu packages

Running bibletime results in:
(BibleTime 2.11.1) FATAL: Could not find QtWebEngineProcess
****Please report this bug at https://github.com/bibletime/bibletime/issues****
Abort (core dumped)

04-10T13:22:30 33> uname -a
Linux 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

04-10T13:24:29 34> bibletime --debug
LOOKING UP LOCALE DIRECTORY...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP LOCALE DIRECTORY COMPLETE.
LocaleMgr::loadConfigDir loading /usr/share/sword/locales.d
LOOKING UP MODULE CONFIGURATION...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP MODULE CONFIGURATION COMPLETE.
(BibleTime 2.11.1) FATAL: Could not find QtWebEngineProcess
Please report this bug at https://github.com/bibletime/bibletime/issues
Abort (core dumped)

04-10T13:30:39 39> apt search QtWebEngine
Sorting... Done
Full Text Search... Done
libqt5webengine-data/bionic,bionic,now 5.9.5+dfsg-0ubuntu2 all [installed,automatic]
  Web content engine library for Qt - Data

libqt5webengine5/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed,automatic]
  Web content engine library for Qt

libqt5webenginecore5/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed,automatic]
  Web content engine library for Qt - Core

libqt5webenginewidgets5/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed,automatic]
  Web content engine library for Qt - Widget

python-pyqt5.qtwebengine/bionic 5.10.1+dfsg-1ubuntu2 amd64
  Python 2 bindings for Qt5's WebEngine module

python-pyqt5.qtwebengine-dbg/bionic 5.10.1+dfsg-1ubuntu2 amd64
  Python 2 bindings for Qt5's WebEngine module (debug extensions)

python3-pyqt5.qtwebengine/bionic,now 5.10.1+dfsg-1ubuntu2 amd64 [installed]
  Python 3 bindings for Qt5's WebEngine module

python3-pyqt5.qtwebengine-dbg/bionic 5.10.1+dfsg-1ubuntu2 amd64
  Python 3 bindings for Qt5's WebEngine module (debug extensions)

qml-module-qtwebengine/bionic,now 5.9.5+dfsg-0ubuntu2 amd64 [installed,automatic]
  Qt WebEngine QML module

qtwebengine5-dev/bionic 5.9.5+dfsg-0ubuntu2 amd64
  Web content engine library for Qt - development files

qtwebengine5-dev-tools/bionic 5.9.5+dfsg-0ubuntu2 amd64
  Qt WebEngine tools

qtwebengine5-doc/bionic,bionic,now 5.9.5+dfsg-0ubuntu2 all [installed,automatic]
  Qt 5 webengine documentation

qtwebengine5-doc-html/bionic,bionic 5.9.5+dfsg-0ubuntu2 all
  Qt 5 webengine HTML documentation

qtwebengine5-examples/bionic 5.9.5+dfsg-0ubuntu2 amd64
  Qt WebEngine - Examples

qtwebengine5-private-dev/bionic 5.9.5+dfsg-0ubuntu2 amd64
  Web content engine library for Qt - private development files

**Comment by jaakristioja** [comment]
This seems to be an issue with Ubuntu packages Qt and/or BibleTime. I suggest you file a bug to Ubuntu about this.

As for a workaround, you can try to run BibleTime with the `QTWEBENGINEPROCESS_PATH` environment variable set to `/usr/lib/x86_64-linux-gnu/qt5/libexec/`. Also ensure that the `libqt5webenginecore5` package is properly installed, and reinstall it if necessary.


PS: The BibleTime team no longer officially supports BibleTime 2.11.1.
