### ISSUE TITLE
Search not finding word

### ISSUE THREAD

**Issue by jimarruk** [bibletime/bibletime#313]
Hello, 

I have recently downloaded and installed linux mint and bibletime.  I must say im very impressed with bibletime its simplicity yet very useful features. 
I have the KJV bible uploaded with the TSK. 

I was searching the word 'mark' and knew that genesis 4.15 should have returned a search but it was null.  Then i searched 'cain' the search module highlights 'Cain' in yellow in Genesis ch 4 v16, 17 and 22 however in the 'Results' box there is no reference to Genesis 4.15 only 4.16,17 and 22. Then i searched 'vengeance' which is in Gen 4. 15 again null both in the main verse box and results the first reference being found is Deuteronomy 32.35.
Am i doing something wrong?
Is this only Gen 4.15?
Are there other verses this occurs with?

Thanks for any help.
Btw i really think this software is great i linked the TSK, the amount of cross references is brilliant..
James

**Comment by gholmlund** [comment]
I have tried to reproduce this in ubuntu 20.04 with BibleTime 2.11 and Fedora 33 with BibleTime 3.0. Both cases found the search word in the places listed above.

I would suggest rebuilding the search indexes. At the bottom of the Search dialog press the "Manage Indexes" button. Put a check on KJV and press Delete.
