### ISSUE TITLE
where the works(books) I downloaded to bookshelf  located in Mac Finder

### ISSUE THREAD

**Issue by aaron2wh** [bibletime/bibletime#315]
anybody can tell me the location? thanks

**Comment by sisco0** [comment]
Should it be the location stated by these lines?
https://github.com/bibletime/bibletime/blob/bbb26d2050d3b5a8de2109b3a6233efa0b12fa3f/src/util/directory.cpp#L70-L71

**Comment by gholmlund** [comment]
The directories above are correct, assuming you are starting from your home directory.
