### ISSUE TITLE
Mag viewer made unusable in BT version 3

### ISSUE THREAD

**Issue by 3chel0n** [bibletime/bibletime#316]
When using the King James Bible ("KJV" in the bookshelf manager) and hovering over a word, the word's definition from original Greek or Hebrew word will appear in the mag viewer.  Many of these definitions are larger than the mag viewer, requiring scrolling within the mag viewer to see the entire definitions.  This was no problem in previous BT versions because one could simply quickly move the mouse from the word of interest over to the mag viewer and scroll within the mag viewer as necessary to see the entire definitions.

However, as of BT version 3, the instant the mouse is moved away from the word of interest, the content within mag viewer changes (seemingly randomly) to a definition of a word of non-interest.  This ensures that a reader cannot see an entire definition of a word of interest in the mag viewer.

I'm aware that I can add Strong's Greek and Hebrew widgets to my window (Open work -> Lexicons and Dictionaries), watch the mag viewer for the Strong's numbers for words of interest over which I hover with my mouse, and then manually search the widgets for those numbers.  However, study is **immensely** slowed in such manner because of the extra time required to find each word, because of the neuro-linguistic pattern interruptions that necessitate re-reading verses multiple times to regain interrupted train of thought, and because such method is error-prone due to mis-typed numbers, etc.

Based on the foregoing, the mag viewer has been transformed from a wonderful, very important tool to being completely unusable.

**Comment by tuxuser06** [comment]
same problem here

**Comment by jaakristioja** [comment]
Please try holding down the <kbd>shift</kbd> key while moving mouse from the word to the Mag viewer.

Note that the Mag view [holds the following text](https://github.com/bibletime/bibletime/blob/1054b57dff316f1a50f391316efa62019b495669/src/frontend/cinfodisplay.cpp#L86-L92) if not currently displaying any other information (emphasis mine):

> This is the Mag viewer area. Hover the mouse over links or other items which include some data and the contents appear in the Mag after a short delay. Move the mouse into Mag rapidly or **lock the view by pressing and holding Shift while moving the mouse**.

Closing this as invalid. Please reopen if this does not work for you. I also filed bug #318 to improve BibleTime documentation on this matter.

**Comment by gholmlund** [comment]
The 3.0 Mag experience is worse that 2.11. If you hover over a reference the text appears in the Mag window. And then if you smoothly move to the Mag window the reference should not change. In 3.0 it does change again once you enter the Mag window. This forces you to use the shift key which should not be necessary.
Reopening.

**Comment by gholmlund** [comment]
I checked in a fix that makes 3.0 work as it did in 2.11

**Comment by jaakristioja** [comment]
For historical reference, the related commits were ddddf067f96e8e822ecc2957d54c97a9d41e718c in the stable-3.0 branch, and 2929e30c9c4af2cab44043c2c4ad78a10588fe53 in the master branch.
