### ISSUE TITLE
BIBdraft does not display anything but verse and chapter numbers. No verse text. BSBdraft is okay.[BUG] 

### ISSUE THREAD

**Issue by n5edd** [bibletime/bibletime#319]
**Describe the bug**
A clear and concise description of what the bug is. Please only describe one issue per bug report.

**To Reproduce**
1. Go to '.BIBLES'
2. Click on 'English'
3. Scroll down to 'BIBdraft'
4. Panel opens without verse text

**Expected behavior**
Panel opens with full verse text
**Screenshots**

**System information (please complete the following information):**
 - OS and OS version: Windows 10 Pro (20H2) 64bit
 - BibleTime Version: 3.0.0
 - How BibleTime was installed:  installer
 - Versions of modules related to the crash: 0.01
 - (If compiled from source) Sword Version: N/A
 - (If compiled from source) Qt Version: N/A
 -

**Additional context**
Removed and reloaded but no joy. NT or OT, the same result.

![BIBdraft](https://user-images.githubusercontent.com/48558225/118836442-76514500-b889-11eb-8f7b-ac1dc1f36a66.png)
![BIBdraft2](https://user-images.githubusercontent.com/48558225/118837349-540bf700-b88a-11eb-81ff-bb5968ca3304.png)

**Comment by jaakristioja** [comment]
I can confirm this on Linux as well. For a split second I think I saw it display some Hebrew text (aligned left), but then it disappeared.

**Comment by gholmlund** [comment]
Fails to display on BibleTime 3.0 and 2.11.
Displays correctly on Xiphos

I have traced it to an issue with ThmlToHtml::processText.

**Comment by n5edd** [comment]
Thank you for looking at this. I don't code so it was beyond me.

**Comment by gholmlund** [comment]
Fixed. This fix is for ThML modules with mixed <sync> and <span> tags.

**Comment by n5edd** [comment]
Please excuse me but I'm not really that tech savvy. Do I have to grab your updated module and rebuild the package, or wait for the updated BibleTime app? Thanks.

**Comment by gholmlund** [comment]
Building the stable source is the only current option. Doing this on Windows does require technical knowledge. I think you will need to wait for a BibleTime release.

**Comment by jaakristioja** [comment]
We will hopefully release 3.0.1 soon.

**Comment by n5edd** [comment]
Thank you.
 
 
 
-----Original Message-----

**Comment by n5edd** [comment]
Thank you. 
 
 
 
-----Original Message-----

**Comment by n5edd** [comment]
I noticed in Xiphos, the BIB Hebrew text is left to right instead of right to left. Is that going to be changed?
 
 
 
-----Original Message-----

**Comment by n5edd** [comment]
Err, I meant, is it going to be changed in BT.
 
-----Original Message-----

**Comment by jaakristioja** [comment]
@n5edd I'm not sure I understand. If this is another issue with BibleTime, please feel to report a new bug. Thanks! :-)

**Comment by gholmlund** [comment]
The right to left direction is specified in the module, not in BibleTime. Since the BIBdraft has both Hebrew(RTL) and Greek(LTR) it cannot display both correctly. There is nothing BibleTime can do about this.

**Comment by n5edd** [comment]
Okay
 
-----Original Message-----

**Comment by n5edd** [comment]
Okay, thank you.
 
 
-----Original Message-----
