### ISSUE TITLE
[BUG] Test suite: Several tests fail if bibletime has not been installed

### ISSUE THREAD

**Issue by mkszuba** [bibletime/bibletime#320]
**Describe the bug**

In spite of what the test README says, all tests except _btlistmodel_fail unless Bibletime has already been installed to standard system locations, with _initTestCase_ reporting

`QWARN  : test_BtInstallThread::initTestCase() Cannot find documentation directory relative to ":"`
`FAIL!  : test_BtInstallThread::initTestCase() 'util::directory::initDirectoryCache()' returned FALSE. ()`

in either case. With Bibletime already installed, _btinstallthread_ fails but in a different way and all other tests pass.

**To Reproduce**

1. Make sure all Bibletime dependencies are available but Bibletime itself is not
2. Unpack the source tarball, create build directory, run cmake, compile
3. Run the test suite

**Expected behavior**

All tests pass.

**System information (please complete the following information):**
 - Gentoo Linux on amd64
 - BibleTime 3.0.0, compiled from source code
 - Sword version 1.9.0
 - Qt version 5.15.2

**Additional context**

Attaching the relevant test log.
[bibletime-tests_require_installation.log](https://github.com/bibletime/bibletime/files/6546156/bibletime-tests_require_installation.log)

**Comment by jaakristioja** [comment]
Yes, this is a known issue. Unfortunately nobody has time to fix things like that. Tests like that should probably be removed or perhaps be moved to some Docker containers. It's all just a big mess and we haven't yet figured out what would be the best path ahead on this, it has not been a priority. ;-(

We apologize for any confusion this has caused.

**Comment by jaakristioja** [comment]
I just removed all tests with d05797db79074c526987329dff78d89eef8c501c.
