### ISSUE TITLE
[BUG] Test suite: failures in BtInstallThread::installModules

### ISSUE THREAD

**Issue by mkszuba** [bibletime/bibletime#321]
**Describe the bug**

While running the Bibletime-3.0.0 test suite, _BtInstallThread::installModules_ fails. This happens both when I run the test suite via a Gentoo package manager (i.e. with restricted permissions) and when I run it manually as an ordinary (non-root) user; the error messages are different in both cases but they appear in the same place.

**To Reproduce**

1. Make sure both Bibletime dependencies have already been installed, in order to work around Issue #320
2. Unpack the source tarball, create build directory, run cmake, compile
3. Run the test suite

**Expected behavior**

All tests pass.

**System information (please complete the following information):**
 - Gentoo Linux on amd64
 - BibleTime 3.0.0, compiled from source code
 - Sword version 1.9.0
 - Qt version 5.15.2

**Additional context**

Attaching the relevant test logs, from both a sandboxed and a normal run.

[bibletime-btinstallthread_abort-sandbox.log](https://github.com/bibletime/bibletime/files/6546259/bibletime-btinstallthread_abort-sandbox.log)
[bibletime-btinstallthread_abort-manual.log](https://github.com/bibletime/bibletime/files/6546260/bibletime-btinstallthread_abort-manual.log)

**Comment by jaakristioja** [comment]
As I just noted in #320, the tests have largely been orphaned. I just dropped them all with d05797db79074c526987329dff78d89eef8c501c.
