### ISSUE TITLE
[QUESTION] Prolog of Personal note can be inserted ?

### ISSUE THREAD

**Issue by Gwang-Jin** [bibletime/bibletime#322]
**Background**
I am using crosswire personal note in BibleTime.
And I found that there is a space box in Luke 15:0.

**Question**
Is it possible to insert my prolog in Luke 15:0 ?

Thank you.

**Comment by jaakristioja** [comment]
This indeed appear to be possible, but for some reason, et does not seem to work properly. There is indeed a box, and it is clickable, but it does not have a "Click to edit" placeholder. When I click and edit, it does not display the text, but when I click to edit again, the edit dialog displays the text I entered earlier.

**Comment by gholmlund** [comment]
Using Revelation 2:0 as an example, it seems that the text entered in Rev 2:0 also appears in Rev 1:20. Or text entered in Rev 1:20 and it appears in Rev 2:0. The diatheke utility also shows this:

$ diatheke -b Personal -k "Revelation 1:20"
Revelation of John 1:20: Rev  2:0
(Personal)

$ diatheke -b Personal -k "Revelation 2:0"
Revelation of John 1:20: Rev  2:0
(Personal)

$ diatheke -b Personal -k "Revelation 2:1"
Revelation of John 2:1: Rev  2:1
(Personal)

I don't believe BibleTime can fix this. We can make Rev 2:0 non editable.

**Comment by gholmlund** [comment]
I debugged into sword far enough that I know it does not support verse 0 entries on the Personal commentary. I have made the verse 0 entries non-editable.

**Comment by jaakristioja** [comment]
> I have made the verse 0 entries non-editable.

This was commit 1f235c0cc396b0bf2bef5758bef974768f42246e in master and 46ce64fddb6b4e96c44232b7f22ccf92a0988b54 in the stable-3.0 branch.
