### ISSUE TITLE
Remove Scofield

### ISSUE THREAD

**Issue by parker5** [bibletime/bibletime#323]
Cyrus I. Scofield of "Scofield Reference Bible" fame was a complete fraud.  He had neither the gift of teaching and preaching nor the scholarship to comment on the Holy Scriptures.  At the very best his demonic "interpretations" were ghost written by others determined to lead the faithful astray.  The Scofield Reference Bible has led many astray and should be removed or at least put with all haste into the cults and unorthodox section.

**Comment by jaakristioja** [comment]
Thank you for reporting this. It is good to know of these concerns, but please back it up with sufficient proof as well.

BibleTime is just a front-end and our team does not provide works like this by themselves. Works come from remote libraries like Bible.org, Crosswire, Deutsche Bibelgesellschaft, IBT, Lockman Foundation, Xiphos and eBible.org. Please contact the distributor of the work (it probably came from the Crosswire) about this.
