### ISSUE TITLE
Cursor size changing 

### ISSUE THREAD

**Issue by ArnoVersfeld** [bibletime/bibletime#325]
**Describe the bug**
**I use Ubuntu 20.04 where I am able to chose a larger than standard cursor size. Under Settings/Universal Access/Cursor Size I have chosen Large. When I ope BibleTime and move the cursor over the app the cursor size always reverts to the default size which is small.**

**To Reproduce**
**Steps to reproduce the behavior:
1. Go to 'Favourites and launch BibleTime'
2. Move 'the cursor over BibleTime app'
3. The cursor immediately reverts to the default small size**

**Expected behavior**
**The cursor should remain the same size selected under settings on Ubuntu.**

**Screenshots**
**Cannot take screen shot.**

**System information (please complete the following information):**
 - OS and OS version: [Ubuntu 20.04, GNOME version 3.36.8]
 - BibleTime Version [3.0.0]
 - How BibleTime was installed [Snap install ]
 - Versions of modules related to the crash (NO crash)
 - (If compiled from source) Sword Version - n/a
 - (If compiled from source) Qt Version - n/a

**Additional context**
None

**Comment by gholmlund** [comment]
I tried this on Ubuntu 20.04 with a snap BibleTime 3.0. When BibleTime is running and I change the cursor size, it does not change when the cursor is over BibleTime.  However, When I changed the cursor size before starting BibleTime, it always had the correct cursor size over BibleTime.  I think this is reasonable behavior.

**Comment by jaakristioja** [comment]
This sounds reasonable to me as well. Closing this issue.

If this still does not work for you, I would suspect this to be a problem with snap packaging or Gnome/Qt interoperability.
