### ISSUE TITLE
Copy text disabled after update to Bible Time 3.0.1

### ISSUE THREAD

**Issue by Greg-Supina** [bibletime/bibletime#334]
Since my update to Bible Time 3.0.1, I cannot use the mouse to select any text in main window and cannot copy anything to the buffer in the usual way. Now Bible Time auto highlights the verse in the selection box above the main window, and in all the open modules simultaneously. This prevents the user from highlighting any other text anywhere in main window. And the user cannot even copy that auto-highlighted text to the buffer. The only way to copy any text to the buffer is by using Ctrl-R ("Copy by references"), indicating the desired range of verses and the module, then clicking on the OK button.

![BibleTime](https://user-images.githubusercontent.com/65780823/128613747-083e79e3-cfe0-4586-9264-c0e89fb19dc9.png)

Bible Time 3.0.1
Snap
Ubuntu 20.04 (focal)
Desktop with I7 processor (old 950@3.07 GHz) and with 16 Gigs Ram.

**Comment by gholmlund** [comment]
I can confirm the bug. It happened because select and deselect used a function that was introduced in Qt 5.13.0. The snap uses Qt 5.12.8. 
DisplayView.qml - line 184, line 194

**Comment by ArnoVersfeld** [comment]
I have also found the same problem. When I use the the "Search" function the selection and copy process works as it should on the found data.
![image](https://user-images.githubusercontent.com/33600932/128661864-8546db26-8462-4adb-83d3-e68df082bdd7.png)

**Comment by gholmlund** [comment]
Fixed and tested with Qt 5.9.9 and 5.15.2.

**Comment by gholmlund** [comment]
I updated the snap with a patch for this issue. Please update your snap.
