### ISSUE TITLE
Several opened Bibles

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#338]
When I have several Bibles opened to own windowses and then I search some new verse on one of them, I want that the other windowses moves to that new verse too.

And if someone has other books like commentaries or other stuff, they shall not move. Only Bibles. And if someone has Bibles in several language, maybe they could change to new verse.

**Comment by jaakristioja** [comment]
I doubt something exactly like that would work out well, especially from an UI design perspective. I'd rather add the ability to sync windows manually, e.g. by drag-and-drop.

The current alternative to make works move in sync is to open several works in one window in parallel.
