### ISSUE TITLE
[ENHANCEMENT] Add dark mode (I'm assuming for linux version)

### ISSUE THREAD

**Issue by doonoo** [bibletime/bibletime#339]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I find it difficult to [...]
No. Isn't a problem... Well for my eyes that os.

**Describe the solution you'd like**
The ability to read this at night.
**Describe alternatives you've considered**
just using kingjamesbibleonline.org and dark reader. Or still use this.
**Additional context**
Can this support GTK?

**Comment by jaakristioja** [comment]
> The ability to read this at night.

You can try to use the other display templates under Settings -> Configure BibleTime -> Display -> Available display styles. Perhaps a darker display style like HighContrast.css will provide a valid workaround.

Or do you mean the styling of UI elements like buttons/menus/widgets?

> Can this support GTK?

What do you mean? I know KDE has provided means to change the style of GTK applications from withing KDE settings. Perhaps other desktop environments also provide means to change the style of Qt applications like BibleTime? If not, perhaps using tools like qt5ct might help.

**Comment by doonoo** [comment]
![09h_12m_20s_01_September_2021](https://user-images.githubusercontent.com/18385494/131677491-650aaffb-2f53-4c78-bf3e-d69621cb05b5.png)
I might need to say I am using Wayland also, so that could be the problem.

**Comment by doonoo** [comment]
> What do you mean? I know KDE has provided means to change the style of GTK applications from withing KDE settings. Perhaps other desktop environments also provide means to change the style of Qt applications like BibleTime? If not, perhaps using tools like qt5ct might help.

This fixed it, thanks!

![Uploading 09h_21m_58s_01_September_2021.png…]()

**Comment by gholmlund** [comment]
I added a configuration dialog setting that lets you choose light or dark mode or to use the operating system default.
