### ISSUE TITLE
How do I compile bibletime without the documentaton stuff,

### ISSUE THREAD

**Issue by FrostKnight** [bibletime/bibletime#342]
I keep trying to build without the pdf stuff, aka this: https://github.com/bibletime/bibletime#documentation-generation-requirements-optional

-- Using CMake 3.16.3: /usr/bin/cmake
-- Setting up build environment for BibleTime version 3.0.2
-- Found CLucene library: /usr/lib/libclucene-core.so
-- Found CLucene include dir: /usr/include
-- Found CLucene library dir: /usr/lib
-- Found CLucene shared library: /usr/lib/libclucene-shared.so
-- Found CLucene: /usr/lib/libclucene-core.so;/usr/lib/libclucene-shared.so
CMake Warning at cmake/FindSword.cmake:67 (MESSAGE):
  Falling back to manual Sword detection...
Call Stack (most recent call first):
  cmake/BTApplication.cmake:17 (FIND_PACKAGE)
  CMakeLists.txt:210 (INCLUDE)

-- Sword 1.9.0 details:
--     CFLAGS: -I/usr/local/include/sword
--       INCLUDE_DIRS: /usr/local/include/sword
--       CFLAGS_OTHER: 
--     LDFLAGS: -L/usr/local/lib;-lsword
--       LIBRARIES: sword
--       LIBRARY_DIRS: /usr/local/lib
--       LDFLAGS_OTHER: 
-- Interprocedural optimization support: YES
CMake Error at cmake/BTDocumentation.cmake:48 (MESSAGE):
  Required program "po4a" not found!
Call Stack (most recent call first):
  cmake/BTDocumentation.cmake:53 (FIND_REQUIRED_PROGRAM)
  CMakeLists.txt:216 (INCLUDE)

-- Configuring incomplete, errors occurred!
See also "/home/localuser/Downloads/bibletime-3.0.2/build/CMakeFiles/CMakeOutput.log".

The above is the result, no matter what I do, 
Even with this option added to cmake.

-DBUILD_HOWTO_PDF=OFF 

Can you tell me what I am doing wrong?

It's kind of frustrating...

**Comment by jaakristioja** [comment]
Please note that in [the documentation](https://github.com/bibletime/bibletime#documentation-generation-requirements-optional) `-DBUILD_HOWTO_PDF=OFF` was just given as one specific example about how to use any of the aforementioned options. I suspect that the error you are seeing might result from only passing `-DBUILD_HOWTO_PDF=OFF` to the CMake executable. Did you also pass any other `-DBUILD_<something>_<something>=OFF` arguments to CMake? Please post the complete `cmake` command line you used to produce this output.

**Comment by FrostKnight** [comment]
So what I gathered is that I had to do this:

 cmake . -DBUILD_HOWTO_PDF=OFF -DBUILD_HANDBOOK_HTML=OFF -DBUILD_HOWTO_PDF=OFF -DBUILD_HOWTO_HTML=OFF

I see now, I have to do all four options at the same time...

cd build in the bibletime folder then cmake .  with the four above options, 
make 
and sudo make install

You may want to mention though, to build without documentation, you have to run all four of those options.
Can you add this to your wiki?

This issue seems to be solved. :)

**Comment by jaakristioja** [comment]
This is documented in the README.md. With commit 1e72c3949ad16a4526b327000ae391b22fb3a96b the defaults are now explicitly listed with each option.

**Comment by FrostKnight** [comment]
Thank you for doing so, appreciated.
