### ISSUE TITLE
[BUG] Crash trying to open any text from Bookshelf

### ISSUE THREAD

**Issue by kthenrique** [bibletime/bibletime#343]
**Bug description**
I've just built 'master' and downloaded some works using the prompt of Bookshelf Manager at start-up. Trying to open any of the downloaded works crashes.

**Steps to reproduce**
1. build master with cmake 
2. Download some works with the Bookshelf Manager at start-up
3. double-click one of the works downloaded.
4. See error:

> (BibleTime 3.1.0_dev+5011661be0761c18bb6ccdd680397cc3e4ebf7ec) WARNING: qrc:/qml/DisplayView.qml:325:19: Type DisplayDelegate unavailable
> (BibleTime 3.1.0_dev+5011661be0761c18bb6ccdd680397cc3e4ebf7ec) WARNING: qrc:/qml/DisplayDelegate.qml:23:14: Expected token `:'
> (BibleTime 3.1.0_dev+5011661be0761c18bb6ccdd680397cc3e4ebf7ec) WARNING: QObject::connect(BtQmlInterface, BtQmlScrollView): invalid null parameter
> bibletime: $HOME/bibletime/src/frontend/display/modelview/btqmlscrollview.cpp:69: BtQmlScrollView::BtQmlScrollView(QWidget*, BtModelViewReadDisplay*)::<lambda()>: Assertion `r' failed.
> Aborted (core dumped)

**Expected behavior**
The work selected displayed on main canvas.

**System information:**
 - OS and OS version: Ubuntu 20.04.3 LTS
 - BibleTime Version: 'master' - commit 5011661be
 - How BibleTime was installed: compiled from source code
 - Versions of modules related to the crash
 - (If compiled from source) Sword Version: 1.9.0
 - (If compiled from source) Qt Version: 5.12.8

**Additional context**

- Output of `bibletime --debug`:

> ❯ ./install/bin/bibletime --debug
LOOKING UP LOCALE DIRECTORY...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /usr/local/etc/sword.conf...
Checking for /usr/local/etc/sword.conf...
found.
DataPath in /usr/local/etc/sword.conf is set to /usr/local/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP LOCALE DIRECTORY COMPLETE.
LocaleMgr::loadConfigDir loading /usr/local/share/sword/locales.d
LOOKING UP LOCALE DIRECTORY...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /usr/local/etc/sword.conf...
Checking for /usr/local/etc/sword.conf...
found.
DataPath in /usr/local/etc/sword.conf is set to /usr/local/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP LOCALE DIRECTORY COMPLETE.
LocaleMgr::loadConfigDir loading /usr/local/share/sword/locales.d
LOOKING UP MODULE CONFIGURATION...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /usr/local/etc/sword.conf...
Checking for /usr/local/etc/sword.conf...
found.
DataPath in /usr/local/etc/sword.conf is set to /usr/local/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP MODULE CONFIGURATION COMPLETE.
LOADING MODULE CONFIGURATIONS...
LOADING MODULE CONFIGURATIONS COMPLETE.
LOADING MODULE LIBRARY...
libsword: SWMgr::createAllModules
libsword: SWMgr::createAllModules
LOADING MODULE LIBRARY COMPLETE.
(BibleTime 3.1.0_dev+5011661be0761c18bb6ccdd680397cc3e4ebf7ec) WARNING: qrc:/qml/DisplayView.qml:325:19: Type DisplayDelegate unavailable
(BibleTime 3.1.0_dev+5011661be0761c18bb6ccdd680397cc3e4ebf7ec) WARNING: qrc:/qml/DisplayDelegate.qml:23:14: Expected token `:'
(BibleTime 3.1.0_dev+5011661be0761c18bb6ccdd680397cc3e4ebf7ec) WARNING: QObject::connect(BtQmlInterface, BtQmlScrollView): invalid null parameter
bibletime: $HOME/bibletime/src/frontend/display/modelview/btqmlscrollview.cpp:69: BtQmlScrollView::BtQmlScrollView(QWidget*, BtModelViewReadDisplay*)::<lambda()>: Assertion `r' failed.
Aborted (core dumped)

- Backtrace:

> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7dd1859 in __GI_abort () at abort.c:79
#2  0x00007ffff7dd1729 in __assert_fail_base (fmt=0x7ffff7f67588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555556b70b9 "r", 
    file=0x5555556cf290 "$HOME/bibletime/src/frontend/display/modelview/btqmlscrollview.cpp", line=69, function=<optimized out>) at assert.c:92
#3  0x00007ffff7de2f36 in __GI___assert_fail (assertion=0x5555556b70b9 "r", file=0x5555556cf290 "$HOME/bibletime/src/frontend/display/modelview/btqmlscrollview.cpp", line=69, 
    function=0x5555556d08e0 <BtQmlScrollView::BtQmlScrollView(QWidget*, BtModelViewReadDisplay*)::{lambda()#2}::operator()() const::__PRETTY_FUNCTION__> "BtQmlScrollView::BtQmlScrollView(QWidget*, BtModelViewReadDisplay*)::<lambda()>") at assert.c:101
#4  0x0000555555668b9f in BtModelViewReadDisplay::BtModelViewReadDisplay(CDisplayWindow*, QWidget*) ()
#5  0x0000555555653a6c in CDisplayWindow::initView() ()
#6  0x0000555555655879 in CBibleReadWindow::initView() ()
#7  0x00005555556a1154 in BibleTime::createReadDisplayWindow(QList<CSwordModuleInfo*>, QString const&) ()
#8  0x00005555556a18b1 in BibleTime::createReadDisplayWindow(CSwordModuleInfo*, QString const&) ()
#9  0x00005555556894d3 in QtPrivate::QFunctorSlotObject<BibleTime::initConnections()::{lambda()#2}::operator()() const::{lambda(CSwordModuleInfo*)#1}, 1, QtPrivate::List<CSwordModuleInfo>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) [clone .lto_priv.1119] ()
#10 0x00007ffff64a0458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00005555556a3c32 in BtBookshelfDockWidget::moduleOpenTriggered(CSwordModuleInfo*) ()
#12 0x0000555555670d1c in QtPrivate::QFunctorSlotObject<BtBookshelfDockWidget::BtBookshelfDockWidget(QWidget*, QFlags<Qt::WindowType>)::{lambda()#1}::operator()() const::{lambda(CSwordModuleInfo*)#1}, 1, QtPrivate::List<CSwordModuleInfo>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) [clone .lto_priv.1467] ()
#13 0x00007ffff64a0458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00005555556a37d2 in BtBookshelfView::moduleActivated(CSwordModuleInfo*) ()
#15 0x00007ffff64a0458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff7a52329 in QAbstractItemView::activated(QModelIndex const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff7acc6ce in QTreeView::mouseDoubleClickEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff782e86b in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff78dbd52 in QFrame::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7a60482 in QAbstractItemView::viewportEvent(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff7ace62f in QTreeView::viewportEvent(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff647464b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff77eba55 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff77f5343 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff647493a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff77f4457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff784a35d in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff784d1ec in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff77eba66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff77f50f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff647493a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff685d71c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#33 0x00007ffff685f10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#34 0x00007ffff683935b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007ffff297432e in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#36 0x00007ffff4f7a17d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff4f7a400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff4f7a4a3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff64cc565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007ffff64734db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff647b246 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00005555555ce64f in main ()

**Comment by jaakristioja** [comment]
Thank you for reporting this issue. It seems to be caused by the required properties introduced by commit 7be35f896b8012c2a199d5d1c2d261d7c39fa29f. However, these require Qt 5.15 or later, so I had to bump the Qt version requirement in the master branch (commit 90e1bb77be12865af885a9c02f8d8ae83dafcf16), because we currently lack the resources to support older versions of Qt.

Note that Ubuntu 20.04 ships with Qt 5.12, so you would probably have to install Qt 5.15 or newer from somewhere else, e.g. from [this PPA](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.2-focal).
