### ISSUE TITLE
Can't run version 3 in Kubuntu 20.04. Can not upgrade. 

### ISSUE THREAD

**Issue by descendingnerdliness** [bibletime/bibletime#344]
After upgrading to Kubuntu 20.04.3 from 18.04, I could no longer run Bibletime 2.9, as it produced an error wanting libsword 1.8. I installed Bibletime 3.0 from its repo and it fails to run for the same reason. Seeing that release 3.02 is almost a month old and reports over 800 subsequent commits I decided that if I had to compile it, I might as well compile the repo version. Then I noticed the qt version. The latest version of QT in the Kubuntu 20.04 repo is 5.12.8. I know it is unheard of in the open source community, but please do us a favor and maintain compatibility with the at least the latest LTS OS release. Many thanks.

**Comment by gholmlund** [comment]
BibleTime 3.0.x compiles and runs well on ubuntu 20.04 with Qt 5.12.8 and Sword 1.8.1.

Where did you get the source? Github clone? Did you check out the stable-3.0 branch?

NOTE: snap and flatpak installs are available.

**Comment by descendingnerdliness** [comment]
Actually, I saw  in the file listing that QT 5.15 had been made the minimum and did not try to compile it. If you say that it will work, I will 'git clone' it and give it a shot. However, Sword came in at 1.9.0.

**Comment by gholmlund** [comment]
I believe the listing you are referring to is the git log for the master version. I just checked the source for Bt 3.0.2 and the min Qt version  is 5.9. I have compiled with Qt 5.9 recently.

**Comment by jaakristioja** [comment]
It is absolutely not "unheard of in the open source community", but we don't have any plans to support Kubuntu 20.04 in our master branch at this time. It's just that we are a very small team of volunteers (perhaps also with busy lives) and don't currently have the resources to provide this level of support. I'm not ruling out longer support cycles in the future should our team grows or we get hired to work on BibleTime. :-)

Closing, as the stable-3.0 branch of BibleTime from this git repository should (at least in theory) build and run as expected on Kubuntu 20.04. Please reopen if it does not.
