### ISSUE TITLE
Ubuntu installation instructions on website need to be updated

### ISSUE THREAD

**Issue by DavidGamba** [bibletime/bibletime#35]
Hi guys,

When I go here: http://bibletime.info/en/download it tells me to install using the ubuntu PPA: https://launchpad.net/~pkgcrosswire/+archive/ubuntu/ppa but that PPA hasn't had any activity since April 2012.

**Comment by mgruner** [comment]
Hello, this will be fixed on the new homepage at https://bibletime.github.io which is supposed to go live sometime soon. Thanks and best regards,
Martin
