### ISSUE TITLE
[BUG] Search for Strong number in OSHB shows nothing 

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#372]
When using the OSHB module, I click on a work for a strong research, but nothing appears as result of the strong research.

Same problem on [xiphos](https://github.com/crosswire/xiphos/issues/1107)

**Comment by jaakristioja** [comment]
I was not able to reproduce this with BibleTime compiled from the master branch (commit a5bc352776de85db029507870ba7b34d1697f5e9) as follows. When I right-click on a word in OSHB and select "Strong's search" from the popup menu, a search dialog appears with something like "strong:H3318" in the "Search for:" text field and immediately executes the search. In case OSHB was not indexed, it asks me whether to index it first.

Are you are doing something differently?

**Comment by LAfricain** [comment]
The problem was the range!! I used New Testament. Sorry for the false report. And even now the update of the module solve the problem for Xiphos.
