### ISSUE TITLE
[BUG] Lack of translation

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#373]
A small part of BT is not localized, in the advance search tool, the range of search, look the screenshot:
![range](https://user-images.githubusercontent.com/19690477/151371098-5a8b4921-9712-4fa6-97a8-cd4d30db2590.png)

**Comment by jaakristioja** [comment]
This should now be fixed by a5bc352776de85db029507870ba7b34d1697f5e9 in the master branch and by 334a4ed85a025336bf114314188435395be3cff0 in the stable-3.0 branch. Thank you for reporting!
