### ISSUE TITLE
Propose a new release for the next ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#375]
The new ubuntu LTS will be published in the next month. It would be great to have in the official debian repositories a new release of Bibletime, with the last commit. 
Some of it, according me, are really important.

**Comment by jaakristioja** [comment]
As far as I know, Ubuntu 22.04 will not be released in March, but on April 21, with feature freeze already on February 24. BibleTime currently has 13 open issues under the [3.1 milestone](https://github.com/bibletime/bibletime/milestone/13). I'm sorry, but releasing BibleTime 3.1 is unrealistic given our current slow pace of development. At the very best we might be able to release 3.0.3 before the Ubuntu feature freeze, but official downstream packaging is not under our control.

@LAfricain Did you mean 3.0.3 or 3.1?

We do however have a plan to provide our own APT repositories for BibleTime (see #258).

**Comment by LAfricain** [comment]
>  Did you mean 3.0.3 or 3.1?

3.0.3 would be perfect. The same as the snap.

> We do however have a plan to provide our own APT repositories for BibleTime (see https://github.com/bibletime/bibletime/issues/258).

Yes I know, and I already propose the 3.0.2 on the Crosswire PPA.

**Comment by jaakristioja** [comment]
It appears Ubuntu 22.04 already includes BibleTime 3.0.2: https://packages.ubuntu.com/jammy/bibletime
