### ISSUE TITLE
Include my name as a contributor.

### ISSUE THREAD

**Issue by FlavioTheoLima** [bibletime/bibletime#384]
Hi!
Please, I would like to have my name as a contributor to Bible Time translations pt-BR.
Thank you!
Flavio Theodor de Lima Silva

**Comment by jaakristioja** [comment]
Fixed by 9151e2cb0ab4bb5fa935d52e300b95ae4b23d5af in master branch and a5ef8e50531eafe42899b4d7b9b587a1a7a3aaa2 in stable-3.0 branch. Thank You! 😃
