### ISSUE TITLE
New Chinese Translator

### ISSUE THREAD

**Issue by aaron2wh** [bibletime/bibletime#385]
I have finished the translation.
pls include my name: Aaron Zhou

**Comment by jaakristioja** [comment]
Fixed by 9151e2cb0ab4bb5fa935d52e300b95ae4b23d5af in master branch and a5ef8e50531eafe42899b4d7b9b587a1a7a3aaa2 in stable-3.0 branch. Thank You! 😃

**Comment by aaron2wh** [comment]
could I ask when will the new version be released? really excited if I will see my mother language.

**Comment by jaakristioja** [comment]
Today, hopefully...

**Comment by jaakristioja** [comment]
@aaron2wh As a sidenote, while fixing #383 I noticed that the zh_TW translation contains "Yoryba" translated to "Yoryba". If you don't know the exact translations for some strings, it is better to leave it untranslated. The software will use the untranslated string in case there is no translation. Leaving it untranslated gives translators a better overview of what is actually translated and what is not.

**Comment by aaron2wh** [comment]
ok，thanks
