### ISSUE TITLE
[QUESTION] why there is no Mac dmg of 3.0.3?

### ISSUE THREAD

**Issue by aaron2wh** [bibletime/bibletime#389]
long for it...

**Comment by jaakristioja** [comment]
Well... many reasons, including us having poor CI, poor release procedures not containing steps for building binaries, technical, legal and financial obstacles for building on Mac/Windows, being undermanned, quite bad management (me), sub-optimal team dynamics/communication/coordination, team living in different timezones, volunteers having incompatible schedules, having families, being stressed out, lacking time, lacking hardware, lacking know-how, not being paid for developing BibleTime, having to work at a day job, and me not especially liking closed-source/proprietary operating systems.

If it weren't for Gary, there wouldn't probably be much hope for any 3.0.3 Mac binaries in the next months/years.

**Comment by gholmlund** [comment]
It is now available at github.

**Comment by aaron2wh** [comment]
> Well... many reasons, including us having poor CI, poor release procedures not containing steps for building binaries, technical, legal and financial obstacles for building on Mac/Windows, being undermanned, quite bad management (me), sub-optimal team dynamics/communication/coordination, team living in different timezones, volunteers having incompatible schedules, having families, being stressed out, lacking time, lacking hardware, lacking know-how, not being paid for developing BibleTime, having to work at a day job, and me not especially liking closed-source/proprietary operating systems.
> 
> If it weren't for Gary, there wouldn't probably be much hope for any 3.0.3 Mac binaries in the next months/years.

thanks for y'all for the volunteering work. that's really great and helpful.

**Comment by aaron2wh** [comment]
> It is now available at github.

great to see that. 
and can I ask a stupid question maybe:
since I'am the Chinese translator(not the tech expert) of project, and I really excited to know that 3.0.3 add Chinese localization.
but I download the Mac dmg, but it still shows English instead of Chinese. could anyone tell me how to change the UI to Chinese.
Btw my Mac system language is Chinese

**Comment by jaakristioja** [comment]
@aaron2wh You already filed #358 for that Mac translation issue.
