### ISSUE TITLE
[BUG]  TTFonts not loading, nor is defalt font sizable  OS is Mint 20.3 Cinninmon

### ISSUE THREAD

**Issue by Dangfree** [bibletime/bibletime#395]
**Bug description**
A clear and concise description of what the bug is. Please only describe one issue per bug report.

**Steps to reproduce**

**Expected behavior**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**System information:**
 - OS and OS version: [e.g. Debian 10, Windows 10]
 - BibleTime Version [e.g. 3.1_rc2]
 - How BibleTime was installed [e.g. from system packages, Snap, Flatpak, installer, compiled from source code]
 - Versions of modules related to the crash (if known)
 - (If compiled from source) Sword Version
 - (If compiled from source) Qt Version

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.

**Comment by jaakristioja** [comment]
I'm sorry, but the bug report does not contain enough information for us to diagnose or even understand the bug. You seem to have forgotten to fill out the bug report template. What is TTFonts? Please fill out the template you posted and reopen if this is still an issue.
