### ISSUE TITLE
Error bible WEBBE

### ISSUE THREAD

**Issue by ArnoVersfeld** [bibletime/bibletime#398]
I found the following error in WEBBE, Jeremiah 22:27 which reads:
But to the land **t** which their soul longs to return, there shall they not return. 
IT SHOULD READ
But to the land **to** which their soul longs to return, there shall they not return.

**Comment by gholmlund** [comment]
This problem occurs in BibleTime and Xiphos. It is not a problem with the applications. It is in the WEBBE module. This module is provided by ebible.org. Please contact them about this.
