### ISSUE TITLE
continually getting this "some of the selected modules were not  installed"

### ISSUE THREAD

**Issue by faithless2** [bibletime/bibletime#399]
Hi, I a running Kubuntu (Ubuntu) 22.4, using the onboard software repository I installed Bibletime (non snap) which ran as expected and proceeded to use bookshelf to install  modules, but some of the modules refuse to install even if I try them singularly over and over again, restarting bibletime or the OS does not help. 

Just wondering if this is mainly a Kubuntu issue rather than Bibletime and is there another way to access and install the required modules?

**Comment by gholmlund** [comment]
I am not aware of this issue. Could you tell us some modules that did not work so we could test this?

**Comment by jaakristioja** [comment]
I'm also quite often experiencing this. It is not a Kubuntu issue. But rather an issue with the Sword library which BibleTime uses in its backend and which does the downloading using curl. Most commonly, this occurs when the download of a single file takes more than 10 seconds. I recently discussed this issue with Troy A. Griffitts, the lead and main developer of the Sword project, but there seems to be no good fix at the moment. However, you may be able to work around this by increasing this strange timeout in your `~/sword/sword.conf` file, e.g. by a factor of 1000:

```ini
[General]
TimeoutMillis=10000000
```

@faithless2 Please let us know whether this helps.

**Comment by faithless2** [comment]
Hi jaakristioja,
Yes thank you that indeed worked and managed to finally get what I "wanted", though I could not find the  ~/sword/sword.conf file using "dolphin file manager" but did locate a installmgr.conf file which had the required line in it as well so just dropped in that 100000 as it was empty ....  and bingo!.... so many thanks for your advice.

**Comment by jaakristioja** [comment]
There is no easy fix to this we could apply to BibleTime. This is already tracked by the Sword project as [API-251](https://tracker.crosswire.org/projects/API/issues/API-251). I'm resolving this as an upstream issue.
