### ISSUE TITLE
Automatic updates of installed works

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#4]
It were nice to have a feature which would automatically check for updates for installed works. This feature should be optional, and only enabled when the user requests it (on first run), because it might cause problems for people in countries where christians are persecuted.

PS: This bug is from the old (bugs.bibletime.info) and older (SourceForge) tracker: https://sourceforge.net/tracker/index.php?func=detail&aid=2969434&group_id=954&atid=350954

**Comment by mgruner** [comment]
Hm. Not sure about an automatic update in the first place, but I would like to have the ability to just see and update the installed works. Right now using the bookshelf manager is pretty cumbersome if you have several remotes and also a number of works installed. It is almost impossible to identify which works can be updated. A separation of install and update could be helpful.

Besides, selecting a remote should not be neccessary. BibleTime should ideally fetch them all and present a consolidated list. All this is part of the current GUI being very much technically oriented and not so much user oriented.

A wizard for new installations bringing up the Bookshelf Manager if the bookshelf is empty would then be a top bonus. Currently it could be hard for new users to find out how they can actually install something to make BibleTime usable. :frowning: 

@gholmlund what do you think?

Best regards, Martin

**Comment by mgruner** [comment]
Ok, #2 would cover part of my complaints. :smile:

**Comment by gholmlund** [comment]
I would be willing to work on this. After reading this bug and bug #2, it seems there are 3 areas. 

A. Updating modules - This seems like it would be a simple list of modules needing updating. it would have check boxes, a button to update the list, and and button to perform the selected module updates. 

B. Welcome Wizard - Something to introduce BibleTime and direct new users how to install modules. 

C. Improvements to the Installing modules - I can picture a wizard which lets you select one or more repositories, then one or more languages, and then presents you will a much smaller tree similar to the current install page.  

I would appreciate any thoughts about this.

**Comment by mgruner** [comment]
Hello Gary,

sounds good. Would you keep the current install dialog also, or could it be replaced?

Regards, Martin

**Comment by gholmlund** [comment]
I think we can replace the current install dialog. I am mocking up a set of pictures of a wizard and will try to get them posted tomorrow.

**Comment by mgruner** [comment]
Awesome, thank you Gary!

**Comment by gholmlund** [comment]
[Pictures.pdf](https://github.com/bibletime/bibletime/files/64490/Pictures.pdf)
I have used Qt Designer to mock up my thoughts about a new Bookshelf Manager. 
Please comment.

**Comment by mgruner** [comment]
Hello @gholmlund, thank you very much so far. This looks very nice and would be a great improvement IMHO. I'd like to see a 2.11 release after this is implemented.

Some comments/suggestions:

Choose Sources: 
- What does the "Update Works" button do (mistake)?
- What does the "Update Sources" button do?
- An icon on the source row (trash can) could allow deletion.
- If there are no sources yet, we should automatically fetch the default source list.
- So in the end we might only need two buttons "Add/update recommended sources" and "Add custom source".
- A better term for "source" might be "(remote/online) library"?

Install Works:
- Only show nodes which have content.

Index Works:
- I believe we could eliminate this screen altogether. Indexes are created on the fly when searching, and we could have a logic in BibleTime that deletes indexes of updated/uninstalled works automatically (if not already present).

On the first start of BibleTime we could present a welcome screen which redirects to the bookshelf manager with the "install works" option preselected.

**Comment by gholmlund** [comment]
What does the "Update Works" button do (mistake)?
* Updates the list of remote repositories.

What does the "Update Sources" button do?
* Updates the works available from each repository.
* We could certainly combine these two actions.

An icon on the source row (trash can) could allow deletion.
* Sounds good.

If there are no sources yet, we should automatically fetch the default source list.
* I was planning this.
    
So in the end we might only need two buttons "Add/update recommended sources" and "Add custom source".
* Yes.

A better term for "source" might be "(remote/online) library"?
* Yes, I was initially just using the current terminology. 

Install Works:
Only show nodes which have content.
* Yes.

Index Works:
I believe we could eliminate this screen altogether. Indexes are created on the fly when searching, and we could have a logic in BibleTime that deletes indexes of updated/uninstalled works automatically (if not already present).
* Agreed.

On the first start of BibleTime we could present a welcome screen which redirects to the bookshelf manager with the "install works" option preselected.
*  Agreed.

**Comment by mgruner** [comment]
Hello Gary,

thanks a lot for your feedback.

> 	• Updates the works available from each repository.

this could be an automatic action that happens when the user clicks on »next« (and the cache is older than some hours). No button needed for this.

Regards, Martin

**Comment by gholmlund** [comment]
I will make it auto update as you described and we will see how we like it. It will take a few seconds to update (with a fast connection).
In the list of sources I could add one additional line which says something like this: "Add custom source". That would remove another button. (The last one).

**Comment by mgruner** [comment]
This is now implemented in master, thanks so much @gholmlund!
