### ISSUE TITLE
BIBLETIME WILL NOT BUILD ON 32 BIT SLACKWARE -CURRENT - CANNOT FIND -LSWORD

### ISSUE THREAD

**Issue by musicman0** [bibletime/bibletime#40]
(32bit), but it stops before completion.  This is what is going on when it stops:

[ 98%] Building CXX object CMakeFiles/bibletime.dir/src/frontend/settingsdialogs/moc_clistwidget.cxx.o
[ 98%] Building CXX object CMakeFiles/bibletime.dir/src/frontend/settingsdialogs/moc_cswordsettings.cxx.o
[100%] Building CXX object CMakeFiles/bibletime.dir/src/frontend/tips/moc_bttipdialog.cxx.o
Linking CXX executable bibletime
/usr/lib/gcc/i586-slackware-linux/4.9.3/../../../../i586-slackware-linux/bin/ld: cannot find -lsword
collect2: error: ld returned 1 exit status
make[2]: *** [bibletime] Error 1
make[1]: *** [CMakeFiles/bibletime.dir/all] Error 2
make: *** [all] Error 2

Thank you for your time.  Any suggestions would be appreciated.  One additinal item:  I tried building version 2.10.0, but had the same error.

**Comment by greg-hellings** [comment]
You need to have libsword installed in a location where your ld command can find it. If it's not installed in such a location by default, you'll need to provide the LDFLAGS environment variable to add it to the arguments passed in.

**Comment by musicman0** [comment]
Would it be possible for you to give me instructions on how to do this?   This is something I have not needed to do before.  I look forward to learning something new.

Once again, thank you for your assistance.

**Comment by musicman0** [comment]
One other item:  if it makes any difference, I am using the slackbuild to do this, but if I need to do this outside the slackbuild, that is fine as well.
