### ISSUE TITLE
How to do 3 languages bible horizontally  eg: Gen1:1 (english then german language then french),  Gen1:2 (english then german language then french) .  [QUESTION]  

### ISSUE THREAD

**Issue by andrew-ysk** [bibletime/bibletime#406]
**Background**
I am in bible studying online group. We read bible multilanguage, 1 line english, 1 line german language, 1 line french, is it possible to achieve this in the app ?  
I am currently only able to do 2 column of different languages. Instead of vertical column, we would like to have it horizontally line by line. 

**Question**
How to do setup bibletime so that it is horizontal interline between different language ? eg: Gen1:1 (english then german language then french),  Gen1:2 (english then german language then french) .

**Comment by jaakristioja** [comment]
I apologize for the delay. And I'm sorry to say that this is currently not possible in BibleTime.
