### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by david-burleigh** [bibletime/bibletime#408]
**Question**
Is it possible to freeze the window configuration within the BibleTime interface? I have the various panels exactly how I want them, but sometimes they all get re-tiled in a different way without any intentional action on my part. This is with the overall BibleTime window maximized.

**Comment by gholmlund** [comment]
Have you tried the menu "Window/Arrangement Mode/Manual Mode". This lets you place the windows as desired and will not re-arrange them. Any new window will appear on top of the originals windows, but not arrange them.

**Comment by david-burleigh** [comment]
No, I hadn't noticed that. Thank you!

**Comment by jaakristioja** [comment]
Closing, as this seems to have been answered.
