### ISSUE TITLE
[QUESTION] Dark Mode in Linux

### ISSUE THREAD

**Issue by ganakee** [bibletime/bibletime#409]
**Background**
I installed BibleTime 3.0.2 from the POP OS repo. I looked for a dark mode setting in BibleTime...Settings...Configure BibleTime . I do not see a dark mode. I searched the GitHub issues for dark mode references and only found a Mac OS topic and some additional, generic references that dark mode might be available. 

**Question**
How does one apply DARK MODE to the BibleTime UI on Linux? (I need to have dark mode for an eye issue.) All other apps use the system dark mode.

Linux:
POP OS 22.04 with all updates (Debian/Ubuntu base)
GNOME 42.4
X11 Windowing

Bible Time installed as a native app from repo (NOT flatpak)
BibleTime 3.0.2 (most current version in POP OS repo)

![Screenshot from 2022-09-21 11-27-47](https://user-images.githubusercontent.com/23140586/191546366-0cfa7330-1655-4d11-870d-e857e4296236.png)

**Comment by ganakee** [comment]
Thank you for the reply. 

No, I do not see any option. On Linux, the system theme should apply (GNOME 40 and above) to the app. I don't think that is happening which means it might be non-Gnome or an older Gnome platform.

**Comment by ganakee** [comment]
Wow. Thanks @53R3n17Y-serenity

**Comment by cheezgr8r** [comment]
@ganakee , I have the same question. What ended up being the resolution? I don't see any comments but yours

**Comment by gholmlund** [comment]
Since the Dark mode setting required a user interface change,  it had to be made in the master branch, not the stable branch. Currently the change is not in a released version of BibleTime. It will be available when 3.1 is released.

If you are able, you could compile the master branch and get the feature.

**Comment by cheezgr8r** [comment]
Thank you! I was able to figure out how to compile the master branch to be able to use dark mode
