### ISSUE TITLE
Some Bibletime modules not being installed 

### ISSUE THREAD

**Issue by duke-sc** [bibletime/bibletime#410]
**Background**
Hi, I'm running linux mint Cinnamon latest release.  I've just installed Bibletime and on first startup selected a whole bundle of modules to install.  Bibles, dictionaries, devotionals.  After the downloads finished I went into Bibletime and only a few of the dictionaries and a couple of other books were present.  None of the Bibles were there.  I tried again but this time just selected the LEB bible and after the progress bar finished a message was displayed saying there was a problem downloading the resource.
**Question**
Am I missing something?  I'm new to Linux but have had no problem downloading and installing other programs from the software manager.  Point worth making - I had exactly the same problem when trying to add resources to Xiphos bible software.  Does this point to a problem with the way my system is running?

Any help greatly appreciated,

Robert

**Comment by jaakristioja** [comment]
This is most likely caused by the buggy downloads logic in libsword. See #352 and #399. A workaround might be to edit your `~/.sword/sword.conf` configuration file to include something like the following:

```ini
[General]
TimeoutMillis=10000000
```

Please reopen, if this does not help.
