### ISSUE TITLE
[BUG] Unable to open Preferences without books downloaded

### ISSUE THREAD

**Issue by danzek** [bibletime/bibletime#413]
**Bug description**
Opens with incorrect language settings and crashes when I attempt to open Preferences to change them.

**Steps to reproduce**
1. Install BibleTime in Applications folder
2. Open BibleTime
3. Opened for me in Russian language. This is a language/keyboard I have installed but my computer is set to English as the main language.
4. Open Preferences.
5. Program immediately crashes. Unable to view/change Preferences.

**Expected behavior**
The Preferences window should open and allow me to change the language setting.

**System information:**
 - OS and OS version: macOS 12.6 Monterey (M1 / Apple Silicon)
 - BibleTime Version: 3.03 release DMG from https://github.com/bibletime/bibletime/releases/download/v3.0.3/BibleTime-3.0.3.dmg
 - How BibleTime was installed: copied to Applications, com.apple.quarantine attribute manually removed

**Additional context**

Crash report attached: [BibleTime-2022-10-15-204105.ips.txt](https://github.com/bibletime/bibletime/files/9795197/BibleTime-2022-10-15-204105.ips.txt)

**Comment by danzek** [comment]
Installing some books and then opening one allows Preferences to be opened without crashing. However, there is no option to change the language used in the program. So the program is incorrectly getting my system language and there is no way to change it.

**Comment by danzek** [comment]
My language settings are correctly set to English and I do not have this issue with other applications, including other Qt applications. The `CFBundleDevelopmentRegion` key is set to `en-US` in the application's `Info.plist` yet it still shows up in Russian. I've also confirmed my macOS language settings are correctly set to English in the GUI preferences as well as using `languagesetup` CLI utility (`en`).

See, e.g.: 

- https://doc.qt.io/qt-5.15/macos-issues.html#translating-the-application-menu-and-native-dialogs
- https://bugreports.qt.io/browse/QTBUG-72491
- (older:) - https://bugreports.qt.io/browse/QTBUG-40882

**Comment by danzek** [comment]
For further testing, I compiled a simplistic Qt CLI app to output the value of `QLocale().name()` as [that appears to be how BibleTime is fetching my language/locale](https://github.com/bibletime/bibletime/blob/ae44428a31ed457c2cf0941efb0b1ba6f06bc353/src/frontend/settingsdialogs/cdisplaysettings.cpp#L180).

Code:

```
#include <QCoreApplication>
#include <QLocale>
#include <QDebug>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    qDebug() << "QLocale name: " << QLocale().name() << Qt::endl;

    return a.exec();
}
```

Output:

`QLocale name:  "en_US" `

It appears to be correct. However, I tested using Qt 6.3.1, not 5.15 which I believe is what BibleTime uses. I imagine the result should be the same, though.

**Comment by danzek** [comment]
I'm also unable to explicitly set the app's language.

<img width="780" alt="Unable to set app-specific language on macOS Monterey" src="https://user-images.githubusercontent.com/6609869/196047199-810d9803-c54f-43b2-b591-b419ae735f3d.png">

**Comment by danzek** [comment]
Also @53R3n17Y-serenity thank you for the help/hints. I did update my original post to make the crash dump an attachment instead of inline.

**Comment by gholmlund** [comment]
I have duplicated the crash in a linux debug build and see where the bug is located. Bug occurs when opening preferences dialog without any works installed.

I should be able to check in a fix in the next couple of days.

**Comment by gholmlund** [comment]
Note: The language for menus and dialogs is controlled by :
     Apple menu  > System Preferences, click Language & Region , then click General. The top language will be used for Qt programs.

**Comment by gholmlund** [comment]
>>  I was guessing that since Settings use Style Preview in it, it might be crashing because there are no works to populate that section of the window.

Actually it was crashing in code related to the "Language for names of Bible books" combo box. It was trying to use the current entry when there were no entries.

**Comment by danzek** [comment]
@gholmlund I'm glad you tracked down the Preferences crash bug.

Concerning language settings, English _is_ my top language, but it still shows in Russian. You can also see the output for `QLocale().name()` in the sample program I wrote above is `en_US`.

<img width="339" alt="English as top language" src="https://user-images.githubusercontent.com/6609869/196340160-bb05a026-35a2-41d3-8704-11bb6ca009f1.png">

**Comment by gholmlund** [comment]
@danzek  I duplicated your Russian language problem with BibleTime. Since handling two issues in one report is not desired,  please submit another report about this.
