### ISSUE TITLE
[ENHANCEMENT] Share bookmark files between various frontends

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#418]
Currently each software create bookmarks in the profile of its applications.

 It would be very useful to be able to share a common folder between all these applications (to my knowledge xiphos and bibletime maybe Esra) in which the bookmarks would be accessible.
I think for example of a bookmark folder in the $HOME/.sword/
I opened the same issue in the [xiphos](https://github.com/crosswire/xiphos/issues/1120) repo.

**Comment by jaakristioja** [comment]
See also #263.

**Comment by LAfricain** [comment]
The #263 is a very close issue, I can close this one. But we have to be careful about file format. I tried to create in xiphos a symbolic link from `.xiphos/bookmarks.xml` to `.sword/bookmarks/bookmarks` and it works well. With BT also, but If I modify the file in BT it will create a new xml in` .bibletime` and remove the symlink.
