### ISSUE TITLE
[QUESTION]  Formatting titles in GenBook

### ISSUE THREAD

**Issue by jd-s** [bibletime/bibletime#421]
**Background**
I have multiple GenBooks which I want to use in BibleTime. However, the display is rather... let's call it generic. In particular, I would like to change the display of title-tag, since it is nearly impossible to figure out where a section begins or ends. For this, I changed my prefered css-theme and added

```
title {
   font-size: 160%;
}
```
However, this did not do the trick. 

**Question**
How can I adjust the style for any tag in books displayed with bibletime? In addition, I would like to change the font and font size.

**Comment by jaakristioja** [comment]
I think that in general you are doing it correctly, there is just no `<title>` tag, but the titles are rendered using some other tag(s).

**Comment by jd-s** [comment]
I guess an answer will be provided in #447.
