### ISSUE TITLE
[ENHANCEMENT] Add ability to freeze window layout

### ISSUE THREAD

**Issue by david-burleigh** [bibletime/bibletime#427]
I always use BibleTime maximized to the full screen, and I set all the windows in a certain configuration that I would like to freeze, but sometimes when I close BibleTime and then later restart it, it loses my window configuration. Being able to force my preferred configuration would be very helpful.

**Comment by gholmlund** [comment]
Have you tried using Windows > Arangement mode > Manual mode

Select this mode and arrange your windows manually.
