### ISSUE TITLE
Bibletime crashes at startup 

### ISSUE THREAD

**Issue by cscj001** [bibletime/bibletime#429]
On Ubuntu 22.04.2, I get the following when trying to start Bibletime from a terminal:

`(BibleTime 3.0.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)`

**Comment by cscj001** [comment]
My Syslog shows the following:

`Apr  7 13:41:26 cp1 metacity[2104]: Invalid WM_TRANSIENT_FOR window 0x5200008 specified for 0x5200009 (bibletime).
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: components have the same version.
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: components have the same version.
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: components have the same version.
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: components have the same version.`

I have an Nvidia Geforce 750 TI graphics card.  The driver version shown as installed appeards to be the correct version.

**Comment by cscj001** [comment]
BTW, my Syslog shows the following:

`Apr  7 13:41:26 cp1 metacity[2104]: Invalid WM_TRANSIENT_FOR window 0x5200008 specified for 0x5200009 (bibletime).
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.632637] NVRM: components have the same version.
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.636167] NVRM: components have the same version.
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.639944] NVRM: components have the same version.
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: API mismatch: the client has the version 470.182.03, but
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: this kernel module has the version 470.161.03.  Please
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: make sure that this kernel module and all NVIDIA driver
Apr  7 13:41:27 cp1 kernel: [853422.644809] NVRM: components have the same version.`

I have an Nvidia Geforce 750 TI and the driver version shown appears to be correct.

**Comment by gholmlund** [comment]
I googled for the following:
    Failed to create OpenGL context for format QSurfaceFormat(version 2.0

I came up with numerous results with various OS and OS versions. All seem to relate to Qt calling the video driver. This is further down that BibleTime code. I doubt we can do anything about it.

Also, I noticed several version mismatches in the syslog above. They relate to the video driver (NVIDIA).

**Comment by ilkant** [comment]
I had problems with Stellarium (open source astronomy program) screen. There were squares on screen. When I changed open source noveau drivers to closed nvidia drivers, problem disappeared. You can try to use different drivers.

**Comment by jaakristioja** [comment]
This also duplicates #125, #170, #176, #295 and #419.
