### ISSUE TITLE
[BUG] Daniel and Esther not displaying

### ISSUE THREAD

**Issue by kainekh** [bibletime/bibletime#430]
Sorry to bother you, and I appreciate your work.

**Bug description**
I cannot access the Greek version of Daniel in products that support it or the same books in a Catholic edition. I can read every other book from the Apocrypha.

**Steps to reproduce**
1. Open Daniel or Esther in a Catholic Bible, and nothing appears. In versions like WEB with Deuterocanonicals, I do not see the Greek version of either. When I select "Esther (Greek)" specifically from the dropdown menu, it takes me to Revelation 1.  "Bel and the Dragon," "Susanna," and "Song of the Three Children" come up blank. All other Apocrypha appears.

This is all true about the World English Bible both Catholic and the version with Apocrypha. However in the LXX2012 it shows up correctly save that the Song of the Three Children is not in Daniel 3, but I suspect that is the Bible's encoding.

**Expected behavior**
I should be able to access the text either by accessing the Greek version in either or by accessing the book proper in the Catholic version..

**Screenshots**
![daniel](https://user-images.githubusercontent.com/13243368/231825319-65d77630-7130-4ce3-bca2-f78aa931ceb0.png)
![esther](https://user-images.githubusercontent.com/13243368/231825489-86ef2dd2-0291-4f3f-97ad-7f3fc8f19faa.png)

**System information:**
 - Arch, QT base 6.5.0-3 and QT base 5.15.9-1. Sword version 1.9.0-7
 - BibleTime 3.0.3
 - How BibleTime was installed: System package; I used pacman and not the AUR. 

**Additional context**
I checked ~/.local/share/bibletime and didn't see a log. I have not tried building from Git and can if I should try that. I attempted to correct this by redownloading them and manually installing them from ebible.org. This did not allow me to access the books.

**Comment by gholmlund** [comment]
I tried this and duplicated it in the BibleTime master branch. Then I tried it in Xiphos and also could not read Daniel or Esther. I conclude this is a problem with the engWEBc2015eb module.
