### ISSUE TITLE
[QUESTION] where is the downloaded book located in Mac and how to clean uninstall

### ISSUE THREAD

**Issue by aaron2wh** [bibletime/bibletime#431]
**Background**
from somehow everytime when I lanuch bibletime, it shows up a black screen. then I remove the app and reinstall the app, after loading, it can show up the main window, but som weird things as this:
1,I found in the upleft corner(the Bible and dictionary block), it shows all the bibles and dicts I have downloaded before the reinstallation. 
2, when I double click to open any of these bibles, it show up a black screen. 

then I shoud cmd+Q to quit the app, but when I relaunde, it will show up a black screnn after loading.

I have removed and reinstallded the app many times, keep happening this problem.

so I think I should have a clean uninstall to solve the problem. but I can't finde the downlaoded Bible files in ~/Library/Applicastion Support/bibletime folder. I thought the downloaded file must be stored in some other places.

OS: Monterey
Bibletime: 3.0.3

**Question**
How to [...] / What is the [...] / Is it possible to [...]

**Comment by aaron2wh** [comment]
> The BibleTime settings are located in $HOME/Bibletime. I would try deleting or renaming it first.
> The Sword modules are located in $HOME/Sword.

where is the $HOME folder?  if you mean APPLESSD/home， for me this is a empty folder.

**Comment by gholmlund** [comment]
I should be /Users/<account name>
It is the one containing the Download and Pictures directories.

**Comment by aaron2wh** [comment]
and  I checked my username folder, this is no folder called Bibletime or related. I showed hidden things already

**Comment by gholmlund** [comment]
I am sorry. I gave a wrong answer. Look at:
/Users/Some_name/Library/Application Support/
