### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by biblestudier** [bibletime/bibletime#432]
I run BibleTime on Linux (Suse LEAP 15.4) and 3.0.2 works fine.  I'm mentioning this because I am a long time user of Bible Time but over on Linux. I've had to go to W11 so I can use M/S Word. 

The problem is W/11 and BibleTime 3.0.3.  The primary window doesn't behave well, that is, it doesn't behave like other applications and their windows. And I think this problem is being caused by how Windows 11 is trying to manage the display. It took a while before I could get <F5> to take it out of full screen mode.

Now in trying to set the MAG window where I want it, it wants to display horizontally across the whole BT window. But I want it to run down the left side. I can get it over to the left and have it "stand up" but if it take it into the BT window it goes across the top (as in jumps to that). So if I put it just to the left of the BT window and let go of it, it jumps into the BT window where I had been trying to place it. This is rather unfriendly behavior. And like I said above, BT 3.0.2 and prior NEVER behaved like this behavior on W11 with BT 3.0.3.

**Comment by gholmlund** [comment]
I cannot reproduce this problem on my W11 with 3.0.3. 
I think it might be a corrupt bibletimerc file. I would suggest renaming it or deleting it.  It contains your settings and gui info.
C:\Users\<name>\AppData\Roaming\BibleTime\bibletimerc

**Comment by biblestudier** [comment]
Did as asked and that seems to have fixed it. Now, my question is, how did this happen? (I do software development on IBM type mainframes, so I always ask this after a customer gets into some weird problem).  I'm just getting familiar with Git because it is now being used by different groups running in z/OS environments and I think z/VM (Hipervisor) environments. So I don't know the answer to this question: Can this be put in some "waiting" status until I can work with this for about a week or so and see if I hit it again?

**Comment by biblestudier** [comment]
Haven't hit this again.
