### ISSUE TITLE
Multiple frontends

### ISSUE THREAD

**Issue by kalemas** [bibletime/bibletime#44]
Is class BibleTimeApp supposed to be used by non-BibleTime frontends (Mini, Mobile) ?

If i run my own QApplication i can not talk to BtConfig that i found very convinient. And user have to set same settings for each frontend.

Question arised because BbileTimeApp have references to frontend/MessageDialog.h that Mini can not to utilize. But it is some wider because common living of two frontends would bring some difficulties like,  frontend developer have to know whether config entry is common or it is BibleTime-only.

By the way there is some logic in main.cpp that is necessary for correct work of any frontend, like registerMetatypes().

**Comment by gholmlund** [comment]
Mobile has its own version of BibleTimeApp (src/mobile/bibletimeapp.cpp. The one in src/bibletimeapp.cpp is only for the desktop version.

**Comment by kalemas** [comment]
Do you use BtConfig ?

**Comment by kalemas** [comment]
I got, you have a copy of a file. I think it is not good practice to maintain a copy of code. Maybe if you use any automatic merging tools/hooks...

Are you still using same config file BibleTime use?

**Comment by gholmlund** [comment]
Mobile uses BtConfig and the same bibletimerc file.

**Comment by jaakristioja** [comment]
We should work towards the master branch only containing code the BibleTime PC desktop application and it's CMake build system. Everything else should go to different branches or repositories, including the `*.pro` files and BibleTime Mobile etc. Having multiple projects in one repository usually doesn't end well. In the long run this probably means that all common code (e.g. `src/backend`) should be modularized and built as a common library. Many of my recent commits have been made towards these goals.

PS: This will also make source tarballs smaller and simplify the build system a lot.

**Comment by kalemas** [comment]
Agree. I ll remove BibleTime.pro but would like to maintain rest of  qmake scripts while they  are  generating conflicts in Mini.

Can not see here answer to my question: BtConfig I'd a part of backend but it can not be used without BibleTimeApp class that is PC-only as Gary states. It is very unobvious now what is supposed to be common code and what is not.

Some of code is useful for other frontends but intended to use only in PC version like BtIcons that base class have whole set of icons related to backend (like icons for bookshelf model) and PC front end (like button icons). And I can see now some code in main.cpp and application class also related here.

We could discuss where this l line goes so I can help with dividing backend/frontend code.

-----Исходное сообщение-----
От: "Jaak Ristioja" <notifications@github.com>
Отправлено: ‎26.‎09.‎2015 12:33
Кому: "bibletime/bibletime" <bibletime@noreply.github.com>
Копия: "Konstantin Maslyuk" <kalemas@mail.ru>
Тема: Re: [bibletime] Multiple frontends (#44)

We should work towards the master branch only containing code the BibleTime PC desktop application and it's CMake build system. Everything else should go to different branches or repositories, including the *.pro files and BibleTime Mobile etc. Having multiple projects in one repository usually doesn't end well. In the long run this probably means that all common code (e.g. src/backend) should be modularized and built as a common library. Many of my recent commits have been made towards these goals.
PS: This will also make source tarballs smaller and simplify the build system a lot.

**Comment by jaakristioja** [comment]
AFAIK, when BibleTime and Sword started out, these were not written by professional software developers. Hence we have a lot of legacy spaghetti code everywhere, not to mention loads of architectural issues. I wish I had good answers to your questions, but I don't right now.

**Comment by kalemas** [comment]
Good answer, let me know if could help.

-----Исходное сообщение-----
От: "Jaak Ristioja" <notifications@github.com>
Отправлено: ‎26.‎09.‎2015 14:34
Кому: "bibletime/bibletime" <bibletime@noreply.github.com>
Копия: "Konstantin Maslyuk" <kalemas@mail.ru>
Тема: Re: [bibletime] Multiple frontends (#44)

AFAIK, when BibleTime and Sword started out, these were not written by professional software developers. Hence we have a lot of legacy spaghetti code everywhere, not to mention loads of architectural issues. I wish I had good answers to your questions, but I don't right now.
