### ISSUE TITLE
Could someone with the skills repackage the Bibletime 3.0.3 flatpak? Platform is end of life.

### ISSUE THREAD

**Issue by Declanomad** [bibletime/bibletime#441]
Problem: 
Flatpak update reports that the platform for the Bibletime 3.0.3 flatpak is end of life.
Also flathub marks the flatpak as using a legacy windowing system and potentially unsafe.

Background:
An up to date flatpak version would be helpful. The current one works, but tends to cause the desktop to go into fallback mode. There isn't a deb package of 3.0.3 for the current base of my OS (Linux Mint 21.2 Cinnamon, on 22.04 jammy).

Details:
"Checking for flatpak updates
Looking for updates…
Info: **org.kde.Platform//5.15-21.08 is end-of-life**, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Applications using this runtime:
   **info.bibletime.BibleTime**"

![Screenshot from 2023-10-03 13-43-37](https://github.com/bibletime/bibletime/assets/143219882/9dfc27a7-11ef-44cb-864e-e0014710ccfb)

**Comment by gholmlund** [comment]
New flatpak is ready at flathub.org

**Comment by Declanomad** [comment]
Thank you.
