### ISSUE TITLE
[ENHANCEMENT] Please add BibleTime to Winget on Windows

### ISSUE THREAD

**Issue by southpawiam** [bibletime/bibletime#444]
I had a catastrophic fail on Windows resulting in a fully reset operating system recently.  I looked for some "newer" option for installations and there was an option called winget in powershell 7, and likely earlier(You can disable powershell 2, uninstall the microsoft store powershell 5 and just use powershell 7 and winget - https://winstall.app/ ).  It's amazing.  I installed all the software I could through winget, and I have found software dependencies update through winget easily(including dependencies from software installed by Steam).    

However, I also found that very little Bible software is using winget which is why I'm requesting this.  There's BPBible, which requires additions separately downloaded through a web browser and Logos 9.  Other than than, there's nothing Bible there.  There's not even Bible memory apps.

**Comment by krisek** [comment]
https://github.com/microsoft/winget-pkgs/pull/129772

**Comment by jaakristioja** [comment]
The [referenced pull request to microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs/pull/129772) by @krisek seems to have been merged, so I suppose an unofficial Winget package of BibleTime is now available and this GitHub issue probably is no longer relevant. Please also note that the BibleTime team currently has no plans or much resources to create or maintain any Winget packages of BibleTime (neither official or unofficial packages). Hence closing this as WONTFIX.

**Comment by krisek** [comment]
Anybody interested, package definition for 3.1.1 has been just merged in winget manifest repo. I'll try to keep it up to date in the future -- I won't report here anymore, if something is missing issue can be raised on https://github.com/microsoft/winget-pkgs/issues
