### ISSUE TITLE
[BUG] JFB Commentary doesn't work on bibletime

### ISSUE THREAD

**Issue by milkias17** [bibletime/bibletime#448]
**Bug description**
Upon installation of the JFB commentary, I have tried it with other sword software namely xiphos, and the commentary works no problems. However when trying to open the commentary on bibletime, bibletime spikes cpu to 100% and just crashes.

**System information:**
 - Fedora 39
 - BibleTime 3.0.3
 - Fedora system package
 - Jamieson Fausset Brown Bible Commentary Version: 3.0 

**Additional context**
LOOKING UP LOCALE DIRECTORY...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP LOCALE DIRECTORY COMPLETE.
LocaleMgr::loadConfigDir loading /usr/share/sword/locales.d
LOOKING UP MODULE CONFIGURATION...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP MODULE CONFIGURATION COMPLETE.
LOADING MODULE CONFIGURATIONS...
LOADING MODULE CONFIGURATIONS COMPLETE.
LOADING MODULE LIBRARY...
libsword: SWMgr::createAllModules
libsword: SWMgr::createAllModules
LOADING MODULE LIBRARY COMPLETE.
ERROR: corrupt data during decompression.
ERROR: corrupt data during decompression.
LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

**Comment by gholmlund** [comment]
Duplicate of #396 and #417. Fixed in master branch. Not yet in released code.

**Comment by milkias17** [comment]
Oh, didn't notice. Thanks🙏
