### ISSUE TITLE
[QUESTION] Documentation generation is not optional?

### ISSUE THREAD

**Issue by stratacast** [bibletime/bibletime#449]
**Background**
I am building bibletime with the BUILD_HANDBOOK_* and BUILD_HOWTO_* settings to OFF. bibletime builds and installs successfully.

**Question**

When I launche bibletime, it fails and I get this error:

```
(BibleTime 3.0.3) WARNING: Cannot find documentation directory relative to "/usr/local"
(BibleTime 3.0.3) FATAL: Error initializing directory cache!
Please report this bug at https://github.com/bibletime/bibletime/issues
```

Is this related to not building the above? Does that mean it is not optional, or is there something else I am missing?

**Comment by gholmlund** [comment]
Yes, this is related to not buiding doc. See the last entry on the BibleTime wiki. 
[Latest generated documentation for BibleTime stable branches](https://bibletime.info/generated_docs/)

You must extract this into /usr/local/doc

**Comment by stratacast** [comment]
Is there a specific directory structure it is expecting? For example, the HTML handbook I have `/usr/local/doc/generated_docs/v3.0.3/handbook/html/en/index.html`, which it cannot find.

**Comment by gholmlund** [comment]
Sorry, I should have tried my procedure. 

mkdir /usr/local/share/doc/bibletime
This should be enough to run bibletime without error.

If you want the docs you can checkout this git repository:
https://github.com/bibletime/generated_docs.git
go to the "docs/v3.0.3" directory.
The "handbook" and "howto" directories can be copied to /usr/local/share/doc/bibletime/

**Comment by stratacast** [comment]
Awesome thank you so much! That worked. I can't build docs, otherwise I can confirm it builds and runs on OpenBSD 7.4. Most of the document generation tools aren't present on OpenBSD. Not sure if xiphos is down or not, but I am unable to update that remote library for some reason
