### ISSUE TITLE
sword libraries not found when compiling bibletime

### ISSUE THREAD

**Issue by guasabara** [bibletime/bibletime#450]
1.  Please report any bugs your find to our issue tracker
  should read 'bugs you find'  This is in the bibletime github page.

2.  I compiled sword and the libraries are installed to /usr/lib64, bibletime cmake scripts could not fine the libraries.  It did compile ok when adding /usr/lib64 using ccmake.

**Comment by jaakristioja** [comment]
> 1. Please report any bugs your find to our issue tracker
>        should read 'bugs you find'  This is in the bibletime github page.

Fixed, thanks!
 
>     2. I compiled sword and the libraries are installed to /usr/lib64, bibletime cmake scripts could not fine the libraries.  It did compile ok when adding /usr/lib64 using ccmake.

If this is a bug, please file a separate bug report and include more detail also stating the exact steps you took, so we can find the exact cause or can at least reproduce the issue. Thanks.
