### ISSUE TITLE
Upgrade to Qt6

### ISSUE THREAD

**Issue by emdee-is** [bibletime/bibletime#451]
Is there work underway to build against Qt6?

Bibletime is in the Gentoo supported packages, but Qt5 isn't anymore.

If you use pyqt it may help if you switch to using qtpy, which insulates the 5->6 changes.

**Comment by jaakristioja** [comment]
> Is there work underway to build against Qt6?

No. The master branch already builds with Qt6.

> Bibletime is in the Gentoo supported packages, but Qt5 isn't anymore.

You are mistaken. Qt5 is still supported by Gentoo.

> If you use pyqt it may help if you switch to using qtpy, which insulates the 5->6 changes.

I don't think you understand what you are suggesting.


Closing, since the master branch already builds against Qt6 and support for Qt6 will be part of the next major release.

**Comment by emdee-is** [comment]
I'm glad master works with Qt6.

You may be right in that Qt5 is in gentoos repo but I think de-facto, building anything that requires Qt6 upgrades with nameslot change the Qt5 components - I'm not sure you can have both on a system.

Thanks for the great software and I look forward to the new release.

**Comment by Arusekk** [comment]
Additional context (scheduled removal in Gentoo): https://bugs.gentoo.org/926655
