### ISSUE TITLE
[QUESTION] No KingComments available

### ISSUE THREAD

**Issue by ScotlandTheBrave** [bibletime/bibletime#453]
**Background**
I have loaded Bible Time about three or four times.  Each time, at the point where I select the concordances I want loaded, amongst others, I select KingComments.   And yet when I eventually run the application it does not get listed.

Yet in .Sword it appears to be listed.  Am I doing something wrong?  Or is BibleTime changing what can and cannot be accessed?

I downloaded "KingComments.zip" from the home website, but have had problems trying to install it into .Sword.

Please help

Al

**Comment by ScotlandTheBrave** [comment]
Further to my question above
------------------------------------------
I don't know if any of the following will help, but I assume it's actually better to have too much information than insufficient information.

Further to the above, I am currently on Linux 21.3.  I installed it about a week ago.
I am on version 3.0.2 as this is the one available from my Software Manager.

Al

**Comment by ScotlandTheBrave** [comment]
Hello,

Thank you for your response.

Following your instructions I renamed the /.Sword folder and then let BibleTime recreate that folder, and its contents, unfortunately I still have no King Comments, or about four other concordances which I deliberately specified when I reloaded the package.

I have since completely removed /.BibleTime & /.Sword, have rebooted, and have reinstalled the BibleTime package from my Linux Software Manager, unfortunately there are still about five or six concordances which appear to be missing.   However I have gone to the website of King Comments and he actually provides a *.zip package which can be loaded into the /.Sword folder, and after a little bit of "fiddling" I have managed to see this concordance, if not any of the other ones I specified.

I'm actually beginning to wonder if something has changed within Linux Mint, as I have only experienced this problem since I upgraded from Linux Mint 20.3 to 21.3.

However, everything is moderately OK now, so I will accept that what I have is enough and stop being so "picky" and enjoy BibleTime.

God bless you


Al

**Comment by gholmlund** [comment]
I notice you keep putting capital letters in these directories. There should be no capital letters in them on linux.
.bibletime
.sword

**Comment by ScotlandTheBrave** [comment]
That is purely force of habit as I do a lot of creating tutorials and reviews and I simply become accustomed to doing that with proper names   To be correct I will endeavor to maintain the correct syntax.

But my typing certainly doesn't have any bearing on my issue.


Al

**Comment by ScotlandTheBrave** [comment]
Issue not resolved, but I'm relatively happy with the "work around"

Al
