### ISSUE TITLE
[BUG]  NT chapter lengths strangely referencing OT chapter lengths

### ISSUE THREAD

**Issue by B-Interactive** [bibletime/bibletime#457]
**Bug description**
When using the **Select chapter** dropdown, all of the New Testament books are showing an incorrect number of chapters.  The number of chapters shown, is actually a reference to the equivalent Old Testament book.  So Genesis (50 chapters) is referenced, when in Matthew and hitting **Select chapter** (1-50 will be shown as options).

This is not an issue with the Old Testament books.
New Testament books are presenting chapter lengths based on their Old Testament counterpart (Genesis to Daniel).  So book 1 (Genesis) is being referenced by Matthew in terms of number of chapters.  Exodus is referenced by Mark, Leviticus by Luke, etc.  Revelation references Daniel, so presents only 12 chapters, making quick access to the remaining 10 chapters problematic (2Corinthians has a similar issue).

[book] [presented chapters] [actual chapters]
1. Matthew 50 (28)
2. Mark 40 (16)
3. Luke 27 (24)
4. John 36 (21)
5. Acts 34 (28)
6. Romans 24 (16)
7. 1Corinthians 21 (16)
8. 2Corinthians 4 (13)
9. Galatians 31 (6)
10. Ephesians 24 (6)
11. Philippians 22 (4)
12. Colossians 25 (4)
13. 1Thessalonians 29 (5)
14. 2Thessalonians 36 (3)
15. 1Timothy 10 (6)
16. 2Timothy 13 (4)
17. Titus 10 (3)
18. Philemon 42 (1)
19. Hebrews 150 (13)
20. James 31 (5)
21. 1Peter 12 (5)
22. 2Peter 8 (3)
23. 1John 66 (5)
24. 2John 52 (1)
25. 3John 5 (1)
26. Jude 48 (1)
27. Revelation 12 (22)

**Steps to reproduce**
1. Go to any New Testament book.
2. Click the **Select chapter** dropdown.
3. Click on the last chapter as see if it actually takes you to that books correct, last chapter.

**Expected behavior**
The **Select chapter** dropdown should accurately reflect each books chapters.

**Screenshots**
![image](https://github.com/bibletime/bibletime/assets/16984998/3ca19c8f-0108-4470-95d4-4193ecf0ca8a)
![image](https://github.com/bibletime/bibletime/assets/16984998/a5e5c57d-f0cf-4d16-b52c-48ec34dd06a5)

**System information:**
 - OS and OS version: EndeavourOS (based on Arch Linux)
 - BibleTime 3.1.0_dev based on latest 35da62ed792d784193ec281c7950766431b7fa82 (built from source).
 - Built from source from AUR package [bibletime-git](https://aur.archlinux.org/packages/bibletime-git).
 - Sword 1.9.0-11
 - QT5 Webengine 5.15.16-6

**Additional context**
I've had this bug for a long time (a year+), but only today noted the connection with the Old Testament books, and taken the time to report it.
This issue is consistent on both my laptop and desktop (same OS), and has persisted between system re-installs.

**Comment by gholmlund** [comment]
Confirmed that it happens on the master branch. It does not happen with BT 3.0.3.

I cannot work on this during the next two weeks.
