### ISSUE TITLE
[QUESTION] How to I correct Bible texts?

### ISSUE THREAD

**Issue by timotheonb** [bibletime/bibletime#458]
**Background**
I have tried contacting CrossWire to see if I could do some corrections on a Portuguese translation of the Bible. I used the email timjr@lavabit.com. I have not gotten a return answer. 
**Question**
How can I correct a Bible text?

**Comment by jaakristioja** [comment]
I'm sorry, but the BibleTime team does not deal with issues concerning individual works and I don't have the contacts for individual works. I think it were best to ask CrossWire for direction, but I'm not sure myself what the best way to contact them would be regarding such issues. I suggest trying to write to their mailing lists to ask for direction, e.g. sword-feedback@crosswire.org or sword-bugs@crosswire.org if these are still functional, or to sword-devel@crosswire.org.
