### ISSUE TITLE
Does not remember "Stay on Top" - Works Window

### ISSUE THREAD

**Issue by yahonata** [bibletime/bibletime#46]
BibleTime does not remember "Stay on Top" of opened Works Window.
Little inconvenience, great software - BibleTime

My System:
BibleTime 2.10.1
SWORD library version 1.7.3
Qt toolkit version 4.8.6
Kubuntu 14.04

**Comment by jaakristioja** [comment]
Fixed/implemented in git master by [4fc23a837d4794d9bfa298f1784a79ae19ea95ee](https://github.com/bibletime/bibletime/commit/4fc23a837d4794d9bfa298f1784a79ae19ea95ee).
