### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by slackguru** [bibletime/bibletime#461]
**Bug description**
I could not compile fresh clone because I do not meet prerequisites for compiling docs. Then I noticed they are optional so I edited the CMakeLists.txt to allow html docs but not pdf and everything compiled with minor typo errors.

When I execute bibletime --debug this is my output...

(BibleTime 3.0.3) WARNING: Cannot find documentation directory relative to "/usr/local"
(BibleTime 3.0.3) FATAL: Error initializing directory cache!
Please report this bug at blah blah blah
Aborted

**Steps to reproduce**
Edit CMakeLists.txt
Set handbook and howto pdf to off
Save
Compile

**Expected behavior**
At this point everything should run

**System information:**
 - OS and OS version: [Slackware 15]
 - BibleTime Version [3.0.3]
 - How BibleTime was installed [compiled from source code]
 - Sword Version 1.9.0
 - Qt Version 5.14

**Additional context**
I am wondering if it is as simple as adding a language for the html handbook and howto? The language "" is left blank and I believe that means all languages will be compiled...
Also, the SET(GENERATED_DOCS_DIR "/home/slackguru/Code/bibletime_3.0.3/i18n/" is populated and should be included in the install.

/usr/local/bin/bibletime is the location of my binary

Help! I desire the sincere milk on my SlackWare!

**Comment by jaakristioja** [comment]
This should be fixed  in the master branch by commit 4f6a40b0bac8d44b94f52d2795f91a1561d668dd. No plans to backport this at the moment.

**Comment by slackguru** [comment]
This alleged fix was committed prior to my cloning. It obviously didn't fix the issue.

**Comment by slackguru** [comment]
Will you please reopen this issue for discussion? No need for a back port yet. I may find a simple solution such as moving the i18n folder to where it belongs. The comit you referenced also indicates I may simply need to recompile with en language as opposed to blank all languages...

Being closed without discussion doesn't help.

**Comment by jaakristioja** [comment]
> Will you please reopen this issue for discussion?

Discussion may continue regardless of this issue being closed.

> No need for a back port yet. I may find a simple solution such as moving the i18n folder to where it belongs. The comit you referenced also indicates I may simply need to recompile with en language as opposed to blank all languages...

I did not fully understand what you meant, but I doubt it.

> Being closed without discussion doesn't help.

Well, it did help us discover we must both grow in love, patience and humility. :-)

> This alleged fix was committed prior to my cloning. It obviously didn't fix the issue.

I don't know what you did exactly, but the log output you posted does not correspond to what the code in the master branch can output. If you had built BibleTime from the master branch and run the corresponding binary, the messages in the log output would not have been prefixed with `(BibleTime 3.0.3)` but instead with something like `(BibleTime 3.1.0_dev+f28295fdc6bb618434bdd0efb266916477602694)`.

Commit c21c5bcdbdd8a910947809257a3125ec969deb52 might also be relevant.

Please forgive me for being insensitive to your feelings.
