### ISSUE TITLE
[BUG] Gill's commentary installation error

### ISSUE THREAD

**Issue by SoupyGit** [bibletime/bibletime#465]
**Bug description**
Gill's commentary will not install.

**Steps to reproduce**
Settings > Bookshelf Manager > Install Additional Works (uses Internet)
Select 'Gill' version 1.4 (John Gill's Expositor) from 'Commentaries' list > Install Works. 
The program either crashes, or says 'the selected works were not installed'

There is a `gill.conf` file in` /.sword/InstallMgr/20090514005900/mods.d`, but Gill's commentary does not load in the bookshelf upon restarting BibleTime.

**Expected behavior**
Commentary installs, no crash.

**System information:**
 - OS and OS version: Linux Mint 21.3 Cinnamon
 - BibleTime Version: 3.0.2
 - How BibleTime was installed: Installed from 'Software Manager' (mininstall 8.2.9) - not the flatpak

**Comment by SoupyGit** [comment]
Tried this (and other modules from Xiphos repository) using the Xiphos software and it failed there too. Seems to be a problem with the xiphos repository, not with bibletime.

**Comment by gholmlund** [comment]
Thanks for checking Xiphos. 
Closing
