### ISSUE TITLE
Tamil Bible Support

### ISSUE THREAD

**Issue by mangoose20026** [bibletime/bibletime#467]
Is tamil bible is available ? if yes, can you please add the steps to install tamil bible

if not, available can you please add support for tamil bible (https://github.com/godlytalias/Bible-Database/tree/master/Tamil)

**Comment by jaakristioja** [comment]
BibleTime is just a front-end software application to various repositories providing SWORD modules (e.g. Bible translations, commentaries etc). You can install a Tamil translation of a Bible similarly as you would install a Bible translation in any other language, provided that it is provided by a remote library. These remote libraries are hosted by external parties, e.g. Crosswire, Xiphos, ebible.org etc (see https://crosswire.org/ftpmirror/pub/sword/masterRepoList.conf for list of the default remote libraries). We (the BibleTime project) do not host any remote libraries nor provide any SWORD modules by ourselves, so this is not in scope for us. We just develop the software.

I don't know if a Tamil translation of the Bible is available in any of these remote libraries, but you can use BibleTime to look for a Tamil Bible in those remote libraries. If you want to include a Tamil Bible in a remote library, please instead contact the owner of the respective remote library.

Does this answer your question?
