### ISSUE TITLE
[BUG] Flatpak version uses old KDE runtime

### ISSUE THREAD

**Issue by HinzundKunz** [bibletime/bibletime#468]
**Bug description**
When updating the flatpak version from flathub, it tells me that bibletime uses org.kde.Platform//5.15-22.08, which is end of life. It is recommended moving to the latest Qt 5.15-based stable version of the Platform and SDK.

**System information:**
Operating System: KDE neon 6.0
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.5.0-45-generic (64-bit)
Graphics Platform: Wayland
Processors: 6 × AMD Ryzen 5 4500U with Radeon Graphics
Memory: 15,0 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Acer
Product Name: Aspire A515-44G
System Version: V1.12

Bibletime 3.0.3
Sword Library 1.9.0
Qt 5.15.10

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.

**Comment by gholmlund** [comment]
I have  updated BibleTime on flathub. The runtime is now 5.15-23.08
