### ISSUE TITLE
Option to change the font size of the Bible text

### ISSUE THREAD

**Issue by AelblerBL** [bibletime/bibletime#470]
Hello,

I'm working on my notebook (with Linux openSUSE Tumbleweed with Plasma KDE 6). 

I downloaded Version 3.0.3 from (Flatpak) and notice that I can find no a way, either via the <Ctrl> + <+> or <-> shortcut or via the application settings, to change the font size in the Bible text.

I have also noticed that it is not possible to reduce the size of an image or change the focus.
![BibleTime](https://github.com/user-attachments/assets/d2165871-eece-45c8-8680-239993d3be18)
A screenshot is attached; it shows the lineage in the library “Maps and Pictures” of the patriarchs.
It is not possible to display the image as a complete document or to move to a specific part of it.

Of course I could change the font in the system settings of my operating system, but this would then also (negatively) affect the display in other applications.

So if this could be “built in”, I would very much welcome it.
Thank you very much for your great project!

Greetings

**Comment by gholmlund** [comment]
You can set the text size from Settings / Configure BibleTime / Fonts / Language: / Use Custom Font:check /

**Comment by AelblerBL** [comment]
Thanks gholmlund,

I found it!  :-)
After activating "Use Custom Font:check / I was able to change the font size.

👍🏽
