### ISSUE TITLE
Rehaul of library manager

### ISSUE THREAD

**Issue by HinzundKunz** [bibletime/bibletime#48]
I'd like to suggest a more or less major rehaul of the library manager. Right now it is very difficult to update installed books. My suggestion: make it more like synaptic or muon package manager, where you have "repositories" ("sources" in Bibletime), but the list of works is just one. You can then filter for language etc. Newer versions are automatically shown as "updateable", etc...

**Comment by mgruner** [comment]
This seems similar to #4?

**Comment by HinzundKunz** [comment]
Yeah, it's the same. closing
