### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Bauke56** [bibletime/bibletime#481]
**Bug description**
A clear and concise description of what the bug is. Please only describe one issue per bug report.

**Steps to reproduce**
1. Go to 'commentaries, jfb 
2. Click on 'jfb..'
4. The app doesn't work anymore and wants to close. It is the same with the mhc commentary. On these 'commentaries the app stucks, crashes.

**Expected behavior**
 I want to open the 'commentaries. The other commentaires work well.

**System information:**
 - OS and OS version: Ubuntu 24.04
 - BibleTime Version [e.g. 3.1_rc2]
 - How BibleTime was installed [e.g. from system packages, Snap.
 - Versions of modules related to the crash (if known)
 - (If compiled from source) Sword Version
 - (If compiled from source) Qt Version

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.

**Comment by jaakristioja** [comment]
Please provide information requested in the bug issue template and reopen if necessary. If possible, please include a backtrace, e.g. obtained with gdb.
