### ISSUE TITLE
[QUESTION] Bibletime will not start

### ISSUE THREAD

**Issue by realmuddy** [bibletime/bibletime#482]
**Background**
I have uninstalled and reinstalled bibletime several times from flatpack and snap
I am running Linux MX latest version

**Question**
How can I fix this?

**Comment by B-Interactive** [comment]
If you start it from the command line, does it present you with any useful output you might be able to share?

Something like this:
```
/usr/bin/bibletime
```

**Comment by realmuddy** [comment]
I have actually been able to fix this. Sadly I don't remember HOW I fixed it but nevertheless it is. Thanks for responding.
