### ISSUE TITLE
Some greek dictionary modules don't work in magnifier

### ISSUE THREAD

**Issue by HinzundKunz** [bibletime/bibletime#52]
MLStrong, Dodson, RealGreek and Abott-Smith don't work in the magnifier when set as default dictionary. I tried the same settings in xiphos, and they didn't work there either, so it seems to be a problem with the modules...

**Comment by jaakristioja** [comment]
... or with Sword.

**Comment by gholmlund** [comment]
Inverse Lexicons also don't work (InvStrongsRealGreek, InvStrongsRealHebrew). 

I don't see any information in the *.conf file for these modules to be able to distinguish modules that will work for Strong's numbers lookup.

**Comment by gholmlund** [comment]
I debugged using the ESV2011 at Revelation 1:1 using the word "angel". The strongs reference requested for "angel" is "G32".  In Rendering::decodeStrongs (btinforendering.cpp) we remove the "G" and do setKey for "32". This works for StrongsGreek, StrongsRealGreek, and AbbotSmithStrongs. It does not work for MLStrong and Dodson.

If you open all these modules in a window and look for that strongs entry you will find that the entry for  StrongsGreek, StrongsRealGreek, and AbbotSmithStrings is "00032". The entry for  MLStrong and Dodson is "G0032". 

Even if I do a setKey of "G32", the MLStrong and Dodson won't work with that. They need "G0032".

So, in this example I have "G32", "00032", and "G0032". Are there any standards for strongs keys?

**Comment by gholmlund** [comment]
added functionality to detect the leading char and number of digits used by the lexicon. Keys to be searched for to display in the MAG window are reformatted to be consistent with the lexicon module.

Also, filter the entries in the config dialog lexicon combobox to only show lexicons with valid Strong's references as their key. This eliminates the inverse lexicons.
