### ISSUE TITLE
BibleTime module windows will not automatically resize/position when using QWebEngine

### ISSUE THREAD

**Issue by gholmlund** [bibletime/bibletime#53]
BibleTime built with QWebEngine can have the following issues.
1. Module windows will not automatically resize/position as the main window resizes or as auto rearrange mode changes from tile vertical or tile horizontal to tabbed, etc.
2. When using the View mode to show toolbars for module windows in the main window, the toolbars are empty.
3. Multiply module windows are active at the same time. 
These issues may be obvious at startup of BibleTime or later as windows are opened.

This is a fairly critical issue on Windows since we need Visual Studio 2015 compile BibleTime due to c++11 issues. Using Visual Studio 2015 requires us to use Qt 5.6 since it is the first Qt to support VS 2015. Qt 5.6 does not have QWebKit and therefore requires QWebEngine.

**Comment by gholmlund** [comment]
I have spent quite a bit of time debugging into Qt to understand this issue. It is a Qt bug and has been submitted to Qt. 
https://bugreports.qt.io/browse/QTBUG-51565
It is about 2 weeks until the scheduled release of Qt 5.6. I have doubt they will fix this before that release. I do have a simple workaround for this. In BtHtmlReadDisplay during initialization there is a 'setHtml("");' statement. This sets the widget focus on a child of BtHtmlReadDisplay. Either not doing the setHtml or clearing the child focus after the statement, will prevent the problem.

The actual problem can be demonstrated with either Qt 5.5 or 5.6 with using a simple QWidget with focus. A focused QWidget is the trigger for the bug. A simple program demonstrating this was submitted to Qt with the bug report.

**Comment by jaakristioja** [comment]
If this is a blocker for 2.11, please tag this.

**Comment by gholmlund** [comment]
Since Qt 5.6 released today and this Qt bug is not fixed, this is now a must fix for 2.11.0. I should be able to check the fix in tomorrow.

**Comment by gholmlund** [comment]
Fixed with commit  fb42edbd9ccd34840631b121113ff899bb011069
