### ISSUE TITLE
Problem building debug version bibletime

### ISSUE THREAD

**Issue by aaronTHJ** [bibletime/bibletime#54]
I'm having trouble building bibletime. I previously ran into some dependency issues but managed to solve them. Now when I run ./build-debug.sh I get stuck on this prompt:

`[ 12%] Building CXX object CMakeFiles/bibletime_common.dir/src/backend/filters/plaintohtml.cpp.o
make[2]: *** [CMakeFiles/bibletime_common.dir/src/backend/drivers/cswordmoduleinfo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/bibletime_common.dir/all] Error 2
make: *** [all] Error 2
`

I think the problem has something to do with the backend? Or maybe a sword module?

**Comment by jaakristioja** [comment]
That part of the output does not show the actual error. Can you paste the full build output, please?

**Comment by aaronTHJ** [comment]
Here it is:

`[ 12%] Building CXX object CMakeFiles/bibletime_common.dir/src/backend/filters/osistohtml.cpp.o
~/bibletime/src/backend/drivers/cswordmoduleinfo.cpp: In constructor ‘CSwordModuleInfo::CSwordModuleInfo(sword::SWModule&, CSwordBackend&, CSwordModuleInfo::ModuleType)’:
~/bibletime/src/backend/drivers/cswordmoduleinfo.cpp:111:99: error: invalid initialization of non-const reference of type ‘sword::SWModule&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     , m_cachedHasVersion(!QString((*m_backend.getConfig())[module.getName()]["Version"]).isEmpty())
                                                                                                   ^
[ 12%] Building CXX object CMakeFiles/bibletime_common.dir/src/backend/filters/plaintohtml.cpp.o
make[2]: *** [CMakeFiles/bibletime_common.dir/src/backend/drivers/cswordmoduleinfo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/bibletime_common.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by jaakristioja** [comment]
Hmm, I've seen that one before. Its a [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50025) fixed in version GCC 4.9. I [pushed a workaround](https://github.com/bibletime/bibletime/commit/1ae6d2eda7a3c639724770bd0563429f6744c7d1) thou.

**Comment by Geremia** [comment]
@jaakristioja I'm using GCC 5.4.0, and I still get this issue.
