### ISSUE TITLE
Next and Cancel not translated

### ISSUE THREAD

**Issue by Merlignux** [bibletime/bibletime#60]
In BibleTime 2.11 RC1, on the Bookshelf Manager, the buttons for "Next "and "Cancel" are not being translated (to pt, at least...)!

**Comment by gholmlund** [comment]
I have added code to translate the QWizard standard buttons. I made it very similar to "prepareDialogBox" in messagedialog.cpp. It should share some translations we already have in messagedialog.cpp, but the "Finish" and "Commit" buttons are not already translated. I believe we have to do something with lupdate, but I am not familiar with this and the Transflex process. Some help would be appreciated.

**Comment by Merlignux** [comment]
Hi.

As soon as "Finish" and "Commit" buttons land on Transifex for translation i'll translate them to PT but i'm not familiar with the rest of the process either, sorry :)

**Comment by gholmlund** [comment]
Transifex has been updated with my change.

**Comment by Merlignux** [comment]
And i've translated the strings last Thursday!

Thanks :D

**Comment by mgruner** [comment]
👍
