### ISSUE TITLE
Problem with dark display-template

### ISSUE THREAD

**Issue by phdemartin** [bibletime/bibletime#62]
Hi, I'm trying to make a display-template for impaired people like me with bad sight, but I can't get ride of the yellow font highlight in the search results, no trace of this option in the css ?? Look's like a bug

![black_bible_time_theme](https://cloud.githubusercontent.com/assets/19616673/15623442/e12c9516-2449-11e6-9e3e-d9f65bce919b.jpg)

![bible2](https://cloud.githubusercontent.com/assets/19616673/15623486/58240a28-244a-11e6-8dde-b9744e374342.png)

Thank you

**Comment by jaakristioja** [comment]
Should be fixed now. Use `.highlightwords { { /* ... */ }` in CSS to style this. Sorry for the delay!

**Comment by phdemartin** [comment]
No poblem, Thanks


______________________________________________________________
Philippe Demartin

Mail:           phdemartin@gmail.com
Web:            www.demartinenchile.com
tel:            +56 32 277 20 53
Cel:            +56 9 9 278 28 68
Skype:          phdemart
______________________________________________________________

2016-07-19 8:55 GMT-04:00 Jaak Ristioja <notifications@github.com>:
