### ISSUE TITLE
Out-of-date "Tip of the day" tips for 2.11

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#63]
There are several tips in `bttipdialog.cpp` which are outdated. The out-of-date tips should be removed in the stable-2.11 branch (already in string freeze) and updated in the master branch accordingly.

**Comment by gholmlund** [comment]
I removed one tip from stable-2.11. I removed it from master and well as improving 2 other tip.
In the process I found that Strong's Search is not working. It was not working in stable-2.10 also.
