### ISSUE TITLE
Parallel view doesn't work

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#65]
I seem to be unable to display multiple Bibles in parallel. The BtModuleChooser bar seems to be awfully broken. Sometimes it shows works in parallel, sometimes not. The number of buttons is not consistent with the number of parallel works. Removing a work appears to replace it with a "NONE" work.

**Comment by gholmlund** [comment]
I have not been able to reproduce this bug. (Ubuntu 16.04, Qt 5.6, gcc)
