### ISSUE TITLE
Saving chapter as HTML or plain text in parallel view only exports the first module

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#69]
If I have 2 works open in a window in parallel view, when I select "Save chapter as HTML" from the popup and enter the filename, it only outputs HTML for the first work in the parallel view.

Maybe it should, but is confusing to users if this popup menu item is enabled when in parallel view.

**Comment by jaakristioja** [comment]
It seems that saving as plain text has the same issue - it only exports the first open work of the parallel view.

I'm not sure what is the best solution for 2.11. Perhaps we should disable this menu item in parallel view.

For the next version, the exact semantics of this feature should be made more clear to the user by the GUI. Maybe we should provide a means to choose the work to export, or allow exporting the parallel view HTML, or something else.

**Comment by jaakristioja** [comment]
Ok, lets skip this for 2.11.

**Comment by kalemas** [comment]
We definitely need ability to save parallel view, what user sees. At moment there is no way to give a list of modules to CExportManager to export, so it is architecture change as well, if i will know of how headers will change, i would fix implementation.

**Comment by gholmlund** [comment]
Fixed. 
Save to html looks like the text window with a column for each module.
For save to plain text it looks like this:
-----------
I Chronicles 2:1   ESV2011   KJV:
These are the sons of Israel: Reuben, Simeon, Levi, Judah, Issachar, Zebulun,

These are the sons of Israel; Reuben, Simeon, Levi, and Judah, Issachar, and Zebulun,

I Chronicles 2:2   ESV2011   KJV:
Dan, Joseph, Benjamin, Naphtali, Gad, and Asher.

Dan, Joseph, and Benjamin, Naphtali, Gad, and Asher.

-----------
