### ISSUE TITLE
Crash after dragging reference (Qt 5.7 only)

### ISSUE THREAD

**Issue by gholmlund** [bibletime/bibletime#70]
Using Qt 5.7 with BibleTime, open a Bible and drag an underlined reference or verse number out of the Bible window. Even before you release the mouse, the Bible window will be cleared. After releasing the mouse any action that would change the contents of the Bible window will crash. 

When the cursor leaves the Bible window, the attached call stack appears in the console window where BibleTime was started. Knowing that QWebEngine renders asynchronously and looking at the call stack, it can be seen that the thread started by QWebEngine has crashed. This appears to be a Qt bug. It is easy to repeat with Qt 5.7 and I could not repeat it with Qt 5.6.1. 
 
I cannot find a bug in the Qt bug tracker that looks like this. It is not clear how easy it will be to create a example for submitting a Qt bug. 

[callstack.txt](https://github.com/bibletime/bibletime/files/372700/callstack.txt)

**Comment by jaakristioja** [comment]
I added this to the 2.11.0 milestone until we at minimum figure out whether we can do something reasonable about this on our side.

**Comment by gholmlund** [comment]
I had to built Qt libraries debuggable to solve this. Once I understood the issue I was able to create a trivial program to reproduce the bug. The details are at:
https://bugreports.qt.io/browse/QTBUG-54896

Except for turning off the ability to drag references from a BibleTime window into another window, there is nothing we can do about this within BibleTime.

**Comment by gholmlund** [comment]
Perhaps we could put a test for Qt 5.7.0 in the build scripts and disallow it?

**Comment by jaakristioja** [comment]
I don't think that's a good idea, because Qt packagers might patch versions on some distributions. If anything at all, we should search for a workaround. Otherwise I think we should just leave it as is.

**Comment by gholmlund** [comment]
As I said above, the only workaround would be to turn off dragging references from our Bible, etc. windows. I don't think this is acceptable. Since this is a Qt bug I am closing this.

**Comment by jaakristioja** [comment]
:+1: Reopen if needed.

**Comment by gholmlund** [comment]
The Qt team has suggested a work around the crash. I have tested it and will be checking it in now.
See QTBUG-54896

Quote from QT
 **_Re: QWebEngineView will crash when cursor leaves the QWebEngineView display area
Indeed, 5.7 added overrides of dragEnterEvent, dragMoveEvent et al. to enable dragging and dropping. The overrides that the example you attached add prevent that some of those are called while some are still called as they are not overridden. Would it work for the time being to call QWebEngineView::dragEnterEvent in your dragEnterEvent override? This fixes the issue for me, but I do not know what your real world application does in these event handlers._**
