### ISSUE TITLE
Selecting tabed under window mode isn't saved

### ISSUE THREAD

**Issue by fishforbreakfast** [bibletime/bibletime#71]
When changing the window arrangement under "Window - Arrangement mode" to tabbed the tabbed mode isn't saved across sessions.  After bibletime is closed and then re-opened the default arrangement is in place instead of the one selected.  In 2.10.1 and earlier, the selected arrangement mode was saved across sessions.  I am using 2.11.0rc1 with Qt 5.6.1
Regards,

Fred

**Comment by gholmlund** [comment]
This is the same as #68 which was fixed 3 days ago.
