### ISSUE TITLE
Inconsistency in parallel Bible view

### ISSUE THREAD

**Issue by kalemas** [bibletime/bibletime#72]
I have parallel with: KJVA and RusSynodalLIO . For RusSynodalLIO Daniel 1:1 is mapped to Daniel 3:24, subsequent verses are mapped to 14:2,3,4 and so on and are empty.

**Comment by kalemas** [comment]
It is sword issue, fix http://www.crosswire.org/tracker/browse/API-187, closing

**Comment by jaakristioja** [comment]
@kalemas Do you think you could also please file a similar pull request for [Sword++](https://github.com/swordxx/swordxx)?
