### ISSUE TITLE
add Korean translation

### ISSUE THREAD

**Issue by rokmcssu** [bibletime/bibletime#74]
please add Korean translation.
attached file is *.ts file
thanks in advance!

[bibletime_ui_ko_ts.txt](https://github.com/bibletime/bibletime/files/449110/bibletime_ui_ko_ts.txt)

**Comment by mgruner** [comment]
Hello @rokmcssu, thanks a lot for your contribution! I added the file to transifex: https://www.transifex.com/bibletime/bibletime/language/ko/. Please register there to be able to update this and other translations of BibleTime!

**Comment by mgruner** [comment]
I have found your user account on transifex and added you to the Korean team of BibleTime as a translator, I hope that's ok! For future updates, please use transifex only.
