### ISSUE TITLE
Bibletime 2.10.1 keeps freezing when hovering on link.

### ISSUE THREAD

**Issue by x86coder** [bibletime/bibletime#76]
Bibletime keeps freezing when:
1. Running program (with an already open devotional).
2. Hovering over a link (Hebrews 1:14 in SME devotional in English).
3. Waiting for Mag area to update.

The CPU usage goes to 50%. Equivalent to 100% CPU usage on a single-core CPU, but this is Dual-core.

**Comment by jaakristioja** [comment]
Can you reproduce this with the git master or stable-2.11 branch?

**Comment by x86coder** [comment]
No. But I will try.
I'm using binary packaged version from "Linux Mint Cinammon Sarah", released around June 2016.

**Comment by Geremia** [comment]
I wonder if this is related to #57 .

**Comment by entodoays** [comment]
I'm running the flatpak version (2.11.2) on Ubuntu and I do have the issue.

**Comment by gholmlund** [comment]
The code that implements the hover trigger is 100% different code in both Qt and BibleTime. We no longer use QWebEngine. It seems very safe to close this.
