### ISSUE TITLE
BibeTile 2.10.1 does not start on fresh Windows 10 install

### ISSUE THREAD

**Issue by andrew-ivanov** [bibletime/bibletime#80]
Steps I've taken so far:
1. Performed a clean install of Windows 10 64bit version, bg_BG locale.
2. Applied all Windows updates (currently indicating version 1607, build 14393.447)
3. Downloaded BibleTime 2.10.1 from GitHub and installed it
4. Tried to start the program from the Start menu
Observed:
Nothing happens. Mouse cursor indicates "busy" for a couple of seconds and then - nothing. Task Manager also does not list any processes that might be BibleTime

5. Tried to start the program from cmd (in \Program Files (x86)\Bibletime\bin)
Observed:
Calling the bibletime.exe immediately returns me to command prompt. No window is opened, nothing relevand in Task Manager. Adding command line parameters (e.g. '/?', '--help', '--usage', '--debug') has no effect on the behavior.

Please note, I've also tried installing different versions of Bibletime (from 2.11 RC2 back to 2.8.4) with no change observed in the above described behavior.

I've also inspected the Building_on_Windows article in the Wiki searching for any missing dependencies, however I was unable to find any major part missing.

Please also note that as a workaround for BibleTime not cooperating, I had BibleDesktop installed and running on the same Win10 machine.

Please advise on what further troubleshooting steps I can take or if I'm not seeing something from the big picture.

**Comment by gholmlund** [comment]
Andrew,

I have multiple computers that were upgraded from Windows 7 to Windows 
10.  I have been able to run BibleTime 2.10.1 and 2.11.rc2 on them.

First, I assume you had Administrator permissions when you installed 
BibleTime.

Second, I would check Control Panel / Programs / Programs and Features / 
Uninstall. There should be several Microsoft Visual C++ Redistributable 
installs. For BibleTime 2.11.rc2 you should see:
  "Microsoft Visual C++ 2015 Redistributable (x86) - 14.24.212" (you 
might see 14.0.23 or some other minor 14.* variation)

Next, run BibleTime from cmd window with the --debug option. Then look 
for a file in your home directory named BibleTime Debug.txt. If it has 
errors that may tell us something. If it does not exist, then you are 
probably missing some library and the program did not execute at all. If 
that is the case, it is possible to debug this further, but it would 
require installing some tools to be able to do this. I won't go into 
details unless you want to try this.

Gary

**Comment by andrew-ivanov** [comment]
Thank you for your help, Gary.

Once I finally understood where the debug log is, I went in for a new troubleshooting session with that machine. A bit of a disclaimer: As part of previous attempts I had BibleTime 2.11.0 RC2 installed and updated versions of vc-redistributable (x86 and x64) downloaded and installed. So please don't be alarmed by the different version in the logs bellow.

My first run gave me this log:
> (BibleTime 2.11.0_rc2+41a33f43fe3a0727dcda7c8411db43e6e904e858) WARNING: Cannot find ALLUSERSPROFILE\Application Data
> (BibleTime 2.11.0_rc2+41a33f43fe3a0727dcda7c8411db43e6e904e858) FATAL: Error initializing directory cache!
> Please report this bug at https://github.com/bibletime/bibletime/issues

A missing directory is easy to fix, so I went ahead and created "C:\ProgramData\Application Data"
This cleared out the first error and revealed a new one:
> (BibleTime 2.11.0_rc2+41a33f43fe3a0727dcda7c8411db43e6e904e858) WARNING: Could not create user settings directory relative to "C:/Users/??? ??????/AppData/Roaming"
> (BibleTime 2.11.0_rc2+41a33f43fe3a0727dcda7c8411db43e6e904e858) FATAL: Error initializing directory cache!
> Please report this bug at https://github.com/bibletime/bibletime/issues

As you can see a non-Latin part of the path got lost somewhere. The user's $HOME  is "C:\Users\ЕПЦ Перник". Let me state again that this is a Bulgarian version of Win10 and the user was named in Cyrillic.

Are there requirements that the paths be all-Latin that I'm not aware of? 
Please let me know if I can provide you with any other useful info.

**Comment by gholmlund** [comment]
Andrew,

Thanks for your troubleshooting. It seems like you have found a bug in 
BibleTime. The paths you mention are specific to the Windows version. It 
should be able to handle the paths you mention, but it seems it does not.

I may take me a couple of days to confirm this and find a fix for this.

Gary

**Comment by andrew-ivanov** [comment]
Thanks Gary,
Let me know if I can help with verifications once a fix is available.

Andrew

**Comment by gholmlund** [comment]
Andrew,

I believe I have fixed the problem. I am providing a test version of 
BibleTime for you to try.

http://sourcearchives.com/downloads/BibleTime-2.11.0_rc_test-win32.exe

Gary

**Comment by andrew-ivanov** [comment]
Hello Gary,

I've downloaded and installed the the provided file. Bibletime is starting up and loading as expected.
The debug log also does not show anything out of the ordinary.

Thank you for all your help!
Looking forward to the official release.

Andrew Ivanov

**Comment by treestryder** [comment]
When ran unelevated, I found using [SysInternals ProcMon](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx), that it also fails, after being denied the creation of "C:\Program Files (x86)\BibleTime\bin\Bibletime". Should I open another bug report?

**Comment by jaakristioja** [comment]
@treestryder Yes.
