### ISSUE TITLE
Release BibleTime 2.11.0

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#83]
I plan to release BibleTime 2.11.0 from the stable-2.11 branch at least before December 22, in time for Christmas. I finally managed to get the QtWebSomething stuff running on my machine and was able to test and fix a few bugs. There are currently no other outstanding issues in the [2.11.0 milestone](https://github.com/bibletime/bibletime/milestone/6).

@mgruner @gholmlund @greg-hellings @tabthorpe Please comment on
- whether this schedule suits you, and
- whether you want time for further testing, and
- whether you want to push anything to the stable-2.11 branch before the 2.11.0 release, e.g. translation/documentation updates, bugfixes etc.

Personally, I'd like to release this as soon as possible, however I just noticed (by running `make messages`) that somehow a few translatable string changes managed to slip into stable-2.11 after the string freeze, so I guess we'll have to notify translators to update their translations before the release?

**Comment by gholmlund** [comment]
Sounds very good to me.

**Comment by mgruner** [comment]
That's fine for me. @jaakristioja did you already upload the strings to transifex?

**Comment by jaakristioja** [comment]
@mgruner Yes I did a `tx push -s` from the stable-2.11 branch as well as from master. But I don't think I fully understand how Transifex works or is supposed to work, especially with git branches.

**Comment by greg-hellings** [comment]
That timeline fits for me.​

**Comment by mgruner** [comment]
@jaakristioja transifex only supports one branch. That is the stable branch at this point; I disabled the transifex configuration in master. This can be changed when we switch to master before the next major release. I added an announcement on transifex; you can perform a "tx pull" and "make messages" before creating the release in the 2.11 branch to get the updates.

**Comment by jaakristioja** [comment]
@mgruner Thank you very much! I didn't know such announcements are possible.

Its troubling that Transifex is limited to a single branch only. Fortunately we don't currently have an urgent need to maintain translations for more than one branch at the time. I guess we can limit Transifex usage to the latest stable branch only, but I suggest we document the exact procedures for switching the active "Transifex" branch in our [Development cycle](https://github.com/bibletime/bibletime/wiki/Development-cycle) wiki page as well lest we forget.

**Comment by jaakristioja** [comment]
@tabthorpe `make howto` and `make handbook` seem to fail with the following messages:

<pre>
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/nwalsh/html/chunk.xsl"
compilation error: file /home/jotik/develop/bibletime/bibletime.git/cmake/docs/docs.xsl line 3 element import
xsl:import : unable to load /usr/share/xml/docbook/stylesheet/nwalsh/html/chunk.xsl
CMakeFiles/howto_cs.dir/build.make:57: recipe for target 'CMakeFiles/howto_cs' failed
make[3]: *** [CMakeFiles/howto_cs] Error 5
CMakeFiles/Makefile2:2397: recipe for target 'CMakeFiles/howto_cs.dir/all' failed
make[2]: *** [CMakeFiles/howto_cs.dir/all] Error 2
CMakeFiles/Makefile2:410: recipe for target 'CMakeFiles/howto.dir/rule' failed
make[1]: *** [CMakeFiles/howto.dir/rule] Error 2
Makefile:303: recipe for target 'howto' failed
make: *** [howto] Error 2
</pre>

<pre>
Scanning dependencies of target handbook_hu
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/nwalsh/html/chunk.xsl"
compilation error: file /home/jotik/develop/bibletime/bibletime.git/cmake/docs/docs.xsl line 3 element import
xsl:import : unable to load /usr/share/xml/docbook/stylesheet/nwalsh/html/chunk.xsl
CMakeFiles/handbook_hu.dir/build.make:57: recipe for target 'CMakeFiles/handbook_hu' failed
make[3]: *** [CMakeFiles/handbook_hu] Error 5
CMakeFiles/Makefile2:2269: recipe for target 'CMakeFiles/handbook_hu.dir/all' failed
make[2]: *** [CMakeFiles/handbook_hu.dir/all] Error 2
CMakeFiles/Makefile2:2009: recipe for target 'CMakeFiles/handbook.dir/rule' failed
make[1]: *** [CMakeFiles/handbook.dir/rule] Error 2
Makefile:927: recipe for target 'handbook' failed
make: *** [handbook] Error 2
</pre>

Any ideas?

**Comment by mgruner** [comment]
@jaakristioja: you can tweak that in cmake/docs/docs.xsl. Just change it to the path that is available on your system, and it should work (given that docbook-xsl is installed).

**Comment by jaakristioja** [comment]
@mgruner Moved the DocBook issue to #85.

**Comment by jaakristioja** [comment]
I have completed the release procedures for 2.11, announced on GitHub, bt-devel mailing list, bibletime.info, Transifex (with a thanks to all the translators), IRC, crosswire.org. I also pushed an ebuild for 2.11.0 to the BibleTime Gentoo overlay and uploaded a tarball to SourceForge.

Please upload the binaries to GitHub only and **not to SourceForge**.

I changed the SourceForge download button to state

> See message ↖ about moving to GitHub

pointing to the message above which says

> As of 2016-05-16, this project may now be found at https://github.com/bibletime/bibletime.

So if you upload your binaries there and make them default for some platform you will break this message, which is probably not what we want.

**Comment by mgruner** [comment]
@jaakristioja thanks! Windows and Mac binaries are uploaded to github. I'll close this issue now. Merry Christmas!

**Comment by Elimelech** [comment]
> @jaakristioja: you can tweak that in cmake/docs/docs.xsl. Just change it to the path that is available on your system, and it should work (given that docbook-xsl is installed).

How to change the path? What to write in this file?

**Comment by jaakristioja** [comment]
@Elimelech The file should contain filesystem paths to the missing files. You can replace these to point to the actual location(s) where these files reside on your filesystem.
