### ISSUE TITLE
Document managing Transifex for the latest stable branch only

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#84]
Since Transifex can only handle a single branch at a time, it seems reasonable that we only keep the translations of the latest stable branch on Transifex. The procedures for the switch-over need to be documented on the [Development cycle](https://github.com/bibletime/bibletime/wiki/Development-cycle) wiki page.

**Comment by mgruner** [comment]
Done.

**Comment by jaakristioja** [comment]
Thanks! 👍
