### ISSUE TITLE
Search never returns results in Old Testament

### ISSUE THREAD

**Issue by spillmanjr** [bibletime/bibletime#89]
No matter what scope is set or what is searched for, BibleTime search never returns anything for the Old Testament (Xiphos does).  Using Google, I cannot find ANYTHING ANYWHERE about ANYBODY experiencing this problem.  Uninstalled, reinstalled, nothing helps, and this is being experienced on every machine I have access to.  This appears to be the only way to contact you. My personal machine is running Linux Mint 17, BibleTime 2.9.2/SWORD from Repos.  Of all the Bible programs available for Linux, BibleTime is my most preferred.  Your help in nailing this down is MUCH appreciated.

**Comment by gholmlund** [comment]
I have not duplicated this issue using ubuntu 14.04 / BibleTime 2.9.2. Have you tried deleting the search index and rebuilding it. See the Bookshelf Manager "Search Indexes" tab. If this is not the issue, please post the names of the Bible's you are searching.

**Comment by jaakristioja** [comment]
We no longer officially support the 2.9 and the 2.10 series of BibleTime and no new versions will be released for those branches.

Can you please try whether this is still occurs with BibleTime 2.11, the stable-2.11 branch or the master branch? I'm currently closing this issue report. If this still occurs with later versions of BibleTime, please comment and we'll reopen this issue.

**Comment by spillmanjr** [comment]
Deleted index and rebuilt.  No change in behavior was seen in version
2.9.2 (current in Ubuntu repos).  Regarding version 2.11: the build
requirements are beyond what I have access to at this point without
significant burden, so will have to go without for now.  Thank you for
your time.
