### ISSUE TITLE
Bibletime fails to save preferences

### ISSUE THREAD

**Issue by Tsoots** [bibletime/bibletime#93]
Bibletime 2.11.0 fails to save preferences and open windows and their setup. Every time I launch the application I will have to reopen the books and setup the windows. I am running it on Windows 10 64bit and am installing it the regular way.

**Comment by gholmlund** [comment]
This is the same issue affecting bug #90. A wrong directory is being used for settings. This directory may or may not be writable. This leads to crashes or loss of settings.

This is already fixed. We need to release 2.11.1 soon.

**Comment by jaakristioja** [comment]
Closing as duplicate to #90.
