### ISSUE TITLE
FATAL: Error initializing directory cache!

### ISSUE THREAD

**Issue by justineuro** [bibletime/bibletime#96]
[10:07 AM:juro@d8jessie:~/BibleTime/bibletime-2.11.0/build]72$ ./bibletime
(BibleTime 2.11.0) WARNING: Cannot find icon directory relative to "/home/juro/BibleTime/bibletime-2.11.0"
(BibleTime 2.11.0) FATAL: Error initializing directory cache!
Please report this bug at https://github.com/bibletime/bibletime/issues

**Comment by jaakristioja** [comment]
I don't think it is reasonable for BibleTime to support something like this.

**Comment by justineuro** [comment]
Thanks for taking the time!  My apologies for the inconvenience.
Best regards!
