### ISSUE TITLE
Search Not Working Accurately

### ISSUE THREAD

**Issue by adamoell** [bibletime/bibletime#99]
Since moving to Kubuntu 16.04 (clean install) and Bibletime 2.10.1, I have noticed that the search facility is not returning the results it short. For example, doing an 'all words' search for "sojourner fathers" I get no results (tested with ESV and KJV), where I'd expect to find I Chronicles 29:15 and Psalms 39:12. On other searches I get results back, and they are matches, but there are other matches missing. I have tried deleting and creating search indexes, and even reinstalling BibleTime - no luck so far. Never had any issue with the previous versions. Any suggestions as to what could be wrong here - or where I can find .deb packages for 2.11.0 that will work on Kubuntu 16.04?

Many thanks for this very fine program - struggling with the search engine has helped me see just how important BibleTime is to me!

**Comment by gholmlund** [comment]
I was able to duplicate your "no results" with BibleTime 2.10 on ubuntu 16.10. I also do see results with BibleTime 2.11 which I compile from source. We don't have an official ppa, but searching for ppa's on launchpad I found the following:
https://launchpad.net/~jonathonf/+archive/ubuntu/bibletime
Please reply with your results if you are about to test with this ppa.

**Comment by adamoell** [comment]
Thanks for the quick response. I'm testing with the PPA now and will let you know shortly!

**Comment by adamoell** [comment]
Problem persists with 2.11.0, but it didn't rebuild the index - so I think I have a faulty index generated by the old version. It doesn't look like I can delete the indexes any more - the feature seems absent from bookshelf manager in the new version - so will remove and reinstall the texts I was using.

**Comment by gholmlund** [comment]
You can also remove the $HOME/.bibletime/indices directory to remove all indexes.

**Comment by adamoell** [comment]
OK, reinstalled the texts and it rebuilt the indexes - problem solved! Thanks so much for the PPA suggestion. Looks like there was maybe a wee bug in the indexing code in 2.10.1? Anyway, I am back in the game! Bless you all - BibleTime is a mainstay of my sermon and Bible study prep, and these days I do my devotional reading with it, too!
